### ISSUE TITLE
[Question/Feature request] Combo emotes?

### ISSUE THREAD

**Issue by RedSnt** [chatty/chatty#104]
http://prnt.sc/d0bypu

BTTV and FFZ are currently featuring several spoopy emotes like HalloHorns and StabZ - from the picture you can see how they're supposed to be combined.

Is this possible to get working in Chatty?

**Comment by tduva** [comment]
No, it's not possible, at least not easily. Both FFZ and BTTV are Browser-based, so they have access to full-fledged CSS which allows elements to easily be moved around.

While it may be possible to somehow implement this specific use-case in a StyledDocument that Chatty uses to display chat, I have no idea how and it always has the chance of breaking stuff. Considering I have enough other stuff to do and this would only be useful in some parts of the year, it's not something I'm currently looking into.

**Comment by RedSnt** [comment]
Cool beans @tduva. It's not particular important to me either way, just wanted to put it on the radar. Chatty is already close to perfect as is. Especially impressed by badge support.
