### ISSUE TITLE
Cant open stream without livestreamer

### ISSUE THREAD

**Issue by 23rd** [chatty/chatty#106]
Hi.
Chatty has Livestreamer window of options. There is text field "Base command", where I can change command. I tried to change it on "mpv" or "smplayer" but nothing works. It does not work only because there is no protocol in url. If I type manually in smplayer "https://www.twitch.tv/twitch" everything works, but it doesnt with "twitch.tv/twitch". And in chatty I cant use it or change url.
If you add protocol https in url for parameters it should work perfectly with and without livestreamer (youtube-dl+smplayer instead).
![14309215783902](https://cloud.githubusercontent.com/assets/4051126/20076639/a8f6560c-a552-11e6-8c02-5d61efcbb60c.jpg)

**Comment by tduva** [comment]
It's tailored to Livestreamer, so it uses a format it understand. You try to create a custom command using the [/proc](http://chatty.github.io/help/help.html#custom-processes) command that runs whatever program you want.

For example: /smp /proc exec smplayer https://www.twitch.tv/$chan

You can also put that to the Channel Context Menu so you can just right-click in chat and run the command from there.

**Comment by 23rd** [comment]
Thx.

**Comment by mtcjayne** [comment]
I did a quick search through commits and didn't see any changes regarding this. Livestreamer and Streamlink both happily accept URLs that start with "http://" and "https://"
