### ISSUE TITLE
Titlebar doesn't show

### ISSUE THREAD

**Issue by DragonQuiz** [chatty/chatty#108]
For some reason on my surface pro 3 chatty shows the titlebar with all the options checked, but on my desktop it doesn't show. I'm not sure why it does that and no one else here has the same problem.

![image](https://cloud.githubusercontent.com/assets/8675162/20126612/9ee64b2e-a604-11e6-8f89-45b5ef91aedc.png)

**Comment by tduva** [comment]
What do you mean it doesn't show? Like on the screenshot that it just shows "Chatty"? Please check `Extra - Options - Simple Title` (this really should be with the other title options).

**Comment by DragonQuiz** [comment]
Wow thanks that actually worked. Now why was that a thing anyway? And why was it in a different tab when it should, as you put it, be in the _title options_?

**Comment by tduva** [comment]
Some people had issues with window capture with a constantly changing title. It was added before the other title options.
