### ISSUE TITLE
Ability to hide Users list, and Menu list?

### ISSUE THREAD

**Issue by Doty1154** [chatty/chatty#11]
[Enhancement]

The ability to both hide the user list and the menu bar would be a great feature. And also possibly the ability to make the window transparent would be awesome.

**Comment by yunake** [comment]
yeah, ability to hide menu bar, and especially the user list would be really helpful!

**Comment by chatty** [comment]
There are a number of shortcuts to toggle the menubar, userlist and inputbar, although it doesn't save between sessions or channels.

    F10 - Toggle Menubar
    Ctrl-F10 - Toggle Inputbar
    Shift-F10 - Toggle Userlist
    F11 - Toggle "Fullscreen"-Mode (actually only removes the menubar and maximizes the window)

http://chatty.github.io/help/help.html#shortcuts

----
Please use a separate issue for any different requests.

**Comment by Doty1154** [comment]
Oh.. Gotcha, is it possible to also put a button for those settings under view? So that they are easy accessible in case for i forget the hot keys?

**Comment by ZeekDaGeek** [comment]
You used to be able to resize the Userbar as small as you wanted to, it seems like after 0.8.1 it had a minimum width now. It was nice to hide it when you wanted to and drag it back out when you needed it. I'm not sure why this changed.

**Comment by i-cant-git** [comment]
It would be nice if there were additional options (toggle Input bar / User list) under View > Options menu.

**Comment by KaXaSA** [comment]
I saw that in `Main > Settings > Windows > Other` we have the options:
'☐ _Enable userlist by default_'
'☐ _Enable input field by default_'

is it possible to add a 3rd option there for the Menu Bar?
'☐ _Enable menu by Default_'

Also: is it ok to comment in an old closed issue or in this case the 'proper way' to use github would be to create a new issue?

**Comment by ifohancroft** [comment]
I would also love to have the option Enable menu by default.
