### ISSUE TITLE
[Feature request] Clickable link to hosted channel

### ISSUE THREAD

**Issue by RedSnt** [chatty/chatty#111]
So at the moment, when you sit in a channel and they decide to host someone you end up getting a lot of sub notifications (I know you can turn that off), so I was wondering - as the lazy git that I am - if it was possible to make the channel name in the notification message. Maybe something like this: 
"[10:37:28] [Notification] somecooldude just subscribed to #someothercooldude !". 
You know, like in IRC clients. 

So maybe the request is rather to add #channel support.

I hope the meaning gets across - I just want a faster way to join the hosted channel's chat without having to type anything.

**Comment by tduva** [comment]
I'm not sure if the `#channel` format comes up often enough, but I'll think about it. In the meantime you can right-click on the channel and go `Miscellaneous - Join Hosted Channel`.

**Comment by RedSnt** [comment]
Doh, guess I hadn't searched hard enough. Job done 👍.
