### ISSUE TITLE
Double click to mention

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [chatty/chatty#113]
Can you please add option to mention people from chat with double clicking on their name? 
Like with BTTV on Twitch. Username, you double click it and it inserts `@somebody, ` in the input field, not so hard.

And thanks for the nice program! ;)

**Comment by 23rd** [comment]
Or any option for right click / left click to mention username. Cant understand why this function still is not in program.

**Comment by tduva** [comment]
You can add that option to the User Context Menu yourself, via Custom Commands, for example like this: `Mention=/insertword @$1 \`

**Comment by 23rd** [comment]
Finally, thank you very much.

**Comment by EDVAUS** [comment]
Add this command on "Custom Commands" :
/Mention /insertword @$1 \

Then if you want it to appear in the menu when right click then type
 /Mention    in    "User Context Menu"
