### ISSUE TITLE
Word wrap issues in regular chat channels

### ISSUE THREAD

**Issue by TrainerTimmy1** [chatty/chatty#115]
Whenever I do anything other than sending messages (such as switching tabs or even clicking on empty space in the chat area), long lines would suddenly wrap by characters instead. Emotes still wrap around normally. I've noticed this annoying bug since I started using Chatty in 0.8.3 in any window size. Changing the font or turning off emotes in settings didn't solve it.

Here's an example, by switching to a different tab and back:
![image](https://cloud.githubusercontent.com/assets/12021121/21077912/5d407820-bf18-11e6-8f37-63f6e0478d82.png)
![image](https://cloud.githubusercontent.com/assets/12021121/21077896/ed85006e-bf17-11e6-8ec8-7b3b8b84871d.png)

**Comment by tduva** [comment]
Yeah it's annoying, I don't know why it happens.

**Comment by TrainerTimmy1** [comment]
I have some new information about this: This word wrap bug only affects tabs that contain regular channels, such as #twitchplayspokemon and #dansgaming, but I never see word wrapping change in whisper and group chat tabs. I've changed the title to reflect this.

**Comment by tduva** [comment]
Fixed in 0.8.6b1.
