### ISSUE TITLE
Support for the Automod feature

### ISSUE THREAD

**Issue by ceriathstudios** [chatty/chatty#119]
Honestly, i have no idea how it works, but it would be great if we could get something like

[Automod] XY wants to write <msg>

and then use /allow <user> or /deny <user>

**Comment by tduva** [comment]
There will be a separate dialog that lists messages filtered by the AutoMod. Maybe I will add a way to show them directly in chat as well, but this way at least mods can approve/deny messages already.

**Comment by ceriathstudios** [comment]
That sounds great, i dont need it to be directly in chat, i was just asking for any way :) Thanks man!

**Comment by tduva** [comment]
This is now available for testing in [0.8.5b1](https://github.com/chatty/chatty/releases).
