### ISSUE TITLE
Ability to specify the channel to join on start from the command line

### ISSUE THREAD

**Issue by yunake** [chatty/chatty#12]
First of all, thanks a lot, this client is awesome!

I have custom scripts that open a stream in livestreamer and would love to be able to join the chat at the same time, when I start the stream. To be able to do that, I need an ability to specify which channel to join straight on the command line, e.g. `java -jar chatty.jar --channel dendi`.

This should be fairly straight-forward to implement. Would you care to accept a diff for a simple implementation that does not go into proper argument parsing of every possible option and supports only this simple channel option?

**Comment by chatty** [comment]
That already exists: http://chatty.github.io/help/help.html#launch

**Comment by yunake** [comment]
wow, thanks! somehow i missed it, as there's no --help or man page.
this looks really close to what i want, in conjunction with -connect.
