### ISSUE TITLE
Tab completion to complete emoticon names

### ISSUE THREAD

**Issue by GreyAsteroid** [chatty/chatty#122]
A nice ease of use feature available in FFZ and BTTV that I would love in Chatty. An option to enable this for just favorite emotes isn't needed but could be useful. Something that is needed however is an option to either prioritize emoticon names or usernames.

**Comment by Decicus** [comment]
You can already do this, but it doesn't work exactly like BTTV or FFZ (I'd assume). Shift+Tab

**Comment by GreyAsteroid** [comment]
Thanks for telling me! Everything else just uses tab so I assumed that would be the case here.

**Comment by Decicus** [comment]
Yeah, I'm assuming so it's to clearly differentiate between emotes and usernames.
