### ISSUE TITLE
[Performance] [Linux] GIF Emotes Xorg High CPU Usage

### ISSUE THREAD

**Issue by dacrossman** [chatty/chatty#125]
When a channel has a handful of Animated GIF Emotes I'm getting very high Xorg CPU Usage.

I started Chatty in Xephyr (an X Server within a Window) and turned on the visual debugging which shows regions of the screen being painted.

Animated GIFS Inside the chat Window result in the entire chat window being painted for every GIF Frame of every GIF. This causes the Xorg CPU usage to skyrocket.

Animated GIFS inside the Emote Dialog are painted individually. which is expected and does not cause any issues.

**Comment by tduva** [comment]
I don't really know how to test this in the same way on Windows. Can you try the following small program, which just contains a JTextPane with some images and text, to narrow down if the issue lies in the JTextPane itself or how I'm using it: [GifDrawTest.zip](https://github.com/chatty/chatty/files/752443/GifDrawTest.zip)

**Comment by dacrossman** [comment]
Hi Tduva! Thanks for the reply. I've tested GifDrawTest.jar and it results in the entire window being repainted.

I did a screen recording of the Emotes Dialog, the Channel and GifDrawTest.jar. Red flashes on the window is when that region is being repainted.

https://vid.me/FMBb

**Comment by tduva** [comment]
Thanks for your help. So apparently that's just how the redrawing works in the JTextPane and not any of my modifications. I'm not really sure what to do about it though. :(

**Comment by h1z1** [comment]
Got bored and tested this a bit.  Quite seizure inducing I think you're seeing they way Xephyr is intended to operate given it's a lightweight server.  Unlike other technologies like VNC or VirtualGL, Xephyr doesn't have screen diff.  Do you have vsync or gsync enabled?  Might help.

I couldn't find any application that didn't cause a complete screen update.

**Comment by cspack77** [comment]
This seems to work for me: `_JAVA_OPTIONS='-Dsun.java2d.opengl=true' /usr/bin/chatty`

**Comment by tduva** [comment]
@dacrossman If it's not too much trouble could you record the same kind of video with [v0.9.2b11](https://github.com/chatty/chatty/releases/tag/v0.9.2b11) (GIF in chat), I'd be interested what it seems to repaint now. I'd do it myself, but I don't know how to do it on Windows.

**Comment by dacrossman** [comment]
Hey mate, sorry for the late reply :) I haven't been able to perform that specific test, but there is a noticeable performance improvement, good work! :)
