### ISSUE TITLE
Feature Request: Chat buffer limit per channel

### ISSUE THREAD

**Issue by Jacky1356400** [chatty/chatty#131]
I've switched over to use the Windows Standalone Version of Chatty recently to stop the memory leak issues I've experienced in Jar Version. However, I am experiencing "Out of memory" errors (also I've noticed Chatty is limited to use **300MB of RAM** no matter what JVM options I add in the config) with a few channels that has a stupidly fast chat **(e.g. Monstercat, LIRIK, etc.)**.

I know to solve that issue, I can just lower the chat buffer size, but I do need a large chat buffer in some channels that I mod in, so I can find messages without going through the logs.

It would be great if there's an option to set the chat buffer limit as **per channel**, so I can have a low chat buffer in channels I want to lurk in without having to deal with lagging out in stupidly fast chat and a high chat buffer for channels I do want it to be.

**Comment by tduva** [comment]
Where are you adding JVM options? The Windows standalone version is using a 32 bit JVM, so it probably uses a lower default max memory. Since the Chatty.exe is a wrapper for starting the JVM, I don't think you can specify JVM options. You need to put those into `app/Chatty.cfg` under the section `JVMOptions`, for example:

```
[JVMOptions]
-Dsun.java2d.d3d=false
-Xmx500M
```

**Comment by Jacky1356400** [comment]
This is what I've put in Chatty.cfg, memory usage seems to be capped at around 300MB for some reasons.
```
[JVMOptions]
-Dsun.java2d.d3d=false
-Xms1G
-Xmx1G
```

**Comment by tduva** [comment]
That works fine for me. How are you checking the memory usage?

**Comment by Jacky1356400** [comment]
I checked the memory usage via Task Manager.
Kinda weird why it isn't working for me, shall mess around with some more settings.

**Comment by tduva** [comment]
What shows up when you do `/appinfo`? That should show the max memory Chatty is assigned.

**Comment by Jacky1356400** [comment]
Apparently it recognises the 1GB memory, but only doesn't want to use more than around 300MB...

**Comment by tduva** [comment]
Did it throw the OutOfMemoryError with those options, using only 300MB? Or was that before you added those options?

**Comment by Jacky1356400** [comment]
It did throw the OutOfMemoryError with those options before, the options are not changed since then.

**Comment by tduva** [comment]
I don't understand then. If max memory is 1GB it should be able to use that much, unless there is something else restricting it somehow. o_O

**Comment by Jacky1356400** [comment]
Is it possible to manually change the JVM version to 64-bit? I wonder if that'll change anything.

**Comment by tduva** [comment]
I don't think that's possible.

**Comment by Jacky1356400** [comment]
Ah, never mind then.

**Comment by tduva** [comment]
I tested the Standalone Version myself and after a while it did for over 300 MB process usage (up to about 600) and also over 300 MB heap size.

**Comment by Jacky1356400** [comment]
Hmm... I shall try again myself with 2GB RAM allocated and see if it works for me.

**Comment by tduva** [comment]
2GB probably won't even start, since it's a 32bit application.

**Comment by Jacky1356400** [comment]
Not sure, at least I know Minecraft can run with 2GB RAM allocated in 32 bit Java, will try if it works.

**Comment by Jacky1356400** [comment]
Just tested, 2GB indeed doesn't work. The thing is, I need to have my chat buffer on quite a high value so I can trace back some logs without using Notepad to open the log (Notepad++, Atom or other programs opens up the log as empty until I close the app), however, I'll probably get OutOfMemoryError with only 1GB of RAM, so I am using the Jar version for now.

**Comment by tduva** [comment]
Are you positive that the chat buffer actually contributes greatly to memory usage? Have you tested it with different values?

**Comment by Jacky1356400** [comment]
Mine is on 50000 in Jar version, joined 16 active channels, used about 1.2-1.5GB RAM.
Turned down the buffer to 100, only used 500-700MB RAM.
Memory usage also depends on how many emotes (no matter animated or not) in the chat buffer.

**Comment by tduva** [comment]
50k? WutFace

I'll see what I can do about channel specific buffer.

**Comment by Jacky1356400** [comment]
Yeah... I need 50k for the channels I mod in, but lower buffer size for other channels I lurk in for points (revlo, etc.).

Also is it possible to allow other text editors (Notepad++, Atom, etc.) to open chat logs while having chatty open? I really don't like using Windows Notepad for checking logs as its searching feature is useless.
(Or in-app log viewer?)

**Comment by tduva** [comment]
I'm using a `FileLock` on a `RandomAcccessFile`. I couldn't find a way to allow read access while holding the lock. I'll add a setting to remove the locking altogether, then you have to make sure yourself that nothing holds a lock or modifies the file while Chatty writes to it.

**Comment by Jacky1356400** [comment]
Ah right, thank you for doing that.

**Comment by tduva** [comment]
Added in v0.8.5b8.
