### ISSUE TITLE
Uses wrong browser

### ISSUE THREAD

**Issue by moozaad** [chatty/chatty#132]
Linux/KDE5

I click open link and it opens it in Opera. I have practically all the browsers installed (for testing) and the kde default is set to Firefox. xdg-open (from command line) opens the correct browser, as do applications within kde.
I couldn't see any options for browser selection or anything in help.

**Comment by tduva** [comment]
Java must have a different browser default or something. You can try `/set urlCommandEnabled 1` which should then use the `xdg-open` command by default. In addition `/set urlCommand ..` sets the command before the URL (if `urlCommandEnabled` is `true`). Please telle me if it works. I should really document these settings.

**Comment by moozaad** [comment]
Yes, that works correctly now. Thanks.

Looking at the awt docs, it doesn't show where it pulls its browser choice from. I checked KDE's file associations, protocol services and default app settings. It's somewhere hidden.

**Comment by tduva** [comment]
Documented these settings somewhere finally. 👍
