### ISSUE TITLE
Wrong highlight bug

### ISSUE THREAD

**Issue by xinitrc-ls** [chatty/chatty#133]
Not the first time i see it. verion 0.8.4.1
P.S.: @xinitrc_ is me
![untitled](https://cloud.githubusercontent.com/assets/14354528/24086866/7b22de3c-0ced-11e7-9e74-541f330da43d.png)

**Comment by tduva** [comment]
Have you enabled "Highlight follow-up"?

**Comment by xinitrc-ls** [comment]
(Facepalm) Yup.
