### ISSUE TITLE
Add option to hide auto-host options

### ISSUE THREAD

**Issue by justinrusso** [chatty/chatty#134]
Add option to ignore auto-host options, or to only show ones with more than 0 (or some optional amount) of viewers.

I've seen broadcasters complain how twitch will spam them with a ton of auto-hosts, and makes chat unreadable when starting a stream.

**Comment by tduva** [comment]
You can Ignore the auto-host messages. For example: `config:info auto hosting`

**Comment by justinrusso** [comment]
Is there a way to ignore only 0 viewer channels?

**Comment by tduva** [comment]
I don't know the message format.

**Comment by tduva** [comment]
From my own streams I could only find the following two formats:

```
[Info] Name is now auto hosting you.
[Info] Name is now auto hosting you for up to x viewers.
```

If you only want to ignore the ones that don't mention a number of viewers (assuming those are 0 viewer ones), then: `config:info auto hosting you.`

Or if `for up to 0 viewers` exists: `config:info auto hosting you for up to 0 viewers.`

Or ignore all single-digit ones: `config:info re:.*auto hosting you for up to \d .*`

Of course you can add several of them to the Ignore list to match different messages.

**Comment by justinrusso** [comment]
So, for example, I'd go to Settings > Ignore > Click the + icon and enter:
![image](https://cloud.githubusercontent.com/assets/25138621/24670755/531a404a-193d-11e7-9fef-04fb2f8eac72.png)

I'd agree, this certainly wasn't obvious, but I can already see the possibilities.

**Comment by justinrusso** [comment]
Thanks for the help! Just saw the help messages and its clearly in there. woops :(
