### ISSUE TITLE
new update fails to launch

### ISSUE THREAD

**Issue by Baerht** [chatty/chatty#138]
updated to 0.8.5. did a clean install to a empty folder. am running the latest version of java.  watching task manager , you can see java instants start , then hang  then disappear, running on a win vista machine. reinstalled 0.8.4.1  and program runs fine

**Comment by tduva** [comment]
Did you retain the settings from your previous installation? There is an issue with Custom Commands ending in a `\`, although there might be other issues as well.

**Comment by Baerht** [comment]
thanks Ill try that

**Comment by tduva** [comment]
This should be fixed in the new update.
