### ISSUE TITLE
Deprecated Twitch Profile option not removed from Emotes Context Menu

### ISSUE THREAD

**Issue by Jacky1356400** [chatty/chatty#141]
I know in [Chatty 0.8.4 b7](https://github.com/chatty/chatty/releases/tag/v0.8.4b7), the deprecated `Twitch Profile` option has been removed from Channel Context Menu **(using 0.8.5.1)**, but apparently, it still exists in Emotes Context Menu, but only in BTTV Channel Emotes and Twitch Sub Emotes, FFZ is fine.
![BTTV](https://i.gyazo.com/6ab732ea2530bd2f605c5d2294e55b90.png)
![Twitch Sub](https://i.gyazo.com/072ad60ccec6616f3abc96932f8f5dd5.png)

**Comment by tduva** [comment]
Good catch. Should probably just change that to the regular channel URL then.

**Comment by Jacky1356400** [comment]
Alright. That'll work.

**Comment by Jacky1356400** [comment]
Fixed in [0.8.6b2](https://github.com/chatty/chatty/releases/tag/v0.8.6b2).
