### ISSUE TITLE
Request: Add Automodoptions

### ISSUE THREAD

**Issue by TheoSchmitz** [chatty/chatty#143]
Chatty should display Messages that request approval by Automod only visible for the Broadcaster and his Stuff and give them the Option to accept or deny those Messages direkt in Chatty by rightclicking the Message and using an option in a popup.

**Comment by tduva** [comment]
This should actually work by now. Enable showing AutoMod messages in chat under "Moderation" settings and right-click on the name in the AutoMod message to open a context menu or left-click to open the User Dialog which also Approve/Deny buttons now.
