### ISSUE TITLE
Chatty won't connect to one channel

### ISSUE THREAD

**Issue by scerion** [chatty/chatty#145]
I have been using Chatty for a couple years now, and within the last month, one of the the channels I regularly join won't let me join via Chatty.  I have tried on a couple different systems but it just sits in a loop attempting to join over and over without ever joining.

the channel in question is "Lowco2525" 

I connect to about 15 other channels regularly and none have this issue, but this one has spanned a couple versions of Chatty.

My apologies if I somehow end up missing something simple...

**Comment by craftwar** [comment]
Try to open your browser http://twitch.tv/Lowco2525 and you will get the answer.
I  think it's account renaming or deletion.

**Comment by scerion** [comment]
And theres the stupidity showing...I didn't even register it was a name change, ugh. My apologies.
