### ISSUE TITLE
[bug] settings corrupt if run mutiple instances at the same time

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#149]
Accidental double clicks make this happen.

Maybe write settings when closing program. (like many programs do, kvirc ...etc)

**Comment by tduva** [comment]
But it is written when the program is closed.

**Comment by craftwar** [comment]
I think mutiple instances is not the only trigger.  Today, I apply windows update and reboot. Setting file corrupts.

**Comment by tduva** [comment]
Did you close Chatty before rebooting?
