### ISSUE TITLE
0.8.1 404 Not Found Issues

### ISSUE THREAD

**Issue by CanadianJeff** [chatty/chatty#15]
Error Report // Chatty Version 0.8.1 / Java: 1.8.0_45-internal (Oracle Corporation) OS: Linux (3.16.0-45-generic/amd64) / [Memory] total: 165,376 used: 84,250 free: 81,125 max: 1,809,920 [Uptime] 21s

http://pastebin.com/XCYqJ29Q

**Comment by chatty** [comment]
The 404 is not an issue, it's an expected error when there are no emotes for that channel. It's unrelated to the actual error (issue #16).
