### ISSUE TITLE
Dark mode possibility?

### ISSUE THREAD

**Issue by Fen1xMonk3y** [chatty/chatty#154]
Chatty (Version: 0.8.6)
Hoping that sometime in the future releases a dark mode or the ability to change tab, menu bar, and alternate pop out boxes (ie emotes, automod, mod action logs) colors to be something less harsh on the eyes. I have frequent migraines and to help change anything I can to dark colored backgrounds with soothing colored foreground fonts. the blinding colors at the top are just that, blindingly bright.  I'm sure I'm not the only one who wishes for this type of ability.  I would be very appreciative of this type of setting.

**Comment by tduva** [comment]
You can try changing to the System Look&Feel if your Windows theme is dark, although I'm not sure if that works. For a real dark mode there would need to be a fitting Look&Feel, but unfortunately I haven't found one that actually works well.

**Comment by Fen1xMonk3y** [comment]
I have Win 10 latest update (after creators update). I have my system on dark mode (which doesnt dark mode much of anything). The only difference between look&feel and system is the font.  Thank you for trying to help, but none of that helps.

**Comment by tduva** [comment]
Chatty has dark Look&Feeels now.
