### ISSUE TITLE
Suggestion: Options/Features 

### ISSUE THREAD

**Issue by ringstabekk** [chatty/chatty#159]
Adding to tweets I have made, couple of things which would be really nice to see in a future build.

- Opening one window whispers as a start-up channel (Something I mentioned in the past)
- Auto pop-out tabs, possibly a / prerequisite on the Start-up channel name settings 
- Option to keep the User dialog window open after actions have been carried out
- Create Stream Highlight on action or trigger e.g. Sub/Re-Sub Alerts
- Odd one but is there a reason I can't use Crtl+A as a hotkey, wanted to assign it to the address book?

Besides that any idea when the next build release will be, hope the notifications bug is fixed in that?
Thank you for the application and the work you put in to it.

**Comment by tduva** [comment]
Under "Settings - Moderation" you can disable "Close User Dialog when performing action" to keep the User Dialog open.

Ctrl+A might not work if it's some sort of default hotkey (like select all).

Just wanted to mention these, obviously this is a quite old issue, so I'm closing this now. If you want to request any of these things again, please open separate issues for them.
