### ISSUE TITLE
Channel Admin dialog does not support multiple communities

### ISSUE THREAD

**Issue by Jacky1356400** [chatty/chatty#164]
[Twitch recently changed the communities feature](https://twitter.com/Twitch/status/885294563585269762), people can now choose up to 3 communities on the dashboard, like this:
![dashboard](https://i.gyazo.com/9bd92e656377542f12225a6a668c7ccf.png)
However, Chatty will only show the first one shown on the dashboard, like this:
![chatty](https://i.gyazo.com/f749a5bc63f472b5e6505ebc158e87ba.png)
![chatty2](https://i.gyazo.com/12fb18d80411f98d7647865090b70ddf.png)

**Comment by tduva** [comment]
Thanks, although for these kinds of things it's not really necessary to add an Issue, everyone tells me anyway immediately after I read the news myself. Unless you can tell me what the API is, because Twitch hasn't documented that yet.

**Comment by Jacky1356400** [comment]
Ah fair enough. I guess asking about the API endpoint in Twitch dev forum should get an answer.

**Comment by tduva** [comment]
I found out the API myself, so this is in the 0.8.7b1 now. Let's hope Twitch doesn't change it.
