### ISSUE TITLE
UrlOpener not catching exception; Desktop.browse() is not supported

### ISSUE THREAD

**Issue by SebDaMuffin** [chatty/chatty#17]
I use chatty on linux and Desktop.browse() is not supported on most java versions, although Desktop itself is. 
Starting on line 85 of chatty.gui.UrlOpener.java, in the openUrl() method, here's my suggested solution.

``` java
...
if (Desktop.isDesktopSupported()) {
    try {
        if (Desktop.getDesktop().isSupported(Desktop.Action.BROWSE))
            Desktop.getDesktop().browse(new URI(url));
        else
            Runtime.getRuntime().exec("xdg-open " + url);
        return true;
    } catch (IOException ex) {
...
```

All I added is the if/else statement and the action to execute in case Desktop.browse() is not supported. If browse is not supported, java will try to execute "xdg-open [url]" which will open the default browser on most linux systems that have the requirements to run chatty.

**Comment by MeFisto94** [comment]
Note: This is highly platform dependant. appart from ``xdg-open`` which you have with XFCE Desktop-Manager you also have ``kde-open`` or ``gnome-open``. 
Maybe there is something which links to ``xdg-open`` like simply ``open``? (Can't test it since I am not on an unix box right now)

**Comment by SebDaMuffin** [comment]
In fact, xdg-open is desktop-independent and is even used internally in some gnome and kde applications. It is not part of the XFCE project, although I'm sure most XFCE desktops include xdg-open. Read more [here](https://wiki.archlinux.org/index.php/Xdg-open). xdg-open is by far the most portable solution and should be included in most systems by default.

**Comment by MeFisto94** [comment]
Oh that's my fault then :fearful: I thought of it as "xfce-open" which is something different, though. Sorry.

Maybe also add something like if (isOnWindows()) { exec(""start " + url); } which does the same on Windows (I don't know if Desktop.browse isn't already supported on every Windows-Box, though. But it would be a nice addition (who knows, there are some Windows PDAs and Server Editions and whatnot))

**Comment by tduva** [comment]
Added support for native URL opening in v0.8.2b4.
