### ISSUE TITLE
[Request] Custom Command - string case

### ISSUE THREAD

**Issue by KipperK** [chatty/chatty#173]
I would like to propose a new function for custom commands that could change the case of an input.  For example, some websites expect Twitch usernames to be all lowercase so being able to do something like `$lower(1)` would be great.

**Comment by tduva** [comment]
Can you give me an example you would use it in?

**Comment by KipperK** [comment]
The command I was trying to add was for the user context menu.  The code would look something like this:
`.Twitch Tools{2}[v]=/openUrlPrompt https://www.twitchtools.com/channel/$lower(1)`

**Comment by tduva** [comment]
This has been added in 0.8.7b3.
