### ISSUE TITLE
[Request] Selection of 2 Communities in Channel Admin menu

### ISSUE THREAD

**Issue by eVoVitamin** [chatty/chatty#175]
Unfortunately you can select just 1 community for Twitch on Chatty's Channel Admin menu, instead of the possible 2 that can be set directly at Twitch's dashboard.
This is quite a hassle since I'm streaming on 2 different communities and therefore can't really use chatty anymore to change the game title, since it'd also set me back to just 1 community when updating the streams title.

Would be great to have a possibility to either CTRL select more than 1 community, or separate them with a comma.

![asd2](https://user-images.githubusercontent.com/11901016/29224203-9c598ec2-7ec9-11e7-8b51-49e594314c50.JPG)
![asd1](https://user-images.githubusercontent.com/11901016/29224202-9c412d50-7ec9-11e7-9ad3-c6561e52016b.JPG)
![asd3](https://user-images.githubusercontent.com/11901016/29224338-27933fd8-7eca-11e7-8dcf-7825e574abda.JPG)
![asd4](https://user-images.githubusercontent.com/11901016/29224341-29a82f0e-7eca-11e7-8589-1edbc97cca1d.JPG)

**Comment by tduva** [comment]
Download the beta version: https://github.com/chatty/chatty/releases
