### ISSUE TITLE
unban username information missing

### ISSUE THREAD

**Issue by BreezeZin** [chatty/chatty#177]
When a mod unbans a user it only shows "/unban" without the username of who was unbanned. Could this data be added so that it would say "/unban test"?

![unban](https://user-images.githubusercontent.com/7067090/29490914-d73b8d44-858e-11e7-9ade-9008da3b4131.png)

**Comment by Decicus** [comment]
This seems to be a bug with the Twitch PubSub system not including the right parameters for the moderator actions. Should fix itself once Twitch sorts the issue out on their end.
