### ISSUE TITLE
Show sub-tier 2/3 emotes under Emoticons -> Channel

### ISSUE THREAD

**Issue by kunizial** [chatty/chatty#183]

**Comment by EpsilonAlpha** [comment]
In the newest Version (0.8.7) there seems to be a bug:

![emotesnameless](https://user-images.githubusercontent.com/1884282/31112903-d94d8a24-a816-11e7-84f5-298ee3ac649d.jpg)

All Emotesets have no Names anymore, not just the Tier 2 and 3 ones, also the Tier 1 now

**Comment by tduva** [comment]
It's not a bug in that version. The API I was using has been removed. I'll need to update to the new one.

**Comment by EpsilonAlpha** [comment]
Oh okay, thanks for the quick reply! I have faith in you guys to fix it *thumbs up*

**Comment by tduva** [comment]
This all works now in the latest beta.
