### ISSUE TITLE
whispers stopped working

### ISSUE THREAD

**Issue by ahmedtds** [chatty/chatty#184]
I think it stopped after last version. Don't know if it's because version change or because of twitch. It was working fine before. Now whispers don't deliver. I think I can receive but can't send myself. It don't show any error or something but it just don't deliver.

**Comment by craftwar** [comment]
work around: whisper first in twitch website than it will work to the same person.

**Comment by tduva** [comment]
Nothing changed in Chatty about Whispers, this is a common issue that intitiating Whisper conversations via IRC doesn't always work.

**Comment by ceriath** [comment]
Same issue here, even the workaround doesnt help, i have no issues using whispers with an older version of chatty tho

**Comment by tduva** [comment]
What version? Are you whispering the same people? The Whispering code hasn't changed in a while.

**Comment by ceriath** [comment]
i am using the latest 0.8.7
experienced the issue with various people of the last days, neither could start a conversation nor answer.

i tested with 0.8.1 which i still had around, tried whispering multiple people, everything worked without any issues

**Comment by tduva** [comment]
v0.8.1 was still using a seperate connection to the Group Chat Servers for Whispering. It's possible that only some Twitch Chat servers have issues. What did you have configured as Group Chat server in the old version?

**Comment by ceriath** [comment]
irc.chat.twitch.tv:6667

**Comment by tduva** [comment]
That would select one of the chat servers from DNS, so difficult to say what it really used. Might be the port, if that gets you on a different server. But it's all just a guess anyway. There is not much to go on if it simply doesn't work, even though Chatty sends it to the server.
