### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by tduva** [chatty/chatty#187]
Since I want to use a GPL library, I will have to change the license of Chatty. It shouldn't be an issue to release Chatty under the GPL, because all the components are using compatible licenses:

* Main code unter MIT License
* Libraries/Assets under Apache, LGPL, Public Domain, CC-BY and so on

This doesn't mean that those licenses are changed (which wouldn't really be possible without the original authors), rather that the GPL doesn't violate their terms, so the program as a whole can be licensed as GPL.

I was thinking that keeping new contributions to the main code under MIT License would probably be the most straightforward, so that there isn't a lot of mix between GPL and MIT in source files.

Anyone got any thoughts about this?

**Comment by theZorro266** [comment]
I agree that keeping the main code under MIT would be straightforward and imo the best choice for this kind of a project. Just my two cents, because no-one else answered yet.

**Comment by tduva** [comment]
My intentions with this are:

* Be able to use GPL libraries
* Keep licensing as simple and straightforward as possible

I find this whole licensing topic pretty confusing, especially in regards to copyleft. Now it seems pretty clear that the project has to be under GPL as a whole, so that when someone downloads the project that copy is licensed under the GPL. When modifications are made to that it's a derivative of a GPL project and contributing these modifications back has to be under GPL, which means maintaining the code under MIT entirely could be tricky. Of course people could get a pure MIT copy to modify, but I'm not sure if the GPL depency simply being in the project already is an issue there and whether it would require conveying the files separately somehow.

I'm probably overthinking this, but at the moment I'm not entirely sure what the best way is.

@theZorro266 What do you mean by "this kind of a project", that makes MIT a good choice?

**Comment by theZorro266** [comment]
When I think of GPL, I think of a license that lets a party license it's code to be used and modified by others, but any modification needs to be public as well. That in itself is fine, but not always forcefully needed. There is no technical advantage to others not to share their modifications on Chatty and that is why I think the MIT license fits well. I like to use the MIT license myself in projects.

I cannot confirm nor disconfirm your other objections though, because I am not a lawyer.

**Comment by theZorro266** [comment]
@tduva maybe you can look at it this way: When you build this project with the GPL library, the software output will definitely be licensed under the GPL. Which means you should inform the end users of the software that they are using GPL licensed compiled code and they agree to the terms and conditions.

But the source code in this repository may very well be licensed under the MIT and you do not need to change the license for the code here. The MIT license explicitly allows anyone to sublicense the code. That also applies sublicensing under the GPL, which may be the essential part.

The Apache license has different conditions:
```
This licensing incompatibility applies only when some Apache project software
becomes a derivative work of some GPLv3 software, because then the Apache
software would have to be distributed under GPLv3. This would be incompatible
with ASF's requirement that all Apache software must be distributed under
the Apache License 2.0.

[...] This is an identical issue for both GPLv2 and GPLv3.
```

This means that you may not have an Apache licensed assets depend on (or even link to) any GPL licensed material. Correct me, if I am wrong, but it seems like as long as there aren't any non-compatible parts of the end product dependent on any GPL licensed parts, it seems to be fine.

**Comment by tduva** [comment]
That's where I'm not quite clear on. If it already becomes GPL if the files are just lying there together in the repository. I mean the imports of the GPL library are already in the source files, but most other files don't mention the GPL library. Of course compiling everything into one program is pretty clear. By the way, users of the software don't have to agree to the GPL. They only need to adhere to it when they redistribute.

The Apache License 2.0 should be compatible with the GPLv3, meaning I can put an Apache component in a GPLv3 project.

* https://www.gnu.org/licenses/license-list.html.en#GPLCompatibleLicenses
* https://www.apache.org/licenses/GPL-compatibility.html

I think the only issue occurs when I would wanted to add some GPL code into the Apache library. The Apache Software Foundation itself says:

> Apache 2 software can therefore be included in GPLv3 projects

So I would assume that it's fine the way I'm using it. It's not compatible with GPLv2 though. But yeah, this is confusing stuff.

**Comment by theZorro266** [comment]
It is correct that the users do not need to accept the GPL, but this is from their first paragraph (Definitions):
```
An interactive user interface displays “Appropriate Legal Notices” to the extent
that it includes a convenient and prominently visible feature that (1) displays
an appropriate copyright notice, and (2) tells the user that there is no
warranty for the work (except to the extent that warranties are provided), that
licensees may convey the work under this License, and how to view a copy of this
License. If the interface presents a list of user commands or options, such as a
menu, a prominent item in the list meets this criterion.
```
That, at least, seems like a must to me.

About the Apache/GPL mixup: Yeah, you seem to be right. I read it again and it stated incompatibility for all Apache Foundation software projects.

**Comment by tduva** [comment]
I pushed an update with the new license, I hope it's ok. In the program it appears in the help under About / License, similiar to before.
