### ISSUE TITLE
When passing the -channel command to the jar it doesn't do anything

### ISSUE THREAD

**Issue by Doty1154** [chatty/chatty#19]
![2015-09-26_17-07-39](https://cloud.githubusercontent.com/assets/7087748/10120504/2e7a6760-6471-11e5-8a75-bb631382242c.png)
Annnd then nothing
![2015-09-26_17-07-46](https://cloud.githubusercontent.com/assets/7087748/10120503/2e74c756-6471-11e5-9d9b-52762bf0a615.png)
(Unless i'm doing something wrong)

**Comment by tduva** [comment]
What do you expect it to do?

**Comment by Doty1154** [comment]
Well i was expecting it to auto open chatty to the channel i pass the command with

**Comment by tduva** [comment]
It presets the channel, but if you want to connect automatically you also have to pass the `-connect` argument.

**Comment by Doty1154** [comment]
Ah, ok ya. "-channel streamer -connect" works.. Kinda awkward. I mean maybe a "-autochannel streamer" command then? er.. Any who thank you for helping
