### ISSUE TITLE
Option to store settings in file for portability

### ISSUE THREAD

**Issue by ahmedtds** [chatty/chatty#191]
I don't know where chatty stores its settings right now but it would be very useful for me to have an option in maybe advanced tab so if I check it, chatty will store all its settings in an ini file or something at application directory. This would be helpful to make it more portable friendly.

Thanks.

**Comment by craftwar** [comment]
Detection of existence of "portable" file in Chatty root directory is one good implementation. (same as kvirc)
or provides "Chatty portable.cmd"
start /D "%cd%" -jar Chatty.jar -cd
put this file in Chatty root directory and run it

**Comment by tduva** [comment]
Chatty settings are stored in JSON files. What is saved where is detailed in the help: http://chatty.github.io/help/help-guide_folders.html

See @craftwar's answer for an example of how you can start Chatty in a portable way.
