### ISSUE TITLE
[Request] Way to sort currently open tabs

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#197]
Something in settings or a button next to the tabs where you can sort all your currently open streams

**Comment by tduva** [comment]
You can set them to sort alphabetically in the settings.

**Comment by OrangutanGaming** [comment]
Where?

**Comment by OrangutanGaming** [comment]
Oops, I can't read. Sorry

**Comment by OrangutanGaming** [comment]
Is there not a way to do it reversed? So basically A at the top, Z at the bottom

**Comment by tduva** [comment]
That's not a matter of the Tab order, but how the Look&Feel layouts the tab rows.
