### ISSUE TITLE
[Request] Command to switch to a currently open stream, and if not, open it

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#199]

**Comment by tduva** [comment]
You mean put a specific stream on a command? Like `/join <channel>`? Or what to you mean by "switch to a currently open stream"?

**Comment by OrangutanGaming** [comment]
Yeah, something like `/join <channel>`, and it will switch to that stream if it's open already, and if it's not, it will open it

**Comment by tduva** [comment]
Well, that command exists already. Unless by "open stream" you mean open in Livestreamer or something.
