### ISSUE TITLE
[Bug] Huge graphical bugs

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#200]
![image](https://user-images.githubusercontent.com/18350092/32416382-0f15796c-c240-11e7-8fdc-b5531168a603.png)
The only way to fix it that I've managed to find is restarting Chatty

**Comment by tduva** [comment]
This seems to be some issue with the interaction of Java and your system, but I don't know what causes it. Please add your experience to the existing issue and try what is suggested there unless you think it's distinctively different: https://github.com/chatty/chatty/issues/64
