### ISSUE TITLE
Sub notifications

### ISSUE THREAD

**Issue by Fen1xMonk3y** [chatty/chatty#203]
Sub notifications are no longer showing up in chat. I am running latest beta 0.9b2.  This functioned perfectly yesterday 14 Nov 2017 but nothing comes up now in chat itself when a sub comes in. I have changed no settings, and I updated on the day this beta 0.9b2 was released. Again it worked correctly yesterday, but today after the sub gifting was released (which from what im seeing by various devs has broken things). This is helpful for creative and irl streamers especially to be able to see new or returning subs in chat or have their moderators use it as a way to  ping the streamer to alert them.

**Comment by Fen1xMonk3y** [comment]
Addendum:  Appears it is an issue with gifted subs only. standard subs are coming through as are resubs. however gifted subs are not showing up.

**Comment by tduva** [comment]
Message added in v0.9b3.
