### ISSUE TITLE
Timeouts shown as bans in modlog

### ISSUE THREAD

**Issue by ceriath** [chatty/chatty#204]
Twitch: https://i.imgur.com/977wm0j.png
Chatty modactions: https://i.imgur.com/WmngJI2.png

The mod confirmed it were actually timeouts.

Using chatt 0.9b3

**Comment by tduva** [comment]
Chatty simply replicates what it receives from Twitch, so I'm not sure how that could happen, unless Twitch sent the wrong thing. From a quick test it does show correctly `[21:00:28] <tduva> /timeout tirean 600`, so it definitely doesn't happen everytime, whatever the reason.

**Comment by ceriath** [comment]
hm, seems to happen just sometimes atm. probably on twitchs side then
