### ISSUE TITLE
Request for User Info Box

### ISSUE THREAD

**Issue by Fentist1x** [chatty/chatty#205]
Actually there are 2 requests to be precise. 

1)  Is there a way in the user name info box you could show when that username followed the streamer of the chat they are in?  ie Followed on : [date]   or has been following for xdays/months/years

2)  Is there a way in the user name info box you could add a place to see the history of name changes ie name a, name b, name c, turnip (the last being the most recent)?  

Both are things done in ffz, and having them in chatty would make it so i no longer need multiple ways to get all the info I need to moderate better.

For clarification, I moderate for several female streamers, knowing if the account is newly made and followed seconds ago, after having just timedout a number of trolls for sexist remarks, and said new account is starting the same thing leads one to believe it could be possible chat ban evasion.    As for the second, several banned individuals have been known to change from banned name, then contact mods and say i dont know why i was banned. Since the "new" name wasnt the actual name banned, and there is no record of them being in chat, they get unbanned. Then proceed to do the same thing they were banned for. Having the ability to quickly see oh user x used to be user a and were banned for  y reason. no in fact you changed your name from x to a and were banned as x for y reason. im sorry, no you cant be unbanned just because you changed your user name.

these are examples seen in the chats i moderate very often.  I for one would love the ease of having all of this info in chatty.

Thank you for all you do. Chatty makes moderation 1000 times better. Please keep up the amazing work

**Comment by Helimyne** [comment]
I would like to add to this request for a save the info/chat that pops out to a separate doc file, ex: .txt
This would be extremely helpful to save something for later whether for mod or give away purposes.

**Comment by tduva** [comment]
Follow status has been added. As for name change info, this is currently not planned, but you can easily open a website this info by adding a button to the User Dialog like this:

    Namechange=/openUrl https://twitch-tools.rootonline.de/username_changelogs_search.php?q=$$1
