### ISSUE TITLE
Feature - Add date to timestamps

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#206]
Add dates to timestamps or an option to post the date before the first message of that day so it is clear which messages are for which day, like so messaging apps do

**Comment by tduva** [comment]
You can set the timestamp to whatever you like using setting commands: http://chatty.github.io/help/help-setting_commands.html#time

**Comment by OrangutanGaming** [comment]
How? I ran `/settings timestamp [dd]` and it brought up the settings popup

**Comment by tduva** [comment]
Example: `/set timestamp [YYYY-MM-dd HH:mm:ss]`

**Comment by tduva** [comment]
Of course it's impossible to add all formats someone could want, but I'll add a few ones to the Settings Dialog to make it easier.

**Comment by OrangutanGaming** [comment]
Are there docs for the formatting and what each character/capitalisation means?
