### ISSUE TITLE
Chatty Window refuses to Focus

### ISSUE THREAD

**Issue by Jai-Brown** [chatty/chatty#208]
I tend to leave Chatty running at all times to log the chat of the channels I'm modded in, especially when I might not be around. Lately, when attempting to use the application after some time, it refuses to take focus and seems to become unclickable, resulting in the window behind it taking focus. I'm even getting the desktop context menu when right-clicking.
The only solution is to restart the application, which sucks halfway through modding a stream.

![Won't focus](https://i.imgur.com/jravV95.png)

**Comment by tduva** [comment]
Have you tried the standalone version?

**Comment by sdaugherty** [comment]
I see this as well, what I have been able to do to fix it is give chatty focus by selecting it from the taskbar, and then resize the window with the windows key and arrow key (windows + up arrow, etc), which I think is only an option in Windows 10. Happens almost constantly when playing a fullscreen game for me.

**Comment by Jai-Brown** [comment]
I've actually started getting this issue a lot with other applications now. I think it's a Windows problem. Closing issue, would have done so earlier, but I totally forgot it even existed....
