### ISSUE TITLE
Command line login via token

### ISSUE THREAD

**Issue by bastimeyer** [chatty/chatty#21]
Hi,
the [command line login via token](https://chatty.github.io/help/help.html#launch) seems to be broken.
The token I'm using (which is including the `chat_login` scope) is being created by [another application](https://github.com/bastimeyer/livestreamer-twitch-gui) in which I want to integrate Chatty into. So the launch parameters pretty much look like this
`-connect -single -token {token} -channel {channel}`, but this is leading to the following error message: "Cannot connect: Incomplete login data."... 
From what it looks like, [the token will only be read from the settings](https://github.com/chatty/chatty/blob/5af75b549f138add9c9e176af7ea57df6401ec9d/src/chatty/TwitchClient.java#L551), instead of the arguments list.

Thanks!

**Comment by tduva** [comment]
It get's [saved in the settings](https://github.com/chatty/chatty/blob/5af75b549f138add9c9e176af7ea57df6401ec9d/src/chatty/SettingsManager.java#L452) from the argument. Try setting the `-user` as well.

**Comment by bastimeyer** [comment]
Ah ok, thanks! Didn't see that, I just had a quick look into the code as I was running into this issue.
I thought passing the token was enough, because the username actually is a redundant information. I mean, I know that it's required for an IRC authentication, but with the token, you could check the API for the username and also validate it and check scopes.

Off topic:
While working on this last night I came across a NullPointerException, the GUI didn't appear and the process also didn't terminate and instead kept logging like crazy. I deleted the log files afterwards, but now I think this was stupid as I should have reported this issue. Unfortunately, I'm unable to reproduce this right now. :disappointed: I'll open up a new issue thread if I come across this issue again.

**Comment by tduva** [comment]
Thats how I do it for regular authentication, but it doesn't work for the commandline argument. I'd rather keep it this way for now unless it's really inconvenient for you to supply the username.

**Comment by bastimeyer** [comment]
No, it's fine, thank you...
