### ISSUE TITLE
Command to favorite and unfavorite a channel

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#210]
`/favorite` and `/unfavorite`

**Comment by h1z1** [comment]
any reason /follow and /unfollow  don't work?  

Channels->Live Channels to bring up a list.   Amazes me how blind Twitch web is to even simple things like this.

**Comment by OrangutanGaming** [comment]
That sounds like a separate issue. Also, mine works fine

**Comment by ripslayer** [comment]
Would love to have this

**Comment by tduva** [comment]
`/favorite` and `/unfavorite` to modify the channel favorites will be in the next version.
