### ISSUE TITLE
[feature] Color Messages based on rules

### ISSUE THREAD

**Issue by marcmagus** [chatty/chatty#213]
Basically the same as a highlight with color:<color>, but without the inherent side-effects of a highlight such as notifying the user and copying to the highlight window.

At the front-end, will want its own tab in the settings dialog.

The ability to recolor portions of a message based on a regexp would be ideal
(e.g. user:NightBot s/^(\w+) (has been live for) (.+)/{cyan}$1{white} $2 {brightcyan}$3/)

**Comment by tduva** [comment]
Coloring portions of the message sounds nice, but it would require much more changes. Coloring the message is basicially already set up.

**Comment by tduva** [comment]
Added in v0.9b4.
