### ISSUE TITLE
[Feature] Report User

### ISSUE THREAD

**Issue by marcmagus** [chatty/chatty#216]
It would be good to have an option to Report a user for violating the Twitch TOS directly from chatty, via the window which appears when clicking on their name.

Currently it's possible to ban, but reporting requires going to the Twitch page. If this functionality is exposed by Twitch API it would be good for chatty to support it.

**Comment by tduva** [comment]
I don't think this is possible with the Twitch API.

**Comment by Fen1xMonk3y** [comment]
//Report[R],   added to user dialog buttons with:   /Report /openURL https://twitch.tv/$$1/report_form  added as a custom command.  works very well.  puts the Report as a button on the name card, and when pressed takes you to the website for reports and auto inputs the users username

**Comment by tduva** [comment]
I understood the request as having a report form directly in Chatty, without having to go to the website at all, which isn't possible.

Opening a direct link is indeed the most best solution at the moment it seems. Maybe it helps someone out.

**Comment by marcmagus** [comment]
My hope had been to have it directly in Chatty, but if the API doesn't allow it this is a great workaround, thanks. Would be a good addition to the handbook.

**Comment by marcmagus** [comment]
Twitch seems to have made an update which makes https://twitch.tv/<user>/report_form no longer function. Has anybody discovered a way of doing this using the new UI?

**Comment by Tomparkes93** [comment]
> Twitch seems to have made an update which makes https://twitch.tv//report_form no longer function. Has anybody discovered a way of doing this using the new UI?

new link is https://twitch.tv//report

**Comment by marcmagus** [comment]
Thank you!
