### ISSUE TITLE
Add setting for closing Emote Dialog when double-clicking on emote

### ISSUE THREAD

**Issue by GreyAsteroid** [chatty/chatty#22]
Not sure if this is meant to be a feature but it's a pain in the ass as multiple channels I follow have subs spam sub emotes when someone subs. If double click to close is an intended feature I ask that it becomes an option.

**Comment by tduva** [comment]
It is intentional. I'll try to add a setting for it.

**Comment by GettCouped** [comment]
Yes please.  I would like it to be a setting as well.

**Comment by tduva** [comment]
Added (e737a2dd495ec34924fb76307b4bf9510022ea44).
