### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by tduva** [chatty/chatty#221]
Based on [this PR](https://github.com/chatty/chatty/pull/220) which is a proposition to add some multilingual support to Chatty, I researched what Java offers itself and came across the [`java.util.ResourceBundle`](https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html) class, which gets a `Locale` object and then loads the appropriate key/value pairs from Java properties files. The hardcoded strings in the program are replaced by calls to that `ResourceBundle` object (via a Singleton class for convenience I guess).

I've already did some tests with it and it seems to work fine. I added a setting to the GUI to switch between English and German (with restart required). Any terms that don't exist in German are taken from the English file (or rather from the "reference" file, which contains all keys, but is in English of course).

### Scope of the translations
Now especially translating all of the help would be too much work, and we would probably constantly end up with varying out-of-date versions in different languages. So it would probably be best to focus on the basic functions in the GUI, so that users who don't understand English very well are able to use the program. However, using English might still be recommended for users who understand it, especially for advanced usage, since the help will refer to the English terms used in the GUI.

### Translation workflow
Figuring out which keys are already translated in which language (especially if new ones are added), the order they appear in (to keep it organized and easy to track through changelogs) sounds pretty annoying, so I think some kind of tool would be necessary that handles that.

This could be:
* A local tool (or none), which each translator could decide themselves. No dependance on anything in particular and each translator just creates Pull Requests for changes.
* An online tool, where several people can collaborate, and translations are centrally exported into the correct format. This ensures that the translators don't have to worry about the format being correct (especially the order of keys and encoding of properties files, which have to be in ISO-8859-1). And of course it makes it easier for several people to work on the same language.

Does anyone have any suggestions for tools/websites? I've looked at [poeditor.com](https://poeditor.com) which has a free plan (and is free for OpenSource projects anyway, if more strings are needed), but I don't know if there might be better alternatives. I'm not very satisfied with their export options, but I can work around that.

Any thoughts on any of this?

**Comment by tduva** [comment]
The encoding is part of the Java properties file format. The `ResourceBundle` class reads those files with ISO-8859-1 encoding and editors that are aware of the file format (like when I edit the file in NetBeans) write it as such as well. There are two ways to handle this:

* Provide custom code for the `ResourceBundle` class to load it in UTF-8
* Encode properties files in ISO-8859-1 and use Unicode escape sequences for any non-latin characters

Both ways seem like a valid option. But either way, because of this annoyance of not just having UTF-8 as the standard encoding for these files, it seems better to do the encoding/formatting in a centralized process, simply for the reason that the encoding will be clear then and there won't be one translator handing in UTF-8 files and another ASCII with Unicode escape sequences (maybe without even noticing, just because their editor saved it that way).

**Comment by tduva** [comment]
I've decided to load the properties files with the UTF-8 encoding by using a custom `ResourceBundle.Control`. This makes it easier to read the files in the repository itself (like checking the history or whatever).

It would also be possible to commit UTF-8 files and then convert them in the build process, but this seems more straightfoward. Of course programs that know to encode properties files in ISO-8859-1 will have to be configured differently, but that's not a big issue, especially if the translations mainly happen through a web interface.

**Comment by tduva** [comment]
I pushed a commit containing some translation preparations: https://github.com/chatty/chatty/commit/14ce46fd375c763c3626f1ba2275e20dcd2b1e8b

I replaced many hardcoded strings from the Main Menubar, Admin Dialog and Channel Info dialog. I also created a translation project you can join: https://poeditor.com/join/project/1Lld6f5Swi (I think I have to approve new contributors, which I'll do if I recognize your name)

@magiruuvelvet I added Japanese on there as well, if you want to contribute (since you had that in your PR).

**Comment by craftwar** [comment]
I think https://crowdin.com/ may be better. It doesn't request so many data. (public e-mail only, obs use this)

**Comment by tduva** [comment]
What data do you mean? The only things you need to enter are an email address and nickname, seems pretty reasonable to me.

**Comment by craftwar** [comment]
Never mind, I create account without link github with another e-mail. Can you add Traditional Chinese?
If you link github, it can all your private date. I don't like this.

**Comment by tduva** [comment]
Yeah, it wants all that access for GitHub integration, I didn't want to do that either.

I added Traditional Chinese. Are you the one who registered with the name "add traditional chinese"?

**Comment by craftwar** [comment]
yes, I will change name later

**Comment by craftwar** [comment]
I don't know why my status becomes pending. (It's okay now) Maybe quit translation means "leave this project", I just wana leave page. (no quit confirmation...)
UI is not good, can't read other language translation for reference. (Simplified Chinese and Japanese)

http://crowdin.net/ is definitely better choice, but not free. Many good features ex: vote system.

**Comment by tduva** [comment]
I looked a crowdin.net and found it pretty confusing.

**Comment by craftwar** [comment]
What do you mean?
My joined projects
https://crowdin.com/project/discord
https://crowdin.com/project/obs-studio

**Comment by tduva** [comment]
I mean that I find the interface and navigation not very intuitive.

**Comment by magiruuvelvet** [comment]
@tduva I registered using GitHub on POEditor now. It says `(pending)`. I guess you need to approve me first? Can't do anything yet. Name is the same.

**Comment by tduva** [comment]
Yes, I approved you.

**Comment by craftwar** [comment]
@tduva can you approve "append" join Traditional Chinese? He is Chinese Chatty user and writes some Chinese tutorials.

**Comment by tduva** [comment]
Sure.

**Comment by gOOvER** [comment]
Transifex.com

**Comment by Appendko** [comment]
@tduva I've put the current Traditional Chinese translation into chatty and found something is wrong in viewer history. (channelInfo.viewers.*)
![](https://i.imgur.com/zySMiOu.png)

**Comment by tduva** [comment]
I have an idea what causes it, so I should be able to fix it once I get around to it.

**Comment by tduva** [comment]
@Appendko I've changed the font for the viewer history in a recent commit, if you want to test if it shows up correctly for you now.
