### ISSUE TITLE
[Feature Idea] Streamlink quality menu display string

### ISSUE THREAD

**Issue by magiruuvelvet** [chatty/chatty#225]
I made a change to the quality menu of Streamlink to specify a string which to display in the menu rather than the raw quality name. This make is possible to create a more readable and nice menu to select the quality. Specially for the fallback options from a PR made in the past my quality menu was the pure unreadable evil and I needed this change.

**Implemented in https://github.com/magiruuvelvet/chatty/commit/c3008a6d6c091052f6c86bf64d2a484b6aa89732**

---

**Example:**

This one:
```
{Best Quality,best},{Worst Quality,worst},{Select Quality,select},|,{1080p (60fps/30fps),1080p60,1080p60_alt,1080p,1080p_alt},{1080p (30fps only),1080p,1080p_alt},{720p (60fps/30fps),720p60,720p60_alt,720p,720p_alt},{720p (30fps only),720p,720p_alt},{480p,480p,480p_alt},{360p,360p,360p_alt},{Mobile (240p),240p,240p_alt},{Mobile (160p),160p,160p_alt},|,{Audio only,audio,audio_only}
```

Transforms into:
![contextmenu](https://user-images.githubusercontent.com/13280758/27496589-e35921be-5856-11e7-9a88-a9af8b1fb41d.png)

And internally it uses the actual quality/qualities which is/are now hidden from the UI :wink:

**Comment by tduva** [comment]
I don't like that it's not compatible with the current format. So for example `{1080p60,1080p,720p60,720p}` would turn into the qualities `1080p,720p60,720p` with the display name `1080p60`. I'd rather use a different separator for the display name, for example like this: `{Best:1080p60,1080p,720p60,720p}`

Based on this I've changed the code, cleaned it up a bit and also refactored it for Unit Tests of the parsing.

**Comment by tduva** [comment]
I added it in [this commit](https://github.com/chatty/chatty/commit/b1ef304e0286d9cd5133297c68142cecc634fa97) if you want to take a look.
