### ISSUE TITLE
Chatty freezes when pasting a very big content from clipboard

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#228]
program crashed. I think log file path is copied to clipboard. I paste to Chatty. Chatty freezes. (12% CPU usage)

It's log content (56,056 bytes)

**Comment by tduva** [comment]
You copied the contents of a whole log file into the inputbox? I'm not surprised it would freeze then.

**Comment by craftwar** [comment]
Yes, but there should be some way to prevent this.

**Comment by tduva** [comment]
The chat input box and some others are restricted in length now, so this issue should be mitigated somewhat.
