### ISSUE TITLE
Custom Commands - Execute multiple commands

### ISSUE THREAD

**Issue by OrangutanGaming** [chatty/chatty#231]
Is there a way to make a command e.g. `test`, where it will run 2 commands? Doing something like `/test /echo $$1 /follow $$1` isn't treated as 2 commands, instead just echos `$$1 /follow $$1` (with replacements)

**Comment by tduva** [comment]
No, that's not possible.

**Comment by OrangutanGaming** [comment]
Are you able to use something like `|` to mark it as separate?

**Comment by craftwar** [comment]
How about adding scripting support? You don't need design command syntax any more.

**Comment by OrangutanGaming** [comment]
That would be super useful, especially for super specific commands
