### ISSUE TITLE
Cannot connect incomplete login data

### ISSUE THREAD

**Issue by kempol** [chatty/chatty#237]
just got this message and i didnt change any setting, i also have requested login data and it says 'access token received'. but in chatty im still not logged in

**Comment by tduva** [comment]
What do you mean by "not logged in"? What does it say in the Login configuration when you Verify login?

**Comment by kempol** [comment]
the account name is empty even after i requested login data

**Comment by kempol** [comment]
ok its working again eventhough i didnt do anything

**Comment by tduva** [comment]
It's possible that it was a Twitch issue. Maybe their API was returning something unexpected, which caused Chatty to not fill out the name.
