### ISSUE TITLE
[Feature Request] UserIDs & Followed Since on User Dialog

### ISSUE THREAD

**Issue by Louwizz** [chatty/chatty#238]
Please can you add the User's ID & the Followed Since date to the User Dialog box? FFZ had these feature via it's website plugin, but they no longer work since the Twitch website update. Thanks.

**Comment by Fen1xMonk3y** [comment]
basically the same as Request for User Info Box #205   requested in Nov 2017.  Still would love to see this implimented.

**Comment by tduva** [comment]
What's your use case for having the User ID shown?
