### ISSUE TITLE
0.9.1b2: First time subscriptions/subs without text not shown in chat

### ISSUE THREAD

**Issue by johnmcdee** [chatty/chatty#242]
Hi,

First of all thanks for chatty, using it nearly everday,  really like it :)

I noticed something when trying 0.9.1b2:

First time subs/subs without "share"-text are not shown in chat anymore with 0.9.1b2 for me. When downgrading to b1 it is working again.

Sub with text are still shown in chat:
![re_subs_are_shown_in_chat](https://user-images.githubusercontent.com/6623698/37219946-56b80672-23c5-11e8-8b49-9f3a7c55db34.jpg)

Sub without text/first time subs are not shown in chat:
![subs_not_showing_up_in_chat](https://user-images.githubusercontent.com/6623698/37219947-56d23254-23c5-11e8-9821-2a8f2912c0ab.jpg)

Only Twitch Prime subs on the screenshot but I'm pretty sure this affects regular subs as well.

Used Release: Chatty_0.9.1b2_hotkey_64bit.zip
Java version: Version 8 Update 161
OS: Windows 10 1709 Build 16299.125

**Comment by tduva** [comment]
I'm aware of it, thanks for the excellent report though. Try the new beta.
