### ISSUE TITLE
own messages

### ISSUE THREAD

**Issue by a-o-w** [chatty/chatty#246]
Hi
After update to 0.9.1 Beta 2(3,4) i cant see my own (my bot) messages
<img src="https://i.imgur.com/SL1UfZa.png" title="source: imgur.com" /></a>
<img src="https://i.imgur.com/XwByAo1.png" title="source: imgur.com" /></a>
<img src="https://i.imgur.com/xEOFbxm.png" title="source: imgur.com" /></a>

or i blind and do not see something in changelog ?%)

**Comment by tduva** [comment]
When you send a message then messages received from the same account within a few seconds are ignored. This is to prevent own messages to appear twice in chatrooms, where each sent message is echo'd back for some reason.

**Comment by tduva** [comment]
This will be restricted to chatrooms and also based on message text in the future, which should work as long as Twitch doesn't modify the message text somehow.
