### ISSUE TITLE
Can't use pageup/down scroll chat window

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#247]
win10 64 bit
Java(TM) SE Runtime Environment 18.3 (build 10+46) from oracle

I am not sure how to 100% reproduce it. I find this bug when I switch to other application window and click chat window in Chatty. I don't have this issue in last Chatty version.

**Comment by tduva** [comment]
The new inputbox based on JTextArea has it's own binding for it (jump to start/end), so if the focus is on there it won't scroll chat. This should be fixed soon.
