### ISSUE TITLE
Doesn't load messages and users

### ISSUE THREAD

**Issue by Tnebi** [chatty/chatty#25]
When I join big channels with a lot of viewers I just load the moderators and I can't see any message posted... I tried to let it load for a while but nothing happens.
![immagine](https://cloud.githubusercontent.com/assets/1217976/10617507/3b6e123e-776b-11e5-9922-c6181af816cf.png)

As you can see there a lot of viewers but no messagers/normal users. (s4 is an exception because he was mod when I joined the channel in Chatty)

**Comment by tduva** [comment]
See [Event Chat](http://chatty.github.io/help/0.8.1/help-short_guides.html#eventchat).
