### ISSUE TITLE
JDK9 and later are not supported

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#252]
gradle wrapper should be upgraded to support newer JDK.
/appinfo always display JDK8 should be fixed.

**Comment by tduva** [comment]
I don't understand what you mean by not supported. Does that gradle version not work with JDK9? The JDK8 debug output is a constant in the code, it will always say JDK8 because that's how I compile it. If you compile it yourself you should know how you compiled it anyway.

**Comment by craftwar** [comment]
Old gradle version can't handle JDK9. If you don't make it display which version JDK is used, it is meaningless . 7th byte of class file is version of class file format. I don't know other method because I don't write java.

**Comment by lewisje** [comment]
Maybe this issue is why Chatty's CPU usage spikes so much on Java 9 and Java 10 (even as of today).

**Comment by Dessa** [comment]
the latest release seemingly has support for jdk10, it builds and works here

as far as "JDK8" in the version string goes, this is seemingly hardcoded since forever (https://github.com/chatty/chatty/blob/master/src/chatty/Chatty.java#L74)

**Comment by tduva** [comment]
The "JDK8" was only an information for myself for debugging purposes, so it was meaningful for me when I needed it.

Closing now since Gradle is updated.
