### ISSUE TITLE
automatically growing inputbox cannot store message with down arrow when grown

### ISSUE THREAD

**Issue by dbkynd** [chatty/chatty#256]
```Changed chat inputbox to automatically grow when entering long lines```
When the input box grows two 2 lines+, pressing down to 'save' a typed message does not work. The current message remains visible.

**Comment by tduva** [comment]
You need to hold Ctrl or disable `On a multirow inputbox require Ctrl to navigate input history" in the Chat settings.

**Comment by dbkynd** [comment]
Ah-ha! Yup. There it is. Thanks!

**Comment by tduva** [comment]
I forgot to really document that though, so I'll do that now. :)
