### ISSUE TITLE
emote tooltips

### ISSUE THREAD

**Issue by mammothbane** [chatty/chatty#259]
Small QoL feature request: it'd be nice to have emotes show their name in a tooltip on hover, like in web Twitch chat. Just a bit easier than having to click and get the popup window if all you want is the name.

![tooltip-hover](https://i.imgur.com/fXv9rEl.jpg?2)

**Comment by tduva** [comment]
Yeah, I've been thinking about this as well. You can also right-click to open the context menu for the name, but it's still not very convenient. It might get annoying to have stuff pop up all the time, but I can always add a setting to disable it if it annoys anyone.

I've added this now for the next version, for badges as well.
