### ISSUE TITLE
make notifications integrate in existing notification systems with f.e. Ubuntu

### ISSUE THREAD

**Issue by greenbigfrog** [chatty/chatty#26]
Thanks for your great tool!

I would like to see chatty not to use his own notification system but to use the existing notification system that is shipped with ubuntu/(almost) any distro.

Some info:
- [ubuntu wiki](https://wiki.ubuntu.com/NotifyOSD)
- [askubuntu](https://askubuntu.com/questions/347946/how-to-raise-user-notifications-in-ubuntu-using-java-code)

I tried to do it myself but I failed and it really would be a nice enhancement :smile:

**Comment by ivazqueznet** [comment]
Or even have the option to run an external command with substitutions for expiry time and other parameters so that `notify-send` or other notification commands can be invoked appropriately.
