### ISSUE TITLE
For launching Livestreamer or Streamlink and selecting a quality less than or equal to desired vertical resolution

### ISSUE THREAD

**Issue by mtcjayne** [chatty/chatty#260]
I made this for a custom Chatty command. Here it is for anyone interested. Requires cygwin, either Livestreamer or Streamlink, and the player of your choice.

https://gist.github.com/mtcjayne/3d04ca8ff50759b576daeeeec27c085b

**Comment by tduva** [comment]
I'm not sure not sure if an Issue is the right spot for this, but I'm also not sure where is.

**Comment by mtcjayne** [comment]
Yeah, there's not a forum or something like that so I wasn't sure where to share it.
