### ISSUE TITLE
Toggle to hide 'Rituals'

### ISSUE THREAD

**Issue by Cold-Phoenix** [chatty/chatty#262]
Could we have an option to hide user ritual usernotices, in large streams which havn't disabled the feature the spam is counterproductive. http://bit.ly/2IYLvbd is an example of a chat with this enabled.

**Comment by Decicus** [comment]
Add `config:info is new here` to your ignore list.

It's _sort of_ covered on the [ignore help page](https://chatty.github.io/help/help-settings.html#Ignore) (though it uses subscription messages as an example instead).
