### ISSUE TITLE
Cheer emote gifts not showing properly

### ISSUE THREAD

**Issue by UnixMonky** [chatty/chatty#264]
Twitch has a new reward emote system for cheering. When these new emotes are given, they are not usable by Chatty as it thinks I am not subbed to something to be able to use them. I've attached a snapshot of twitch chat on the web showing the emotes I can use, and what shows in Chatty. I do note that the emote that shows up in chatty will occasionally change to a different emote that I have, but it only ever shows one.
![emotes_web](https://user-images.githubusercontent.com/6799707/41384965-e02e7f0e-6f46-11e8-8f56-f87307f66d11.png)
![emote_chatty](https://user-images.githubusercontent.com/6799707/41384972-e28920f6-6f46-11e8-8b43-bcb56ff60c49.png)

For reference, the temporary emotes are described on Twitch here:
https://blog.twitch.tv/support-streamers-and-get-gifts-by-cheering-for-your-favorite-world-cup-team-c10c455cedcc

The overwatch emotes are described here, but I think they're using the same underlying framework:
https://overwatchleague.com/en-us/news/21525182/ready-set-cheer

I will note that all the emotes I have from this are the reward for other people cheering, I have not contributed bits myself.

**Comment by tduva** [comment]
Unfortunately this is an issue on Twitch's end. Twitch Chat doesn't send all special emotesets you have access to (as it does for the "normal" ones), but keeps cycling through them every time you send a message. I don't know if it's a bug, but it definitely doesn't seem intended, since it doesn't make much sense.
