### ISSUE TITLE
Feature Request: OBS Plugin Mode

### ISSUE THREAD

**Issue by ddugovic** [chatty/chatty#267]
I'd like to use Chatty as an open-source substitute for KapChat.  Namely, I'd like:

* A fixed-dimension view-only display (no input)
* No scroll bars if text overflows
* Ideally, a way to bundle/install it into OBS (like CLR Browser), although certainly I can run it standalone if necessary

**Comment by tduva** [comment]
I'm not sure how Chatty could be an OBS Plugin, but for screen capturing you can either use the [url=http://chatty.github.io/help/help.html#streamchat]Stream Chat[/url] or use the main window and enable "Settings - Window - Always show chat scrollbar". That way the size of the chat doesn't change.

**Comment by ddugovic** [comment]
Cool!  How do I make Chatty wider than my monitor, so the scroll bar doesn't consume space?
