### ISSUE TITLE
Emotes not loading sometimes

### ISSUE THREAD

**Issue by mtcjayne** [chatty/chatty#269]
I'm seeing this icon a lot instead of emotes. Any ideas what can cause it?
![image](https://user-images.githubusercontent.com/27238473/42732028-ce639c18-87de-11e8-90b3-337b43e2e3e7.png)

**Comment by tduva** [comment]
Install the [latest release](https://github.com/chatty/chatty/releases/tag/v0.9.1-emotefix) or the [latest beta](https://github.com/chatty/chatty/releases/tag/v0.9.2b4).

**Comment by mtcjayne** [comment]
I either didn't notice that or Chatty hadn't told me about that. Do these
hotfix versions get notifications?

**Comment by mtcjayne** [comment]
I either didn't notice that or Chatty hadn't told me about that. Do these hotfix versions get notifications?

**Comment by bariod** [comment]
He announces it on twitter and discord. Only full releases notify you in the application, I think.
