### ISSUE TITLE
Graphical glitches in text input field and userlist while on multiple monitors

### ISSUE THREAD

**Issue by RedSnt** [chatty/chatty#27]
So this one is fairly specific. I've read a little about it online and it seems like it might be something to do with java not handling multiple monitors very well.  

Anyway. This bug happens when you have the main chatty window on your secondary monitor (not main as set in windows) and the bug seems to randomly come and go with the only triggering event being when a toaster notification is shown. This bug happens despite disabling either directdraw or direct3d in "Other" under "Options".  
My current way of bypassing the glitch is currently having the client main window on my primary monitor and then popping out a channel and moving that to my secondary monitor.  
But that fix also implies that that the problem might have something to do with chatty toaster notifications.

I might've jumped the gun with this bug report because I've just turned off "Chatty notifications" and am going to see if that fixes my graphical problems.

PS: Didn't attach picture in original post, so here it is: http://i.imgur.com/c20QjYZ.jpg

EDIT: Nope, still happens. Noticed it happened when I tried to use the auto-completion feature which also produce a small toaster like popup.

EDIT2: Previous observation regarding bug not happening on primary monitor was wrong.

**Comment by RedSnt** [comment]
So I tried installing JRE 1.7.0_51 to see if that would solve my problem, but I just get an "exception error". Then I tried installing 1.8.0 (original release build) and Chatty runs but still get the same bug. So I just updated to newest release of Java and still the same bug. I also tried messing around with nVidia control panel stuff but alas, with no solution.  

So I haven't been able to debug anything from my side, besides noticing that main chat window rarely bugs out but anything java notification wise seem to bug out both chat input field and user list. Tab bar also doesn't bug out.

**Comment by beardsocool** [comment]
This has never happened to me ever.

**Comment by RedSnt** [comment]
This bug pretty much only happens when quickly mousing over emoticons in the emoticons window. At some point the "buffer" or whatever gets filled - it bugs out, causing the glitch you see in the picture previously posted. 

It's probably caused either by the tooltip module or the image module used to display emoticons - or the window manager perhaps. 

So this is a request from me: Ability to run chatty without tooltips (who use them anyway?). Or maybe point me in the right direction and I'll read up on how to compile Chatty myself. I love the program, but this one little thing is driving me nuts.

**Comment by RedSnt** [comment]
I finally found out what caused this bug, and it was none other than: MSI Afterburner. I feel ashamed for not properly eliminating this months ago.  

Easy to run both at same time once you add a profile for javaw.exe and disable on-screen display support in RivaTuner Statistics Server.

It makes perfect sense as well, I'm just a big dummy. Consider this "bug" resolved.

**Comment by tduva** [comment]
Thanks for reporting back. I'll add this to the Troubleshooting in case someone else has the same issue.
