### ISSUE TITLE
Umlauts in URL ends URL highlighting, breaks clickable URL

### ISSUE THREAD

**Issue by DaRuudii** [chatty/chatty#272]
If an umlaut (ä, ö, ü, ß) is in an URL, it breaks the URL and therefore breaks the clickable URL.

![image](https://user-images.githubusercontent.com/8517764/44041858-12aa8eca-9f1f-11e8-8c05-372df18cf54f.png)

tested with german umlauts: ä, ö, ü, ß
version tested on: 0.9.2b5 (hotkey_64bit)

Don't know if other special characters (maybe from other languages) are affected.

**Comment by tduva** [comment]
Technicially it's not a valid URL with that character (without being encoded accordingly), but since browsers don't really seem to care too much about that anyway maybe it should still support it.

**Comment by tduva** [comment]
This kind of link should work now in the latest beta.
