### ISSUE TITLE
Message highlighted when it shouldn't be

### ISSUE THREAD

**Issue by jakebathman** [chatty/chatty#276]
I've seen an occasional issue with this on a few of the latest (beta and stable) versions of Chatty. It's intermittent and I can't figure out how to recreate it all the time.

I have a rule to highlight my twitch username (jakebathman) as a basic highlight rule. Most of the time it matches correctly and only highlights messages with my username in them.

Occasionally, it'll _also_ highlight the next message from that user. In this case, Nightbot is the first user that had a message matching the highlight rule. But the subsequent Nightbot message was _also_ highlighted.

This isn't the first one I've noticed, and it's almost always from Nightbot (though that could be coincidence because Nightbot mentions me often)

Here's a screenshot, followed by my build info:

<img width="604" alt="drlupo w 2 9034 75432m - this is a stream fortnite - chatty 2018-09-07 09-17-50 1" src="https://user-images.githubusercontent.com/43112/45225053-31278900-b281-11e8-8350-a23be9e3f1e3.png">

**Chatty Version**: 0.9.2b5
**OS Version**: MacOS High Sierra 10.13.6 (17G65) 
**JRE Version**: 9.0.4

**Comment by Decicus** [comment]
This seems like a result of the "Highlight follow-up" feature, see screenshot:
![](https://i.decic.us/2018-09-07_U1ou1e.png)

**Comment by jakebathman** [comment]
Ugh, thanks. Didn't notice that checkbox or know about the feature.

That's what I like about Chatty: there are an _insane_ number of little cool things it can do.

Closing as expected behavior.
