### ISSUE TITLE
Auto Complete of name that are similar, breaks chatty

### ISSUE THREAD

**Issue by gamerscircle** [chatty/chatty#278]
When I do a !so [aka Shoutout] for someone using the autocomplete, it will list those that are similar, but I am until to select and chatty is unusable.  I have to quite and restart it.

**Comment by tduva** [comment]
I don't see any issues with TAB Completion at all. Can you describe the problem in more detail? What exactly are you pressing? What is happening? How does Chatty become unusuable? Since when has this been happening? Can you 100% reproduce it? What OS? What Chatty version? What Java version?

**Comment by gamerscircle** [comment]
It happens to me as often as I have similar names.. I will screen shot it.

**Comment by gamerscircle** [comment]
This is not an exact example of chat, but it is very similar with how windows / frames will over lap and not repaint. 

[https://i.imgur.com/4uLvBva.jpg](url)

**Comment by tduva** [comment]
So you're saying as soon as the TAB Completion tooltip comes up, the painting breaks. Unfortunately this kind of issue is very unclear, so I can't really help. You can only try if any of this works: https://chatty.github.io/help/help-troubleshooting.html#visual-glitches

**Comment by tduva** [comment]
That being said, if this is one of the main things that triggers it for you, you can try to disable the TAB Completion popup in the settings.
