### ISSUE TITLE
Global Moderator status not caught by $mod in usercolors

### ISSUE THREAD

**Issue by jakebathman** [chatty/chatty#281]
### Overview

When using a custom usercolor for `$mod`, this fails to color a user that's designated as a Global Moderator. There is also no documentation on usercolors if it's possible to select on global mod status (as is possible elsewhere, e.g. Highlight [meta prefixes](https://chatty.github.io/help/help-settings.html#Highlight) using `status:g`).

### Example
User: `*%+Dyna`

<img width="734" alt="screen shot 2018-09-27 at 11 53 54 am" src="https://user-images.githubusercontent.com/43112/46161793-1b87fc80-c24c-11e8-96f2-f60b530d233c.png">

### Expected behavior

Either:
* Usercolors filters should include `$globalmod` (or similar); or,
* The existing usercolors filter `$mod` should also match against global moderators (prefixed with `*`)

### Additional information
- OS: macOS Mojave 10.14 (18A389)
- Chatty Version: 0.9.2b8
- Java Version: 9.0.4
- When has the issue first occurred: Only noticed on this version (hadn't seen a global mod before)
- How often does the issue occur: every time

**Comment by Lucaber** [comment]
Hi,
`$globalmod` does actually already exists, this is just missing in the documentation.
