### ISSUE TITLE
[Feature-Request] Advanced chat moderation tool

### ISSUE THREAD

**Issue by Eyremba** [chatty/chatty#291]
Basically, it would be cool to be able to create a list of profanity/insulting words and if a word from this list is contained in a Twitch chat message, Chatty highlights the message and automatically opens this userdialog: 

https://chatty.github.io/img/userdialog.png

This would make the moderation a lot easier and Moderators would be able to block/delete undesirable content much faster than before. It should also be able to detect the words from the list if they are wr1tt3n in a diff3r3nt w@y to make it harder for the bad guys to bypass this tool.

**Comment by tduva** [comment]
I'm not sure if opening a User Dialog automatically would be a good idea, especially in very busy channels. If anything there would have to be some kind of queue that allows to cycle through detected problematic users. I doubt I'm going to have time for something like that anytime soon though.

I don't think I'd be able to create any kind of detection that also recognizes variants. Even official Twitch tools such as AutoMod have been known to struggle with detection, and they certainly have more ressources at their disposal. Although Twitch recently added some kind of bad word detection that is appended as tags to messages, so it should be possible to implement something that e.g. Highlight messages that contain profanity.
