### ISSUE TITLE
FrankerFaceZ/FFZ emotes do not load on Java 11

### ISSUE THREAD

**Issue by abelbriggs1** [chatty/chatty#293]
I haven't seen anything about this, and I know this project runs on Java 8, but I wanted to document this here so nobody else has to tear their hair out like I did.

**Describe the bug**
FrankerFaceZ emotes do not load(local or global) on Java 11 - a red X is displayed.

**To Reproduce**
Try to use a FrankerFaceZ emote on Java 11.

**Expected behavior**
The emote loads and displays normally.

**Debug Log**
`[23:55:37] Trying to load WooperZ again (https://cdn.frankerfacez.com/d0636daa05fbb163bcc80c009d70b180.png)
[23:55:37] Error saving https://cdn.frankerfacez.com/d0636daa05fbb163bcc80c009d70b180.png to /home/ultimasphere/.chatty/cache/img/imgcache-emote_FFZ__8314302b6b69f583196aafe349e73658fd001dad: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[23:55:37] Error loading image: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

SSLHandshakeException. Maybe something changed in the SSL library between J8 and J11 that causes this?

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Linux Mint 19
- Chatty Version (e.g. v0.9.1 Standalone): 0.9.3 beta 2, but I've had the same issues on 0.9.1 and 0.9.2.
- Java Version (if not using Standalone): open-jdk-11
- When has the issue first occurred (Chatty Version or timeframe): Since I started using Chatty(0.9.1)
- How often does the issue occur (everytime, sometimes): Always

**Additional context**
Things I tried before switching Java versions:

Turning off Direct3D and DirectDraw
Toggling FFZ support
Going back versions
Deleting the image cache in ~/.chatty

Thanks for making a great chat app. Very handy to use with Livestreamer.

**Comment by tduva** [comment]
I'm getting the same error on Windows 7 OpenJDK 11.0.1 with the FFZ CDN (the API seesm to work fine).

**Comment by L2501** [comment]
this should be fixed in java 11.0.2

https://bugs.openjdk.java.net/browse/JDK-8210334

**Comment by tduva** [comment]
On AdoptOpenJDK 11.0.2 the emote information can now be loaded from the API, but loading the emote images gives me a new error: `javax.net.ssl.SSLException: No PSK available. Unable to resume.`

This may be due to this bug: https://bugs.openjdk.java.net/browse/JDK-8213202

**Comment by L2501** [comment]
A workaround is to disable TLS1.3 with -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
