### ISSUE TITLE
[Request] Allow the Filter replacement to be set to nothing/blank

### ISSUE THREAD

**Issue by KaXaSA** [chatty/chatty#294]
So I was playing with the Filter `(Main > Settings > Chat > Filter)`, the words/regex that you add to the list get replaced by `..` (default) and I noticed that you can use `replacement:anythinghere`

> reg:^Stream Schedule:.*
> Filter messages starting with 'Stream Schedule', default replacement ('..').
> replacement:Schedule reg:^Stream Schedule:.*
> Same as previous, but replace with 'Schedule'.

**but what if want to replace it with nothing? like just filter out the matched regex?**

`replacement: reg:regexhere`  doesn't work
I also tried to replace it with _zero width characters_ like: `​`
but It get replaced by like.. a small `.` 😢

**Comment by tduva** [comment]
I'm not a fan of changing messages without any sort of feedback, but I guess if you explicitly choose to do it that's your problem. I'll try to see if I can do it somehow.

**Comment by tduva** [comment]
This is implemented (`replacement:none`).
