### ISSUE TITLE
[Request] Scale Animated Emotes

### ISSUE THREAD

**Issue by Osahashi** [chatty/chatty#295]
**Describe the bug**
I set the emotes to 130% upscale, but it only works for the global and normal emotes, but not the BTTV emotes in Chatty

**To Reproduce**
1. Go to Settings
2. Click on Emoticons
3. "Scale (Chat)": 130% + "Emotes Dialog": 130%

BTTV emote, on the left side, does not scale, global sub emote, on the right side, scale correctly:
At Chatty (Version 0.9.3-b2)
![at chatty](https://user-images.githubusercontent.com/22057956/49387836-b6a0c500-f71a-11e8-9686-fe2797b55fcf.JPG) 
At normal chat on website:
![at twitch chat](https://user-images.githubusercontent.com/22057956/49387884-cfa97600-f71a-11e8-8285-a5035acfd9a6.JPG)

- OS: Windows 10 Home - 1803 17134.441
- Chatty Version (e.g. v0.9.1 Standalone): Chatty_0.9.3-b2_win_standalone
- How often does the issue occur (everytime, sometimes): everytime

**Comment by tduva** [comment]
All Emotes except Animated can be scaled. What channel are these Emotes on?

**Comment by Daisenki** [comment]
Ah ok I see the problem, it is a animated emote, the lights are moving. The emotes are from the channel Miamouz 
So in this case it's not a bug or? More like a feature request for scaling the animated emotes too.

**Comment by tduva** [comment]
Animated emotes are scaled by now.
