### ISSUE TITLE
Custom Commands don't obey :emoji: codes 

### ISSUE THREAD

**Issue by UnixMonky** [chatty/chatty#306]
**Describe the bug**
Custom commands that include :emoji: shortcodes do not produce the emoji, but rather the literal text ":emoji:". This is not true for Twitch/FFZ/BTTV Emoticons, those will correctly be replaced.

**To Reproduce**
Create a custom command including an :emoji:
/music :musical_note: %1- :musical_note:
Call the custom command:
/music testtext:
Chatty adds ":musical_note: testtext :musical_note:" into chat as plaintext

**Expected behavior**
Chatty should put "🎵 testtext 🎵" into chat

**Debug Log**
I didn't see anything relevent in debug log, but I'll be glad to look again and update if there's a better search method.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/6799707/51200406-65622480-18c7-11e9-8fa1-177de6edd7e8.png)

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Ubuntu 18.04
- Chatty Version (e.g. v0.9.1 Standalone): v0.9.4
- Java Version (if not using Standalone): openjdk 10.0.2 2018-07-17
- When has the issue first occured (Chatty Version or timeframe): First noticed today 2019-01-15
- How often does the issue occur (everytime, sometimes): everytime

**Additional context**
If i take the erroneous plaintext from chat and copy/paste it into the input box then chatty will correctly replace the emoji.

**Comment by tduva** [comment]
Technicially the feature only replaces codes in text entered into the inputbox, but since Custom Commands largely act "as if you entered it into the inputbox yourself" it makes sense that they replace codes as well. This will be added in the next beta.
