### ISSUE TITLE
Suggestion for the backend of Chatty

### ISSUE THREAD

**Issue by Zero3K** [chatty/chatty#308]
Maybe you could make it be based on Ambassador (https://github.com/Ascrod/ambassador) instead of Java.

**Comment by tduva** [comment]
I don't know what that is exactly, but reprogramming everything in another language/environment would probably take years to reach feature parity, that's just not practical.

**Comment by Zero3K** [comment]
Then what about a plugin/extension for it?

**Comment by Zero3K** [comment]
It would be nice if someone were to make one for Ambassador.
