### ISSUE TITLE
Hide bots

### ISSUE THREAD

**Issue by FireCulex** [chatty/chatty#309]
Twitch doesn't allow us to remove bots from our channel. It would be nice if there was a way for Chatty not to display them when they join/leave and on the channel list. If we have to add who to hide individually thats fine.

**Comment by tduva** [comment]
You can add users to the Ignored Users (chat) list (reachable via the Ignore settings page) and enable the option to hide ignored users at the bottom of the list. You can also add users to the list when you right-click on them in chat/userlist and choose `Miscellaneous -> Ignore (chat)` from the context menu.

**Comment by FireCulex** [comment]
This is actually brilliant thanks!
