### ISSUE TITLE
Request to not remove lines if a user is inactive

### ISSUE THREAD

**Issue by tezJR** [chatty/chatty#310]
The User Dialog says "some lines cleared due to user inactivity". As a mod, being able to see more chat at a glance that a user did, even if days old, is extremely useful. Can we have an option to restore previous versions' behaviour not having lines cleared, and even an option to adjust the number of displayed lines beyond 100?

**Is your feature request related to a problem? Please describe.**
I updated Chatty, and the User Dialog says "some lines cleared due to user inactivity" where it never did before.

**Describe the solution you'd like**
Can we have an option to restore previous versions' behaviour not having lines cleared, and even an option to adjust the number of displayed lines beyond 100?

**Comment by tduva** [comment]
The option is under Settings - Moderation.
