### ISSUE TITLE
Cannot open url

### ISSUE THREAD

**Issue by dherault** [chatty/chatty#314]
Hi, when I click on a link in the chat, it offers to open it. When I then click on "Open URL", nothing happens.

Windows 10 / Chrome as default browser.

Cool app, using it to stream :)

**Comment by BurnsCommaLucas** [comment]
Are there any sites whose links make it through, or does every site do nothing when clicked? I've had this issue before but it was related to firewall/proxy settings on the network I was connecting to.

**Comment by dherault** [comment]
Every site do nothing
