### ISSUE TITLE
Space after tab completion

### ISSUE THREAD

**Issue by azizLIGHT** [chatty/chatty#316]
**Is your feature request related to a problem? Please describe.**
Whenever I tab complete, I get annoyed when it doesn't automatically add a space after the completed emote as I expect from other chatting programs like discord or chatterino or even IRC tab nick completion. This seems like standard behavior in other programs and Chatty is the odd one out in its behavior. I end up typing the next word attached to the tab completed emote/nick and its embarrassing when I send it to the channel without thinking

**Describe the solution you'd like**
Option to add a space character after tab completion, in the settings. Selecting it will automatically add a space character after any tab completed nick or emote

**Describe alternatives you've considered**
- Typing space myself, again and again and again....
- Getting used to unusual tab completion on Chatty

**Additional context**

**Comment by tduva** [comment]
I'm used to not having a space added from IRC, but I guess everyone's perferences are different. I would get annoyed by having to delete a space all the time when I want to type something like `<name>:` or enter Emoji without a space in between them. It's reasonable to add it as an option though.

**Comment by azizLIGHT** [comment]
Sure, it's a preference and quality of life improvement. Make it as an option that one must specifically select, so that out of the box options follow what you want (no space after tab) and those who care can find the option to change the behavior. Thanks for considering

**Comment by tduva** [comment]
Added a setting for this in v0.9.7-b1.
