### ISSUE TITLE
Login data was determined invaild

### ISSUE THREAD

**Issue by kussii** [chatty/chatty#32]
Hi, every time i close/start chatty i keep getting
https://i.gyazo.com/920da41ebede7f4fa2813077ed573b4c.png
https://i.gyazo.com/4ae130b249062c75c82e4605fb49a83f.png
and every time i i have to login. Anyone got any idea why?

**Comment by tduva** [comment]
I'm not sure why that would happen, unless during times where Twitch was derping. But it shouldn't happen regularly.

**Comment by adamteece** [comment]
I've been having this happen myself from time to time. Basically the window pops up, I click verify, and it lets me back in. Not sure if any kind of auto reconnect would be possible?

**Comment by craftwar** [comment]
I change client-id for my modified chatty.
I have this bug now sad :(

I think this log may be related to this bug.

[2017-09-25 00:38:33 INFO] GET (v5): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization) [chatty.util.api.TwitchApiRequest/getUrl]
[2017-09-25 00:38:34 INFO] GOT (401, -1): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization) [java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0] [chatty.util.api.Requests$1/requestResult]
[2017-09-25 00:38:34 WARNING] Access denied when getting followed streams. [chatty.util.api.StreamInfoManager/requestResultFollows]
[2017-09-25 00:38:34 INFO] Checking token.. [chatty.util.api.TwitchApi/checkToken]
[2017-09-25 00:38:34 INFO] GET (v5): https://api.twitch.tv/kraken/ (using authorization) [chatty.util.api.TwitchApiRequest/getUrl]
[2017-09-25 00:38:34 INFO] GOT (200, 46, gzip): https://api.twitch.tv/kraken/ (using authorization) [chatty.util.api.Requests$1/requestResult]
[2017-09-25 00:38:34 INFO] No webserver running, can't stop it [chatty.TwitchClient/stopWebserver]

**Comment by tduva** [comment]
I don't know why Twitch doesn't accept tokens sometimes. Try requesting new login data.

**Comment by craftwar** [comment]
It happens every few hours (less than 5). Maybe you can try remove chatty token and twich connection to find out what's wrong. Or debug with my client id.

**Comment by tduva** [comment]
I'm not sure what you mean by "remove chatty token and twitch connection".

**Comment by craftwar** [comment]
Make a clean start about any authentication related.
I think it may be twitch change some mechanisms but old app is still on old mechanism.
I don't have this problem when I use original chatty. (connection to twitch more than 1 year)
My client id is one less character to yours. This may make twitch use different mechanism.
I don't read twitch docs, all are my guesses.

**Comment by tduva** [comment]
I registered a new App on https://dev.twitch.tv for testing, let's see if I have the same issue with tokens generated from that. Did you do the same? What did you select as Application Category? That field didn't use to be there, although I don't know what consequences that selection has.

**Comment by craftwar** [comment]
I created 3 days ago. I tested application integration and chat bot. I think it's for statistical, don't see any doc about that option.

**Comment by craftwar** [comment]
@tduva do you get any club?

**Comment by tduva** [comment]
Yes, seems like tokens are supposed to expire now. You can see the expire time in seconds if you enter your token here: https://api.twitch.tv/kraken/?api_version=5&oauth_token=<token>

I don't know how Twitch expects tokens being refresh in a clientside app though.

**Comment by craftwar** [comment]
Twitch dev doc says refresh token before any request.

**Comment by tduva** [comment]
I'm using the Implicit Code flow, which doesn't provide a refresh token. And I can't use the Authorization Code flow because it requires a client secret which I can't store securely clientside.

**Comment by craftwar** [comment]
Just send a request to https://api.twitch.tv/kraken before any request? Not sure what Twitch mean.

https://dev.twitch.tv/docs/authentication
If You Use Twitch for Login to Your App, You Must Validate Every Request
When validating each of your requests, submit a request to the root URL. If you are authenticated, the response includes the status of your token. The response includes a token object, and if the valid field in that object is true, your access token is valid.

https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api#root-url

**Comment by tduva** [comment]
I think they are referring to websites that use Twitch OAuth to identify users, so on every page request it should be checked that he user's token is still valid. It doesn't have to do with the issue in this thread.

**Comment by craftwar** [comment]
I can't find what "client secret" can do. In the worst case, let every user register their app. Fill in their own client-id and client secret. Twitch docs always are bad, hard to understand.

If you use Chatty for chating only, you can generate token from http://www.twitchapps.com/tmi.
It's permanent but lacks all features except chat.

You forget put forum thread here.
https://discuss.dev.twitch.tv/t/oauth-implicit-code-flow-user-access-tokens-expiration/11662

**Comment by tduva** [comment]
Telling every single user to register there own app on Twitch isn't practical, and I doubt it would be wanted by Twitch.

The http://www.twitchapps.com/tmi token may be permanent now (as are Chatty's, it uses the same exact method and is an "old" app as well), my concern is what happens when Twitch changes is so that the tokens of old apps start to expire as well.
