### ISSUE TITLE
Help setting up an OAuth Redirect URL for TardsPlaya

### ISSUE THREAD

**Issue by Zero3K** [chatty/chatty#321]
I have a guy working on fixing the issues it has with loading Twitch Streams and need help setting up the mentioned URL so it'll be able to get the list of HLS urls and use the selected quality for streaming to a media player.

**Comment by tduva** [comment]
I'm not sure what this has to do with Chatty?

**Comment by Zero3K** [comment]
I just thought that you could help. The guy stopped responding so now I have to find someone else to work on it.
