### ISSUE TITLE
Filter Emote Only Messages

### ISSUE THREAD

**Issue by dungi** [chatty/chatty#326]
Hello,

I like to filter Emote Only Messages (if there are 3 or more of them) > mostly hype or raid messages, that pushes away the old messages (or only show the first message) and hide the duplicates (cause VIPs and MODs can write the same message again)

Thanks

**Comment by tduva** [comment]
Should be be able to ignore messages that Twitch considers emote only (so this will only work for Twitch emotes, not FFZ or BTTV), at least as long as they attach the tag to the message (it's not an "official" tag afaik).

Add `config:t|emote-only=1` to the Ignore list. You can add other prefixes such as `chan:` to e.g. restrict it to certain channels. See the help for more information.

I'm also considering some sort of repeated message detection, but nothing concrete yet (https://github.com/chatty/chatty/issues/361#issuecomment-623375684).

**Comment by dungi** [comment]
In my first test it seems to work if I only type Twitch Emotes in Chat. Sad that It doesn't work for BTTV or FFZ, but it will keep my chatlog cleaner for now :) Thank you
