### ISSUE TITLE
[Feature Request] Manual selection of audio output device

### ISSUE THREAD

**Issue by Kmartinator** [chatty/chatty#331]
**Is your feature request related to a problem? Please describe.**
I am unable to reliably separate out notification sounds to a specific audio output device, so during streams, the notification sound is broadcast out to the stream, when I would prefer to make it so only I can hear it.

**Describe the solution you'd like**
Having the option to select which audio device the program uses as the output.

**Describe alternatives you've considered**
I thought this could be simulated by starting the program in one audio device for the whole computer, then switching the device after the program is open. I thought maybe it would be a java thing since Minecraft does that sometimes (spoilers: nope, Minecraft is just weird).

I have been trying to research ways to isolate that audio, but apparently Windows doesn't make it easy. I'm continuing to dig, but I thought I would drop this in here in case it was doable!

**Additional context**
I have been using Chatty since I started streaming 2 years ago. It has been the most important piece, for me, in being able to present the stream the way I want to, because of the ability to add notification sounds to chat messages. I rely very heavily on this for my chat engagement, but have just been thinking recently that some folks might be put off by it. Thanks for your hard work on it, even if this feature idea doesn't pan out :)

**Comment by tduva** [comment]
You can select the Output Device in the Sound Settings (on the Notifications Settings page). If that doesn't work, then I'm not sure.

**Comment by Kmartinator** [comment]
Wow, and I though I turned the settings upside down. Sorry for the time wasting, thanks for the help!
