### ISSUE TITLE
Exception on the first :P smiley

### ISSUE THREAD

**Issue by sfahrenholz** [chatty/chatty#333]
**Describe the bug**
I dont know how to descripe.. when i typing :P in a channel, i get this exception

**To Reproduce**
[Steps to reproduce the behavior:
1. Start Chatty
2. In a channel type something (see below)

**Expected behavior**
No Exception

**Additional information (please complete the following information):**
- OS (e.g. Windows 7):  Win 10
- Chatty Version (e.g. v0.9.1 Standalone):  0.9.7 Standalone

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)

**Additional context**
[Add any other context about the problem here.]
[16:37:31] @{USER}: Na du verschollender
[16:37:39] @{USER}: Was ist das denn hier?
[16:37:44] @{USER}: Vorgearbeitet?
[16:38:12] @{USER}: Sagen sie alle
[16:38:15] @{USER}: Jaja
[16:38:18] @{USER}: :P

Error Report // 2019-07-24 16:38:18 +0200 / Chatty Version 0.9.7-b5 Hotkey / Java: 10.0.1 (Oracle Corporation / C:\Program Files\Java\jre-10.0.1) OS: Windows 10 (10.0/amd64) / [Memory] total: 1.059.840 / 2.082.816 free: 820.520 [Uptime] 3m 36s

```
16:36:55 GOT (200, 3150, gzip): https://api.twitch.tv/kraken/streams?offset=0&limit=100&channel=69257053,81077929,43190043,118423531,54844912,50398110,38179826,50648478,76301488,135000771,60573786,115897932,36811285,12875057,38775728
16:38:11 GET (v5): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization)
16:38:12 GOT (200, 3151, gzip): https://api.twitch.tv/kraken/streams/followed?limit=100&offset=0 (using authorization)
16:38:12 Got 2 (limit: 100) followed streams.
16:38:18 Unhandled Exception:
null


```

**Comment by tduva** [comment]
This should be fixed by now.
