### ISSUE TITLE
Not displayed your own FFZ Supporter badge

### ISSUE THREAD

**Issue by estintax** [chatty/chatty#335]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may fix your issue. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*

**Describe the bug**
In the chat does not display your own badge of FFZ Supporter

**To Reproduce**
1. Donate to FrankerFaceZ to get FFZ Supporter badge;
2. Open any chat channel;
3. Send any message to the chat;
4. Look at your badges in front of nick;
5. See error.

**Expected behavior**
Before nickname should be FFZ Supporter badge

**Debug Log**
https://pastebin.com/j1ksETgM

**Screenshots/Videos**
![In Chatty](https://i.imgur.com/LtWUr7m.png)
![Twitch Chat with FFZ Addin](https://i.imgur.com/Dbz6RzM.png)

**Additional information (please complete the following information):**
- OS: Windows 10 Home Version 1809
- Chatty Version (e.g. v0.9.1 Standalone): Chatty Version 0.9.7 Hotkey
- Java Version (if not using Standalone): 1.8.0_201
- When has the issue first occured (Chatty Version or timeframe): 0.9.7
- How often does the issue occur (everytime, sometimes): everytime

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)

**Additional context**
The rest of the users who donated to FFZ have this badge

**Comment by estintax** [comment]
Fixed itself

**Comment by 2up3r** [comment]
how u fixed it? i got the same problem ...see others ffz badge in chatty but not my own, in browser i see my own too
