### ISSUE TITLE
Support new "Channel Points" emotes

### ISSUE THREAD

**Issue by bap14** [chatty/chatty#338]
**Is your feature request related to a problem? Please describe.**
Twitch has just released, in a preview or alpha, a "Channel Points" system. Sitting in a stream will accrue points which can be used to perform / unlock things in the channel. One of these abilities is to "edit" an emote in one of three ways and use it for 24 hours.

There are only three modifications that can be made at this time (described in the next section). These are implemented using a suffix syntax.

**Describe the solution you'd like**
Add support for the emote suffixes:

 - **_BW** - Renders a black-and-white version of the emote
 - **_SG** - Renders the emote with sunglasses
 - **_HF** - Renders the emote horizontally flipped

**Describe alternatives you've considered**
This is a new Twitch feature, there isn't an alternative.

**Additional context**
An example of a channel with this feature is Fr1sky86

Twitch info on channel points: https://help.twitch.tv/s/article/channel-points-guide?language=en_US

**Comment by tduva** [comment]
The emotes are shown in received messages now, however showing them in the Emotes Dialog or sent messages is not possible at the moment due to lack of API data for them.
