### ISSUE TITLE
Support for new Channel Points highlighted messages

### ISSUE THREAD

**Issue by swemoney** [chatty/chatty#339]
**Is your feature request related to a problem? Please describe.**
The new Channel Points feature on Twitch allows users to "highlight" a chat message which makes it kind of look like a resub message in the normal Twitch chat.

![highlight](https://user-images.githubusercontent.com/4160/64471186-b7d0a980-d113-11e9-9500-56e5aa99305f.png)

**Describe the solution you'd like**
Some way of highlighting those messages in Chatty. A [Notification] message that a user highlighted a message followed by the message would probably work great. Checking my twitch bot, the highlighted messages have one extra tag with a key of `msg-id` and a value of `highlighted-message`.

**Describe alternatives you've considered**
This is a new feature on Twitch so no alternatives.

**Additional context**
[Channel Points Guide on Twitch](https://help.twitch.tv/s/article/channel-points-guide)

**Comment by tduva** [comment]
These are now marked in Chatty. Not all the information that is shown in the screenshot is available through the API at this point though, so it shows up differently.
