### ISSUE TITLE
Add support for new twitch /emoteonly and /emoteonlyoff commands

### ISSUE THREAD

**Issue by skovacs1** [chatty/chatty#34]
Twitch has recently added emote-only mode (and, of course, the ability to disable it). Chatty does not support the commands in the / form and can only be entered using . notation. See http://help.twitch.tv/customer/portal/articles/659095-chat-moderation-commands between /subscribersoff and /clear.

Created a bare-bones PR to add support for the / commands themselves.
https://github.com/chatty/chatty/pull/33

Could maybe consider adding emote-only to the title bar (ChannelState) for clarity.

**Comment by tduva** [comment]
Added (978d516ebe3db3cb0b2522aa69ea293fe3bc63e7).
