### ISSUE TITLE
Random Incorrect Highlight

### ISSUE THREAD

**Issue by lucas861223** [chatty/chatty#341]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may fix your issue. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*

**Describe the bug**
Random messages in certain channels get highlighted and send notifications despite not matching any entry in the highlight list (confirmed using the test function).

**To Reproduce**
It only happens in 1 out of all the channels I open, and the messages don't seem to follow any pattern. 
It consistently happens in, in my case, raeyei's channel.

**Expected behavior**
The messages to not be highlighted.

**Debug Log**
None

**Screenshots/Videos**
[highlight list](https://i.imgur.com/du8ibbh.png)
[unwanted highlighted message (the emote is raerLurk)](https://i.imgur.com/pcdlefv.png)

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Windows 10
- Chatty Version (e.g. v0.9.1 Standalone): 0.10-b3
- Java Version (if not using Standalone): 1.8.0_181
- When has the issue first occured (Chatty Version or timeframe): 0.10-b3, after updating
- How often does the issue occur (everytime, sometimes): consistent in raeyei's channel, but only happens to some messages

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)

**Additional context**
I'll post more incorrectly matched messages as they happen

**Comment by lucas861223** [comment]
[here is another, emote is KEKW](https://i.imgur.com/awFSpuM.png)

**Comment by Decicus** [comment]
Looks like it's related to the ["Highlight my message"](https://i.imgur.com/hjQZdHb.png) reward from the new [Channel Points feature](https://help.twitch.tv/s/article/channel-points-guide?language=en_US)

Uncheck this box:

![](https://i.imgur.com/DHDQGmz.png)

**Comment by tduva** [comment]
I have seen some people (understandably) confused about this, so I'm considering just using the Highlight Colors rather than making it an actual Highlight.

**Comment by lucas861223** [comment]
Ah I see, thanks for the help!
