### ISSUE TITLE
Channel Point Highlight Suppression

### ISSUE THREAD

**Issue by TheBloodyScreen** [chatty/chatty#345]
**Is your feature request related to a problem? Please describe.**
With the new Channel Point system, users can apparently choose to get their message highlighted.
This is surprisingly distracting and unless I'm very blind there doesn't seem to be a way to suppress this. 

**Describe the solution you'd like**
A simple checkbox to "Suppress Channel Point Highlights" would do perfectly.

**Describe alternatives you've considered**
Adding a way to add "twitch native" highlights to the  blacklist.

**Additional context**
![example](https://puu.sh/EucID/1636a34292.png)

**Comment by tduva** [comment]
You can disable it being colored under "Settings - Highlight - Color messages highlighted by channel points". You can disable the badge by adding a Custom Badge under "Settings - Badges" with the type "Highlighted (by points)" and no image.

**Comment by TheBloodyScreen** [comment]
Thank you very much!

**Comment by jakebathman** [comment]
If anyone finds this wanting to disable highlights for all channels, except re-enable them for their own channel:

**Step 1**: Un-check the box in Settings > Highlights
<details>
<summary>Click for screenshot</summary>
<img width="741" alt="Screen Shot 2020-01-02 at 8 41 47 AM" src="https://user-images.githubusercontent.com/43112/71672555-f4b45200-2d3b-11ea-9cf0-cb12bc074371.png">

</details>

**Step 2**: Add a new highlight entry on that same settings screen, and enter this (substituting your own channel name, of course): `chan:jakebathman config:hl`
<details>
<summary>Click for screenshot</summary>
<img width="530" alt="Screen Shot 2020-01-02 at 8 39 36 AM" src="https://user-images.githubusercontent.com/43112/71672635-380ec080-2d3c-11ea-81c6-fe4a51a80597.png">

</details>
