### ISSUE TITLE
User logs on long period and all current users (without them writing in chat)

### ISSUE THREAD

**Issue by Hoopou** [chatty/chatty#348]
Adding support of 3rd party logger and users viewer :

Exemple of request for getting user logs (**on clannel** timthetatman - **user**: wipz - **for**: October 2019):
https://overrustlelogs.net/timthetatman%20chatlog/October%202019/userlogs/wipz.txt

Getting all current users in chat (on channel timthetatman):
https://tmi.twitch.tv/group/user/timthetatman/chatters

**Comment by tduva** [comment]
All third-party logging sites are unfortunately shutting down. Also Twitch has been recently removing a lot of unofficial API endpoints, so I'm not very keen on putting work into using any more of those.
