### ISSUE TITLE
[BUG] Chatty dont shows all Emotes

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#349]
**Describe the bug**
I have noticed that a streamer that I watch does not show certain emotes at Chatty although they should.
PS: Sorry that I don't give so much info, don't know what I can/should give for stuff

**Screenshots/Videos**
(This should be not a ad for the streamer) https://streamable.com/5c5p4

**Additional information (please complete the following information):**
- OS Windows: 10
- Chatty Version: 0.11-b1
- Java Version: 1.8.0_201
- When has the issue first occured (Chatty Version or timeframe): I dont know
- How often does the issue occur: everytime

**Comment by tduva** [comment]
Those emotes work fine for me. Can you try to enter `/clearemotecache TWITCH` (this could take a bit) and then restart Chatty and try again.

**Comment by barbiehunter** [comment]
Through the command can i see all emotes again, Thx.
