### ISSUE TITLE
[Request] BTTV holiday emotes not overlapping as intended

### ISSUE THREAD

**Issue by KaXaSA** [chatty/chatty#354]
So every year BTTV add temporary holiday emotes like: 
IceCold SoSnowy CandyCane ReinDeer SantaHat TopHat = ![emotes-overlap](https://user-images.githubusercontent.com/6237603/70365151-c479b080-186e-11ea-8271-fdd1c3bb8fdb.png)

These emotes appear over other emotes, example:
D: IceCold SoSnowy becomes -> ![emote-overlap](https://user-images.githubusercontent.com/6237603/70364890-6f896a80-186d-11ea-9db7-a5b8ed48b51d.png)

Sadly, this doesn't work in Chatty, the emotes just appear side by side.

As far as I can tell they add a negative margin to make the magic happen. 
I don't know if there is more to it, but this is the css code:
```
/* Prevent stacking of IceCube, SoSnowy */
.bttv-emo-5849c9a4f52be01a7ee5f79d + .bttv-emo-5849c9a4f52be01a7ee5f79d,
.bttv-emo-567b5b520e984428652809b6 + .bttv-emo-567b5b520e984428652809b6 {
  display: none;
}

/* Ice Cube */
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-5849c9a4f52be01a7ee5f79d img,
div.bttv-emote + .bttv-emo-5849c9a4f52be01a7ee5f79d img {
  margin-left: -33px;
}

/* SoSnowy */
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-567b5b520e984428652809b6 img,
div.bttv-emote + .bttv-emo-567b5b520e984428652809b6 img {
  margin-left: -32px;
}

/* SantaHat */
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-58487cc6f52be01a7ee5f205 img,
div.bttv-emote + .bttv-emo-58487cc6f52be01a7ee5f205 img {
  margin-left: -34px;
  margin-top: -18px;
}

/* TopHat, CandyCane, ReinDeer */
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-5849c9c8f52be01a7ee5f79e img,
div.bttv-emote + .bttv-emo-5849c9c8f52be01a7ee5f79e img,
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-567b5c080e984428652809ba img,
div.bttv-emote + .bttv-emo-567b5c080e984428652809ba img,
div[data-test-selector="emote-button"] + span[data-a-target="chat-message-text"] span .bttv-emo-567b5dc00e984428652809bd img,
div.bttv-emote + .bttv-emo-567b5dc00e984428652809bd img {
  margin-left: -31px;
  margin-top: -18px;
}
```
I would love to see this working in Chatty, Thanks!

**Comment by tduva** [comment]
Since Chatty isn't browser/CSS based, this isn't that easy. Thanks for the code though. I've been working on a way that should work for all of the emotes except animated emotes, since it involves actually creating a new image, which means it's more complicated when it involves animated emotes (not impossible of course, but not really easy enough to quickly implement).

It won't necessarily look exactly the same, but it should work for most of them.
