### ISSUE TITLE
Automod stops showing up when running Chatty for a long period of time

### ISSUE THREAD

**Issue by NurikSakura** [chatty/chatty#355]
Greetings!

I am running the latest version of Chatty (Version: 0.10), and it is constantly (24/7) open and connected to several channels, including my own. While streaming, I have both Chatty and Twitch Dashboard open, and I noticed a strange thing - after a couple of days of running, Chatty stops showing automodded messages neither in chat, nor in "Automod" popup window, while they still show up in normal Twitch chat. If I restart Chatty, automod starts displaying once again, but a day or two later the issue repeats itself. As I do not get automod messages each stream and I don't stream every day, it's hard to specify the exact time window, yet it is not an immediately repeating issue.

- OS: Windows 7 (6.1/amd64)
- Chatty Version: 0.10 Hotkey
- Java version "1.8.0_231"
- Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
- Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
- Memory: total: 421 888 / 3 715 584 free: 318 811

**Comment by tduva** [comment]
AutoMod messages rely on receiving moderator actions from Twitch's PubSub service (Websocket). It's a known issue that the Websocket connections with the library Chatty is using can sometimes hang after connection issues that required a reconnect (the same happens with the connection to the FFZ websocket system). I am not aware of any way to fix this, except switch to a different websocket library and see if that fixes it, which I'm in the process of doing.

**Comment by tduva** [comment]
This may be fixed since the latest betas because I switched to a different Websocket library.

**Comment by tduva** [comment]
I'm closing this for now. Let me know if you're still experiencing issues in the latest version.
