### ISSUE TITLE
A Chatty OBS Studio plugin

### ISSUE THREAD

**Issue by Lewdicolo** [chatty/chatty#362]
![32y7A0w 1](https://user-images.githubusercontent.com/19986227/72763206-7e1aaf80-3b97-11ea-9687-494fff06544c.png) <- Rough Example

Would be great to see a Chatty plugin for OBS Studio similar to the StreamElements OBS.Live plugin. I'd love to have Chatty as a dockable window in OBS Studio for me to read chat on while I stream. (Not talking about an overlay that's visible on stream)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A plugin developed for OBS Studio that makes Chatty a dockable window alongside the stream preview.

**Describe alternatives you've considered**
hovering chatty over OBS or having it alongside OBS on the same screen

**Additional context**
I use StreamElements OBS.Live plugin and NordVPN. Unfortunately, with NordVPN, the Twitch popout chats (which is what StreamElements OBS.Live uses) constantly disconnect and reconnect. Chatty, however, doesn't have that issue. I also like Chatty's interface a lot more than Twitch's popout chat interface.

**Comment by tduva** [comment]
I'm not sure how an OBS Plugin would work. I think stuff like the Activity Feed or Stream Information on your screenshot are probably just websites that run a browser plugin, but that wouldn't work for Chatty.

**Comment by meldommer** [comment]
This is definitely doable.  I worked on a software application in the past that took a google earth window and reparented it into our application, granted it was not a cross platform solution.  I also came here looking to see if there was a way to dock other application windows into OBS, specifically Chatty same as this user.  Seems like that is not possible and only urls can be done.
