### ISSUE TITLE
Replays not showing as live for all followed streams.

### ISSUE THREAD

**Issue by astro013** [chatty/chatty#364]
**Describe the bug**
In both the latest version 0.11 and version 0.9.7 replays are no longer showing as live in the followed live channels list. Status shows as user offline if you join a live channel that is replaying a VOD. Previous behaviour showed channels as Live [VOD]. Perhaps twitch changed something in the API.

**To Reproduce**
1. Launch Chatty, login, connect etc.
2. Click on Channels - Live channels
3. Scroll down to view live channels
4. VOD replays do not show

**Expected behavior**
Streams that are playing replays showing as Live [VOD] in the live channels list as was the previous behaviour and showing up in history timeline.

**Additional information:**
- OS: Windows 7 
- Chatty Version: 0.9.7 Standalone & 0.11 Standalone 
- When has the issue first occurred: 26 Jan 2020
- How often does the issue occur: every time

**Comment by tduva** [comment]
Live VODs should show in the latest beta.
