### ISSUE TITLE
[BUG]  Point system

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#366]
**Describe the bug**
The channel point system is not yet displayed correctly in Chatty with all displays. On the following pictures (from a german stream, hope is no problem) are not all things shown in Chatty.
**To Reproduce**

**Screenshots/Videos**
Picture from the stream 
![image](https://user-images.githubusercontent.com/38357837/73770368-9b956f00-477c-11ea-8b8f-41783e7a83ce.png)
Picture from chatty 
![image](https://user-images.githubusercontent.com/38357837/73770386-a223e680-477c-11ea-99ee-d156d36b2130.png)

**Additional information (please complete the following information):**
- OS Windows: 10
- Chatty Version: 0.12-b1
- Java Version: 1.8.0_201
- When has the issue first occured: idk
- How often does the issue occur: sometimes

**Additional context**
I think you are still working on it, so i just give this as little information

**Comment by barbiehunter** [comment]
PS: just as question, how can i display even all "Point" things on the Dialog, i see by a streamer he can see the stuff from the point system from one dude but i dont. (i cant find anything by the settings)

**Comment by tduva** [comment]
The Twitch API does not support viewers seeing the same information as the streamer, so this is not possible.
