### ISSUE TITLE
Has emotesets been removed?

### ISSUE THREAD

**Issue by qome** [chatty/chatty#367]
**Describe the bug**
`emoteset` is no longer a valid refresh option but is still in the documentation

**To Reproduce**
[Steps to reproduce the behavior:
1. `/refresh emotesets`
2. `[12:54:29] Usage: /refresh <type> (invalid type, see help)`

**Expected behavior**
The documentation should be updated or there's a problem with the option.

**Debug Log**
None at this time since I'm assuming it's a documentation issue

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Windows 10
- Chatty Version (e.g. v0.9.1 Standalone): 0.11 Hotkey
- Java Version (if not using Standalone): 
- When has the issue first occured (Chatty Version or timeframe): Unknown, I don't use the command often
- How often does the issue occur (everytime, sometimes): Every time

**Comment by tduva** [comment]
The help will be updated, thanks.
