### ISSUE TITLE
[BUG] No twitch emotes available, only BTTV and FZFZ

### ISSUE THREAD

**Issue by LoveIsGrief** [chatty/chatty#369]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may fix your issue. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*

**Describe the bug**

When opening the emote window there are no Twitch emotes visible. Also typing the name of one e.g `DansGame` and hitting Tab, does nothing. That only works for BTTV and FZFZ emotes.

**To Reproduce**

1. Open Emotes window (Ctrl+E)
2. Open "Twitch" tab

**Expected behavior**

All twitch icons visible.

**Debug Log**

[chatty.txt](https://github.com/chatty/chatty/files/4541071/chatty.txt)

**Screenshots/Videos**

![screenshot](https://user-images.githubusercontent.com/2829538/80399600-c5f95300-88b9-11ea-8f14-73946c6b4da7.png)

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Ubuntu 18.04
- Chatty Version (e.g. v0.9.1 Standalone): Chatty (Version: 0.12-b2)
- Java Version (if not using Standalone): 
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```
- When has the issue first occured (Chatty Version or timeframe): Probably around 24 April 2020
- How often does the issue occur (everytime, sometimes): Every time

`/appinfo` 

 - 
Chatty Version 0.12-b2 [Memory] total: 310.272 / 4.087.808 free: 192.148 [Uptime] 11m 29s [System] Java: 11.0.6 (Ubuntu / /usr/lib/jvm/java-11-openjdk-amd64) OS: Linux (4.15.0-97-generic/amd64) Locale: nl_NL [Connection] Connected to: irc.chat.twitch.tv/35.163.83.163:6697 (11m 10s, 38 channels)

**Additional context**

Tried running the beta and stable with the same result.

Tried `/clearemotecache TWITCH` from #349 to no avail.

**Comment by tduva** [comment]
The Twitch emote API is quite broken. Make sure you have the "Your Subscriptions" access under "Main - Login.." so it can use the API endpoint that is less broken.

**Comment by LoveIsGrief** [comment]
That did it. Weird though, since it work on another computer.

Thanks nonetheless!
