### ISSUE TITLE
[BUG]  Pinged in chat

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#378]
**Describe the bug**
When i get pinged it get red marked and the next message after that too from a Person

**To Reproduce**
[Steps to reproduce the behavior:
Idk how to respond it, get marked by a person and the person send instanlty message after that

**Expected behavior**
idk

**Screenshots/Videos**
[If applicable, add screenshots or videos to help explain your problem.]
![image](https://user-images.githubusercontent.com/38357837/84398499-512b6f80-ac00-11ea-9e2f-b14adceb4c98.png)

**Additional information (please complete the following information):**
- OS Windows 10
- Chatty Version 0.12
- Java Version 1.8.0_201
- When has the issue first occured idk
- How often does the issue occur Everytime when i get pinged/marked

**Comment by tduva** [comment]
Do you have "Highlight follow-up" in the "Highlight" settings enabled?

**Comment by barbiehunter** [comment]
Yeah i had, sorry for the Late answer forget to answer it.  Problem is fixed for me.
