### ISSUE TITLE
[IDEA] Display Month of a sub

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#379]
**Describe the solution you'd like**
If you hover over the sub badge, it would be good if the number of months is displayed. idk what i would say more about the feature tbh.

**Example**
Example from the Twitch Chat:

User from the Twitch Chat (4 Month sub):
![image](https://user-images.githubusercontent.com/38357837/86907362-2fe17480-c115-11ea-9b6a-078ddfad89eb.png)

User in the Chatty Chat:
![image](https://user-images.githubusercontent.com/38357837/86907395-3ec82700-c115-11ea-8b6e-b891a40a31d5.png)

**Comment by mheob** [comment]
Was added in [Version 0.13.1](https://github.com/chatty/chatty/releases/tag/v0.13.1)
