### ISSUE TITLE
Dark theme for "System" Look&Feel, when Windows 10 theme is Dark?

### ISSUE THREAD

**Issue by m4gnify** [chatty/chatty#381]
**Is your feature request related to a problem? Please describe.**
"Dark" is chosen as my Windows 10 "theme" color, but the Chatty "System" theme is still white/light colored.

**Describe the solution you'd like**
Chatty follows System Dark/Light color scheme

**Describe alternatives you've considered**
The dark Look & Feel themes work just fine, but I'd like the system theme for some other personal pc problem related stuff.

**Additional context**
Dark theme selected in Windows 10
![firefox_1QuHvHvDeE](https://user-images.githubusercontent.com/8404962/88585281-30559700-d053-11ea-8a61-9ada6e77872b.png)

What Chatty looks like when selected and not selected
![Chatty_NCxY12OZAG](https://user-images.githubusercontent.com/8404962/88585354-49f6de80-d053-11ea-92bb-9cea39bede5a.png)
![Chatty_EN8tJvf87l](https://user-images.githubusercontent.com/8404962/88585348-495e4800-d053-11ea-91fe-509991370968.png)

Thanks anyhow, Chatty is pretty great.

**Comment by tduva** [comment]
The Look&Feel is provided by Java, so I'm not sure what I could do about that.

**Comment by m4gnify** [comment]
It's ok! Thanks anyway mate
