### ISSUE TITLE
reverse emote darkmode or add option

### ISSUE THREAD

**Issue by arrowgent** [chatty/chatty#384]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may include your feature. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*
using 0.13b1

**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]

version 0.12: Improved dark theme Look and Feel detection and Emotes Dialog background

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

allow choosing the background color.  it used to be black, now it is grey alternating black.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

tried changing chat window background options to see if it had any effect

**Additional context**

previous version 0.11 was black and did not have this issue

https://i.imgur.com/76vKrod.png

**Comment by arrowgent** [comment]
seems like this was fixed,  not sure what fixed it.

**Comment by tduva** [comment]
I changed the Emote Dialog colors to be based on the chat foreground/background colors in v0.13.
