### ISSUE TITLE
AuthMeReloaded compatability issue on quit message

### ISSUE THREAD

**Issue by NyanGuyMF** [chatty/chatty#388]
**Describe the bug**
The plugin sends an exit message when an unauthorized player leaves the server, but does not send a message about joining the server. 

**To Reproduce**
1. Have both `chatty.misc.joinmessage` and `chatty.misc.quitmessage` permissions
2. Join server
3. Do not log in to AuthMe (do not enter password or register)
4. Leave the server
5. Get quit message

**Expected behavior**
I expect that the plugin will not send exit messages of unauthorized players.
Or be able to choose between two options: either send log-in and log-out messages, or not send them at all

**Debug Log**
There is nothing helpful there. Only chat messages that are not related to the issue.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/43143315/97226236-89210100-17f5-11eb-8541-1a1100a1f608.png)

**Additional information (please complete the following information):**
- OS: Linux void 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
Debian GNU/Linux 9.12 (stretch)
- Chatty Version (e.g. v0.9.1 Standalone): v2.18.1
- Java Version (if not using Standalone): java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
- When has the issue first occured (Chatty Version or timeframe): checked only last v2.18.1 version
- How often does the issue occur (everytime, sometimes): everytime player quit server

**Comment by tduva** [comment]
This is the repository of a Twitch Chat Client, it looks like you're talking about a Minecraft plugin.
