### ISSUE TITLE
April fools or a bug? :)

### ISSUE THREAD

**Issue by Sundheden** [chatty/chatty#39]
Raw message says: :twitchnotify!twitchnotify@twitchnotify.tmi.twitch.tv PRIVMSG #datmodz :Sundheden subscribed for 11 months in a row!

Twitch says: http://puu.sh/o26LF/dd8e0df640.png

Chatty 0.8.2b4 says: http://puu.sh/o26N3/0b84ac79c9.png
(years)

I'm either spoiling a April fools joke here, or someone made a goof :P

**Comment by Decicus** [comment]
[Definitely not an April fools](https://github.com/chatty/chatty/blob/c79040281ba167cb2e28f91356fe44159cc3b140/src/chatty/gui/MainGui.java#L2626-L2629)
