### ISSUE TITLE
MacOS UI elements inconsistent.

### ISSUE THREAD

**Issue by Daniel41550** [chatty/chatty#390]
**Describe the bug**
When using the MacOS version, the java or MacOS version of the UI elements is chosen random (to my knowledge).
Mac UI elements

**To Reproduce**
1. Open the program on Mac

**Expected behavior**
To use the same set of UI elements (ideally the MacOS set)
**Debug Log**
[Include a Chatty debug log: https://chatty.github.io/help/help-report_issue.html#log ]
[debug_sessionjavaui.log](https://github.com/chatty/chatty/files/5549719/debug_sessionjavaui.log)
[debug_sessionmacui.log](https://github.com/chatty/chatty/files/5549720/debug_sessionmacui.log)

**Screenshots/Videos**
<img width="708" alt="CleanShot 2020-11-16 at 14 51 36@2x" src="https://user-images.githubusercontent.com/5463196/99307109-ab69d580-281b-11eb-92a3-fdcd49517617.png">
<img width="448" alt="CleanShot 2020-11-16 at 14 51 44@2x" src="https://user-images.githubusercontent.com/5463196/99307115-ae64c600-281b-11eb-988d-0db3be152a7c.png">
Java UI elements
![CleanShot 2020-11-14 at 23 11 04@2x](https://user-images.githubusercontent.com/5463196/99307122-b0c72000-281b-11eb-91ae-493ad579ac16.png)
![CleanShot 2020-11-14 at 23 11 13@2x](https://user-images.githubusercontent.com/5463196/99307128-b3297a00-281b-11eb-9874-33e89daf2390.png)

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Mac OS X (10.15.7/x86_64) 
- Chatty Version (e.g. v0.9.1 Standalone): 0.13
- Java Version (if not using Standalone): 1.8.0_271
- When has the issue first occured (Chatty Version or timeframe): Since I've downloaded it
- How often does the issue occur (everytime, sometimes): Everytime

**Comment by tduva** [comment]
Can you clarify when it changes? After a restart or while the program is running? What Look&Feel do you have selected in the settings under "Look"?

**Comment by Daniel41550** [comment]
It changes on launch, but doesn't always change. After changing the Look and Feel option to system, it now consistently uses the MacOS UI elements, which are the better of the two in my opinion anyways. Thank you!
