### ISSUE TITLE
Support for User Pronoun Add-On https://pronouns.alejo.io/

### ISSUE THREAD

**Issue by marcmagus** [chatty/chatty#392]
**Is your feature request related to a problem? Please describe.**
Alejo has provided the ability for Twitch users to register pronouns at https://pronouns.alejo.io/ and a Chrome extension which adds a badge displaying those pronouns for users who have done so.

**Describe the solution you'd like**
Chatty should enable support for this add-on by fetching the pronouns and displaying them in a similar manner.

**Describe alternatives you've considered**
I looked into providing this via ADDON badges and Addressbook, but it would still be necessary to modify the chatty source to programatically check for pronouns, store a timestamp to avoid too many rechecks, etc. and would pollute the Addressbook with every user ever seen in chat.

**Additional context**
It seems the pronouns are fetched via GET at https://pronouns.alejo.io/api/users/<username> (e.g. "https://pronouns.alejo.io/api/users/marcmagus"); the Chrome extension relies on browser caching to reduce network load. A chatty solution should similarly cache results, but probably not indefinitely, or it should allow a way to refresh as users do sometimes change their pronouns. Similarly, no-result should be cached and rechecked occasionally to support people adding themselves to the database later, but not constantly.

This should be implemented in a way which allows the user to override badges (personally I would want more compact ones) or turn the feature off entirely.

**Comment by Freso** [comment]
I think tduva might already be in Alejo’s Discord to ask API questions from them: https://twitter.com/ChattyClient/status/1333540622624559104 :)

**Comment by tduva** [comment]
This is planned for the next version, however as a simpler implementation at first, where it will show the pronoun in the User Dialog (opened when clicking on a name in chat), not directly in chat. That way it's at least possible to look it up.

**Comment by tduva** [comment]
This is added in v0.14-b1. It's also possible to show them in chat, although due to keeping the implementation simple it may take some time to show up for each user. The settings under "Main - Settings - Other" are disabled by default.

**Comment by lewisje** [comment]
This should be closed, because support exists as of the current version (0.15).

**Comment by lewisje** [comment]
Lately, I haven't seen custom pronouns in Chatty, even though I have the feature turned on and I have set my own custom pronouns; maybe the API has changed.

**Comment by tduva** [comment]
I've seen some API request errors lately, maybe some temporary server issues, but generally it still seems to work.

**Comment by lewisje** [comment]
It started working again for me a few hours ago.
