### ISSUE TITLE
FrankerFaceZ Channel-Specific Badge Assignments

### ISSUE THREAD

**Issue by SirStendec** [chatty/chatty#393]
Recently, we (that is FrankerFaceZ) started letting users assign bot badges to users in their channels. This has been exposed in the API for some time, but between poor documentation and the inability for users to take advantage of it, I don't blame anyone for not catching it and/or implementing support. The feature is intended to let users easily flag their own custom bots without any form of approval, while the global bot badge will be limited to bots in widespread use across Twitch.

All single room endpoints now include arrays of usernames and user Twitch IDs for assigning badges to users in those specific rooms. When possible, clients should always use the Twitch ID rather than a username as usernames may be out of sync with Twitch after an account name change.

Data from the API looks something like:
```json
{
	"room": {
		...
		"user_badges": {
			"2": ["quoteconut"]
		},
		"user_badge_ids": {
			"2": [74024612]
		}
	}
}
```

`user_badges` and `user_badge_ids` are objects with keys that are the badge ID as a string (only a string due to the nature of JSON, and can be treated as integers) and the values are arrays of usernames or Twitch IDs.

In the future, this may support badges other than the bot badge. However, for now, it's limited to the bot badge with ID 2.

Side note: We now have automatically generated documentation available at https://api.frankerfacez.com/docs/ describing rooms and all other endpoints.

**Comment by tduva** [comment]
Thanks for letting me know. I'm implementing the bot badge only for now (with no ability to show possible future other badges), since the bot badge is already set up and works differently from regular badges.

**Comment by tduva** [comment]
This is added in v0.14-b1.
