### ISSUE TITLE
Support for Windows 10 Tiling/Stacking

### ISSUE THREAD

**Issue by jonathanbloom** [chatty/chatty#402]
**Is your feature request related to a problem? Please describe.**
I can't get Chatty to properly stack to one side of the screen using the Windows 10 tiling/stacking feature. I have to manually do this.

**Describe the solution you'd like**
Being able to tile/Chatty to a side of the screen when either using the **Win + Arrow** keys or dragging an application like OBS to one side and it asks which program to put on the other side.

**Comment by jonathanbloom** [comment]
Disregard, found my solution. https://github.com/chatty/chatty/issues/337

**Comment by tduva** [comment]
With these Look&Feel only the custom window doesn't support it, if you enable the setting to use the native window, it works. More information: https://chatty.github.io/help/help-laf.html#native-window
