### ISSUE TITLE
Pressing "Cancel" in the "Send as a reply to a message of" dialog clears message input

### ISSUE THREAD

**Issue by rybak** [chatty/chatty#404]
**Describe the bug**
When you press "Cancel" in the "Send as a reply to a message of" dialog, it clears the message input, which doesn't seem like good UX.

**To Reproduce**
1. Enter a message which starts with an `@<someone>` where `<someone>` already has messages
2. Press Enter key, dialog "Send as a reply to a message of <someone>" will appear
3. Click "Cancel" button in the dialog

**Actual behavior**
1. The dialog "Send as a reply to a message of ..." is closed
2. The message input is cleared, with no way to bring back the typed message.

**Expected behavior**
1. The dialog "Send as a reply to a message of ..." is closed
2. The typed message is left as is in the input field.

**Screenshots/Videos**
![chatty-screenshot](https://user-images.githubusercontent.com/624072/107818234-9b5c8600-6d77-11eb-8302-d22c3d972863.png)

**Additional context**
I pressed "Cancel" because I noticed a typo in the message, so I wanted to continue typing it.

**Comment by tduva** [comment]
The idea behind Cancel is it being a "Don't send" option, although I can see how it could be confusing. When pressing enter, the inputbox will already be automatically cleared, even though it's temporarily halted by the dialog. Although I suppose the text could be re-inserted.

Note that it is possible to retrieve any text in the inputbox you pressed enter on, via the input history: https://chatty.github.io/help/help.html#inputHistory Just pressing up-arrow key after you clicked Cancel would retrieve the message again.

**Comment by tduva** [comment]
This has been added in the latest version.
