### ISSUE TITLE
Cant Uninstall Chatty

### ISSUE THREAD

**Issue by claire435** [chatty/chatty#407]
I've been using Chatty for a while but recently I want to uninstall the program since I'm not using it anymore. however, when I go to my windows 10 uninstall page Catty just isn't on the list. it's just not there. I can't uninstall it because it's not on the uninstall list. I've looked for an unistall.exe and can't find one. how do I uninstall chatty, what am I missing?

**Comment by tduva** [comment]
This should help: https://chatty.github.io/help/help-guide_folders.html#uninstall

**Comment by fynnebr** [comment]
If yout didnt fix yet. Look for the .chatty folder und delete it.
