### ISSUE TITLE
Chatty unable to set tags

### ISSUE THREAD

**Issue by NicciZar** [chatty/chatty#408]
**Describe the bug**
Chatty unable to set setting tag inside Admin Panel (for myself and channels where I am the editor role)

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to the admin panel inside chatty (I am connected to my own channel)
2. Click on "Update"
3. See error:
![image](https://user-images.githubusercontent.com/43537611/110452866-de372280-80c5-11eb-9ef6-036b0fca694b.png)

**Expected behavior**
No errormessage (no error)

**Screenshots/Videos**
Posted on step 3

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Win10 Professional
- Chatty Version (e.g. v0.9.1 Standalone): 0.14
- Java Version (if not using Standalone): Version 8 Update 271 (Used the chatty installer
- How often does the issue occur (everytime, sometimes): When clicking "Update" in the admin panel

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)
Output:
Chatty Version 0.14 Hotkey [Memory] max: 88,428 / 395,968 free: 26,743 [Uptime] 5m 30s [System] Java: 1.8.0_201 (Oracle Corporation / D:\Program Files (x86)\Chatty\runtime) OS: Windows 10 (10.0/x86) Locale: en_GB 
(without the Connection)

**Additional context**
I authenticated Chatty with a Oauthtoken that was generated by a website but I made sure to enable every setting for the key. So I dont know if its because of the key or because of chatty / twitch.

**Comment by tduva** [comment]
Please check that you have all the access under "Main - Account".

**Comment by NicciZar** [comment]
Hi

Chatty should have all the needs permissions to do that but the erromessage persists..

Best regards

**Comment by NicciZar** [comment]
I just want to update / close this thread as I updated to the newest Chatty beta version Chatty (Version: 0.15-b5) and I revoked my previous Access Token and generated a new one (with chatty this time!) and now it doesnt show that the access is denied.

Thanks for updating the token method!
