### ISSUE TITLE
Have Chatty automatically open windows on channel connect. (Also window snapping)

### ISSUE THREAD

**Issue by NicciZar** [chatty/chatty#409]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may include your feature. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.* -> There is no newer version

**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]
- its annoying to open every Window I need when starting up Chatty and connecting to a channel.
- also have the windows snap to the main window

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
- a button on every window (with configs for each channel) where I can set an "autostart on connect" option
- also a list with every channel where I have specific channel configurations (for example autostart on the channel info window)

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]
- An Idea would be: Having tabs like visual studio (or windows10) where the windows snap in place and open again next time I open the program

**Comment by tduva** [comment]
I assume by windows you mean things like Channel Info, Admin Dialog, Highlighted Messages, ..? You can set these to reopen from last session by changing the setting under "Main - Settings - Window - Restore dialogs".

**Comment by NicciZar** [comment]
Yes, that was exactly what I searched. Thank you very much. :)
