### ISSUE TITLE
Custom VIP Badges (New FrankerFaceZ Feature)

### ISSUE THREAD

**Issue by SirStendec** [chatty/chatty#410]
**Describe the solution you'd like**
Hello, friend! Yesterday, FrankerFaceZ added a feature that allows broadcasters to set a custom image for VIP badges in their chat. Example:
![image](https://user-images.githubusercontent.com/14036657/114815448-2cee7100-9d84-11eb-9d69-0691130c32ad.png)

These custom badges work like a normal Twitch custom badge, such as sub badges. Just a total image replacement, no background colors or anything like the special way FFZ handles mod badges.

If a channel has a custom VIP badge, there will be URLs for the badge in the APIv1 room response from FrankerFaceZ. For example, from https://api.frankerfacez.com/v1/room/sodapoppin we see:

```json
{
	"room": {
		"id": "sodapoppin",
		...
		"vip_badge": {
			"1": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/1",
			"2": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/2",
			"4": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/4"
		},
		...
	}
}
```

In a channel with no custom VIP badge set, `vip_badge` will be `null`. Additionally, if users don't supply a high enough resolution image, 2 or 4 may be null to indicate their absence. In the future, we'll have our CDN just upscale things on demand, but that isn't happening yet so please don't rely on behavior like that.

I was hoping Twitch would add VIP badge customization themselves, but as I still haven't heard of it coming by now, I doubt it's coming. In lieu of that, I think FFZ can provide the service reasonably well and so here we are. This should be fairly easy to implement, I'd think.

**Comment by tduva** [comment]
Thanks, this will (finally) be available in the next update.
