### ISSUE TITLE
joins / parts notices delay problem

### ISSUE THREAD

**Issue by linux858** [chatty/chatty#414]
is there a way to short the notices from joins / parts delay from users to my channel? there is 3 minutes delay when I see the notice for someone who joined my channel that he is already there in twitch web browser for 3 minutes already.

**Comment by arrowgent** [comment]
thats an api IRC issue, not sure if that can be solved by chatty
i may be wrong, but twitch obfuscates that, or the IRC api is written like that (intentionally)

**Comment by tduva** [comment]
Joins/parts in Twitch Chat aren't real-time as in real IRC and quite unreliable in general. There isn't any way to change that from the client's side.
