### ISSUE TITLE
No message when channel points were redeemed

### ISSUE THREAD

**Issue by DasMonschta** [chatty/chatty#419]
I get no message when people redeem channel points.

/debug simulate creward is doing what it should do.

Do i need to make specific settings in twitch or chatty for this to work?

**Comment by tduva** [comment]
Only point redemptions that have a chat message attached show up for all users. All redemptions are only visible for the broadcaster when the "Points Redemptions" access is granted under "Main - Account".

**Comment by DasMonschta** [comment]
Thank you so much. I totaly forgot that i just gave rights to chat messages.
