### ISSUE TITLE
can't remember Chatty window position

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#42]
In settings

Dialogs Location/Size
Restore Dialogs

I tested all 4 choices, no1 can't restore position.
Any hint to fix, or I misunderstand this setting.

**Comment by tduva** [comment]
It should remember the main window position either way. Are the settings saved at all?

**Comment by craftwar** [comment]
window size is saved but not position

I use tool to reset position every time

posX, y -7, 538
width, height 984, 512

**Comment by tduva** [comment]
Is that partly off the screen? It won't restore a position that is outside of the visible screen region. Where does it place it?

**Comment by craftwar** [comment]
Yes, can you fix that?

**Comment by tduva** [comment]
That's done on purpose to prevent the Window from being inadvertently created at a position where it can't be reached. Although this will be more lenient in the next version and there will be a setting to disable this check altogether in case it still causes undesired behaviour.
