### ISSUE TITLE
Add option to disable animated emotes when Chatty is not in focus

### ISSUE THREAD

**Issue by Lubjan** [chatty/chatty#423]
**Is your feature request related to a problem? Please describe.**
With Twitch now supporting animated emotes for everyone and not only by using BTTV/FFZ, a lot of "moving" chat will probably appear. When focusing on something else and emotes are looping in Chatty it will probably get distracting.

**Describe the solution you'd like**
I'd like to have the option to either allow `n` loop iterations per emote (though this will probably be harder to implement/the least useful one), to generally disable animated emotes (maybe differentiate between FFZ/BTTV ones) or my personal favourite, to disable emote animation when Chatty is not in focus.

**Describe alternatives you've considered**
Turning of the screen Chatty is on.

**Additional context**
https://blog.twitch.tv/en/2021/06/04/kicking-off-10-years-with-our-biggest-emote-update-ever/

**Comment by jspraul** [comment]
This has been implemented, right?

![image](https://user-images.githubusercontent.com/115931/166860827-d0ddb06d-e3a6-40d7-8397-29fc87c768e4.png)

**Comment by Lubjan** [comment]
Well yes and no, the current implementation only allows you to either have animations or not. My proposal was to add an option where you can set a fixed amount of animation loops or disable emotes only if Chatty is not the focused window, to remove some distraction.

**Comment by tduva** [comment]
Please check out the beta, settings for this have been added.

**Comment by Lubjan** [comment]
Works great, thanks for adding it. ^^
