### ISSUE TITLE
Twitch Animated emotes are static

### ISSUE THREAD

**Issue by deanpcmad** [chatty/chatty#424]
**Describe the bug**

Twitch animated emotes are now live but they show as static images in Chatty

![](https://files.deanpcmad.com/2021/cb792187-78bf-4540-9f3b-94c6efad4270/2021-06-18-17-15-28.gif)

**Expected behavior**

Animated emotes should be animated

**Additional information (please complete the following information):**

I'm using the latest beta version (0.15-b7) on Windows 10

**Comment by arrowgent** [comment]
new api,  give it a bit and it will be tested and finalized

https://github.com/chatty/chatty/pull/425

**Comment by deanpcmad** [comment]
Fixed with 655186a9a75801ce0e02b391d5ce6f7d4f8ead31
