### ISSUE TITLE
Animated Emotes are not showing up on My Emotes/Auto completion

### ISSUE THREAD

**Issue by MPThLee** [chatty/chatty#426]
**Describe the bug**
Animated Emotes doesn't shows on Emoticons-My Emotes / Auto completion

**To Reproduce**
[Steps to reproduce the behavior:
1. Ctrl-E and go My Emotes tab
2. chat message starts with `:`

**Expected behavior**
Animated emotes shows up.

**Additional information (please complete the following information):**
- OS : Windows 10
- Chatty Version: v0.15-b8

**Additional context**
I just restart chatty 3 times, but it never shows. however, it still renders on chat ok.
Access on Emote shows Restricted. But no access indicator (Which i can access it).
 
Seems like it highly depends on new Emotes API. Emote ID start with `emotesv2_` unlike static emote(which is just number)
See #421 too.

**Comment by lemings68** [comment]
You can find the SHA for the commit that shows tduva working on the new emote API already in this PR's comments: 
https://github.com/chatty/chatty/pull/425
This is the commit: https://github.com/chatty/chatty/commit/655186a9a75801ce0e02b391d5ce6f7d4f8ead31

**Comment by tduva** [comment]
Can you please confirm if this works for you in v0.15-b9.

**Comment by Lemingss** [comment]
> 
> 
> Can you please confirm if this works for you in v0.15-b9.

The animated emotes in the Ctrl+E emote list show up in a different grouping, and when hovering over an animated emote it isn't animated in the dialogue. I haven't noticed anything else, I've been using the beta build since it came out.

Do you want me to create an Issue for these?

In the image below, all of those emotes are from the same channel, but the bottom group is the animated ones
![image](https://user-images.githubusercontent.com/26569321/123601033-826ce280-d7f7-11eb-903d-0841da172775.png)

**Comment by tduva** [comment]
Thanks for the feedback. Since the APIs are quite new and some other APIs previously used were removed the implementation isn't quite polished. As long as the emotes show up for you, both in the Emote Dialog and sending message in chat, it's correct.

**Comment by arrowgent** [comment]
animated emotes do not show up for me in the emote dialog
[.](https://i.imgur.com/Mup81nT.png)

animated emotes show up in chat but when i type them manually they do not appear


Chatty Version 0.15-b9 Hotkey [Memory] max: 599,040 / 7,296,512 free: 480,294 [Uptime] 9m 26s [System] Java: 1.8.0_292 (Private Build / /usr/lib/jvm/java-8-openjdk-amd64/jre) OS: Linux (4.15.0-147-generic/amd64) Locale: en_US [Connection] Connected to: irc.chat.twitch.tv/44.226.36.141:6697 (9m 22s, 1 channels)
