### ISSUE TITLE
[0.15-b9] emote window doesnt show subscription emotes, only ffz & bttv 

### ISSUE THREAD

**Issue by arrowgent** [chatty/chatty#427]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may fix your issue. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*

**Describe the bug**
[A clear and concise description of what the bug is.]
emote window doesnt show subscription emotes, only ffz & bttv 

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to '...' open emote window
2. Click on '....' go to "Channel"
3. Scroll down to '....' "subscription emotes"
4. See error] no emotes.

**Expected behavior**
[A clear and concise description of what you expected to happen.]
previously subscriber emotes showed up under ffz/bttv emotes

**Debug Log**
[Include a Chatty debug log: https://chatty.github.io/help/help-report_issue.html#log ]

**Screenshots/Videos**
[If applicable, add screenshots or videos to help explain your problem.]

**Additional information (please complete the following information):**
- OS (e.g. Windows 7):  linux
- Chatty Version (e.g. v0.9.1 Standalone): 0.15-b8
- Java Version (if not using Standalone): 
- When has the issue first occured (Chatty Version or timeframe): 
- How often does the issue occur (everytime, sometimes): 

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)
Chatty Version 0.15-b8 Hotkey [Memory] max: 546,816 / 7,296,512 free: 221,688 [Uptime] 1d 7h 26m 34s [System] Java: 1.8.0_292 (Private Build / /usr/lib/jvm/java-8-openjdk-amd64/jre) OS: Linux (4.15.0-144-generic/amd64) Locale: en_US [Connection] Connected to: irc.chat.twitch.tv/44.226.36.141:6697

**Additional context**
[Add any other context about the problem here.]

this might have started happening with twitch's new api, even using chatty v0.14

**Comment by arrowgent** [comment]
https://github.com/chatty/chatty/issues/421

this might be related,  new requirements for emote interface

**Comment by arrowgent** [comment]
https://github.com/chatty/chatty/releases/tag/v0.15-b9

oh, of course... check releases first
LET ME TEST

**Comment by arrowgent** [comment]
https://github.com/chatty/chatty/pull/425

subscriber emotes show up in "My Emotes"
animated emotes show up as "(0 emotes)" with no emotes

animated emotes show up in chat properly when used by others
not when used by self

**Comment by tduva** [comment]
Since this is likely an API issue can you please include a Debug Log.

**Comment by tduva** [comment]
Also please make sure that your token is created through Chatty and not from another app.

**Comment by EpsilonAlpha** [comment]
Same issue here: No Emotes are shown in the Emotes Window

- Token was generated from Chatty
- In my case, the issue occurs on my Windows 10 and macOS Machine, so no direct relation to a specific operating system
- The autocomplete of Emotes still works, with Tab or : .
- Also will the Emote be shown if I enter the Emote Name manually

Log File:
[chattylog.txt](https://github.com/chatty/chatty/files/6736171/chattylog.txt)

**Comment by arrowgent** [comment]
![.](https://i.imgur.com/bjOnKld.png)

pretty straight forward
Emote Dialog -> Channel
ffz/bttv emtoes appear =/= Subscriber emotes Do Not Appear


Subscriber Emotes used to appear under "Channel" below the ffz/bttv emotes

**Comment by tduva** [comment]
@EpsilonAlpha Your log is incomplete, so it doesn't show a version number, but based on the contents you are not using the latest version, so it can't work in the first place.

**Comment by tduva** [comment]
@arrowgent All your Helix API requests are failing with 401, which indicates authentication failure. Emotes can't work in anything other than received messages without those requests working. As to why authentication fails I don't know. Maybe try to disconnect Chatty and redo your token or something.

**Comment by EpsilonAlpha** [comment]
> @EpsilonAlpha Your log is incomplete, so it doesn't show a version number, but based on the contents you are not using the latest version, so it can't work in the first place.

Strange since I copied the whole log. I'm using the 0.14

**Comment by arrowgent** [comment]
> > @EpsilonAlpha 
> Strange since I copied the whole log. I'm using the 0.14
irreguardless which version youre using, the api has changed.  old versions will have missing emotes due to this

`
Removed twitchemotes.com API (because it was turned off), resulting in less emote info in some places
`


yes i have not created a new oauth login for almost 2 or more years
... i could do this, with backup, which means i have to do a number of things to change my oauth at several places using other tools ...
clearly im not willing to do that, but if that is the solution for some reason; i will just wait.

**Comment by EpsilonAlpha** [comment]
> > > @EpsilonAlpha
> > > Strange since I copied the whole log. I'm using the 0.14
> 
> irreguardless which version youre using, the api has changed. old versions will have missing emotes due to this
> 
I know

> `Removed twitchemotes.com API (because it was turned off), resulting in less emote info in some places`
> 
Yeah, Twitchemotes changed

> yes i have not created a new oauth login for almost 2 or more years
> ... i could do this, with backup, which means i have to do a number of things to change my oauth at several places using other tools ...
> clearly im not willing to do that, but if that is the solution for some reason; i will just wait.

I will also wait for an update to fix it

IMHO:
I don't get why Twitch is changing their API so frequently! There is no valid reason to revamp the API over and over, not adding or removing endpoints (which would make much more sense). That's also the reason why I put my own App out of service, it was too much work besides my main job to maintain compliance with the current version of Twitch. 

From my perspective, an API is meant to provide a constant, reliable interface for applications to interact with the service and doesn't need to change very frequently like the Web UI. But Twitch is violating that concept.

**Comment by tduva** [comment]
> > > > Strange since I copied the whole log. I'm using the 0.14
> > 
> > 
> > irreguardless which version youre using, the api has changed. old versions will have missing emotes due to this
> 
> I know

It was just a bit confusing getting feedback on an older version, because this issue is specifically about v0.15-b9 (it says it in the title).

**Comment by EpsilonAlpha** [comment]
> > > > > Strange since I copied the whole log. I'm using the 0.14
> > > 
> > > 
> > > irreguardless which version youre using, the api has changed. old versions will have missing emotes due to this
> > 
> > 
> > I know
> 
> It was just a bit confusing getting feedback on an older version, because this issue is specifically about v0.15-b9 (it says it in the title).

Yeah, I know. Just wanted to show: It's not specific to the beta versions.

**Comment by tduva** [comment]
> yes i have not created a new oauth login for almost 2 or more years
> ... i could do this, with backup, which means i have to do a number of things to change my oauth at several places using other tools ...
> clearly im not willing to do that, but if that is the solution for some reason; i will just wait.

What are you waiting for? And why do you require other tools to update the token in Chatty?

**Comment by EpsilonAlpha** [comment]
I think the new update fixed that, works like a charm! Thanks :)

**Comment by arrowgent** [comment]
v15.0

> remove token access
dont revolk token access

> verify login oauth token
open url in browser and authorize

> reconnect token
close chatty and reopen

> issues discussed are resolved
