### ISSUE TITLE
User Dialog Button Shortcuts not working, v0.15-b9

### ISSUE THREAD

**Issue by ironforward** [chatty/chatty#429]
**Describe the bug**
When i click on a user in a chatroom, the user dialog opens, then i press a keyboard button that has been set up as a shortcut for a button action, but nothing happens. However, i can still mouse over to the dialog and click the button manually and it will do the correct action.

**To Reproduce**
1. Go to Settings
2. Go to Commands
3. Click Edit on User Dialog Buttons
4. Paste in the following: 
```
/Ban[5], /Unban[7], 10m[1], 30m[2], 1h[3], 24h[4]
/ModUnmod

@AutoMod
.Approve=/Automod_approve
.Deny=/Automod_deny

Delete[6]=/delete $$(msg-id)
```
5. Click Save in the dialog
6. Click Save in the Settings
7. Click on a user in a chat room, which should open the user dialog, do not click on the dialog.
8. Press '5' to try to ban them

**Expected behavior**
The keyboard shortcut should submit the command associated with it.

**Debug Log**
Looking at the debug logs, it logs nothing seemingly related to this particular issue

**Screenshots/Videos**
the keyboard shortcuts shown here on the buttons are not functioning in v0.15-b9
![image](https://user-images.githubusercontent.com/7257376/124172846-2ad0b000-da5f-11eb-95b3-5bede50e78bf.png)

**Additional information (please complete the following information):**
- OS: Windows 10
- Chatty Version: v0.15-b9
- Java Version: 1.8.0_201
- When has the issue first occurred: v0.15-b9
- How often does the issue occur: in all user dialogs, every time

**Additional context**
these were working in v0.15-b7 (i never tried b8)

**Comment by ironforward** [comment]
this issue ended up being local!

**Comment by tduva** [comment]
Local how? If it's something other users may encounter as well, it might be useful to share what the problem was.

**Comment by ironforward** [comment]
oh the issue was completely outside of Chatty

when i was trying to ban harassers in the chat quickly via the dialog shortcuts, i was using the keys on my mouse, which turned out to not be working at all in _any_ app, and simply unplugging the mouse and plugging it back in got it all working again.

i definitely should have tested it out more before bothering to submit the report 😅
