### ISSUE TITLE
Chat message notifications for the first message only

### ISSUE THREAD

**Issue by lhorace** [chatty/chatty#432]
This is a quality of life feature request. Previously, I use to have Chatty play a sound, whenever a chat message was received. However, overtime, this became a nuisance and a distraction. Disabling the function now creates a new problem. Where as (not often), I miss out on messages and by the time I notice it and respond. The user has already left.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a notification for the first time the user types, over a period of time. More precisely, when a user enters the chat, and sends his/her message. I get a notification only once, till a user defined time has elapse, and resets. 

**Describe alternatives you've considered**
I couldn't find an alternative to this feature.

**Additional context**
N/A

Would this be possible?

**Comment by tduva** [comment]
I believe you are looking for the "Passive Cooldown" setting in the Sound tab of a Notification Event.

Quote from the [help](https://chatty.github.io/help/help-settings.html#Notifications), section "Event settings (Notification/Sound)":

> For example if your chat isn't very busy and you want to get notified of new messages so you notice, then you could add an event of type Chat Message with a Passive Cooldown of 5m, which means the sound only plays if someone writes a message after the chat has been silent for at least 5 minutes. If on the other hand you would set it as a regular Cooldown it would play the sound after 5 minutes even if the chat has been busy non-stop, at which point you probably wouldn't need to be alerted since you're already paying attention to it.
