### ISSUE TITLE
User list gets squished to the side after letting app start up, but only on some channels

### ISSUE THREAD

**Issue by Ulexos** [chatty/chatty#434]
**Describe the bug**
Ever since version 0.15 (just tried beta 0.16 b1, issue persists), I noticed that when I let Chatty launch and join each and every channel in the background without interacting with it until it has joined each channel, some channels' user lists on the right side next to the chat window get squished to the side as far as possible.
This seems to only happen on the same channels, on others it never happens, or at least hasn't yet.
Seems like it happens more often on live channels, maybe where more/a lot of users are in the chat?

**To Reproduce**
1. Launch Chatty
2. Wait for it to finish joining each and every channel
3. Click on any channel
4. Usually the ones that are live with a lot of users in the chat will now have their user list squished to the right side - until one either relaunches Chatty and scrolls/clicks through each and every channel (annoying, tedious and time consuming to do on each launch when one is in a lot of channels), or reopens the channels where the user list got squished (again annoying and time consuming)

**Expected behavior**
Launching the app and doing whatever (interacting with it or letting it join each channel in the background), being able to click on any channel without the user list getting squished to the side on some of the channels.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/16191795/130325185-646b4833-a7f4-49d2-9f4f-200b76352471.png)

**Additional information (please complete the following information):**
- OS Win 10 Pro 21H1 Build 19043.1110
- Chatty Version 0.15 and 0.16 b1
- Standalone installer
- Issue first occured on version 0.15, the update where it stopped visually distracting by switching to each channel on join, and instead staying on the most recently joined channel (top right by default)
- Issue occurs everytime I launch the app, unless I scroll through each and every channel right after it launched, opening each channel by doing so on startup, before the app has joined all of them

**Comment by jerrycarlson** [comment]
I have this same persistent issue.

I'm running Chatty (always the latest stable release of the "JAR-Version (.zip)") on two different PC platforms but both running the latest Windows 10 and the latest stable JRE.

I can't detect a pattern as to which channels will exhibit the squished userlist.  Also, I am certain that sometimes a channel's userlist will be fine when I first run Chatty but then if I minimize Chatty to the system tray and pull it back up later, that same channel's userlist gets squished.

**Comment by Ulexos** [comment]
Issue still persists on the latest beta version.
I used Chatty_0.16-b4_win_standalone_setup.exe to install it on my D: drive.
Could it be that Chatty absolutely has to be on the speediest system SSD drive available for this issue to not occur?
As mentioned before, the issue especially seems to happen for chats where the streamer is live and a lot of users are active/in the chat.
However, the issue is not exclusively limited to those chats.
It occurs on other chats that don't fit those criteria as well, seemingly randomly.
But there definitely is a pattern in regards of this issue.
Certain open chats seem to have this issue more often than not.
For example for the channels xqcow, jerma985, franzj Chatty almost if not always is squishing the userlist to the side, while others almost if not always have the userlist shown properly.

**Comment by Ulexos** [comment]
Issue still persists on 0.16 beta 5.

**Comment by Ulexos** [comment]
Hmm, setting this to 120 instead of the default 0 might have just fixed it!

![image](https://user-images.githubusercontent.com/16191795/147739267-1c1acd60-9467-40cd-9b7e-c49a231f461c.png)
