### ISSUE TITLE
Whispers bug

### ISSUE THREAD

**Issue by Phlynn** [chatty/chatty#44]
When i was testing whispers i ran chatty and wrote from another twitch account to myself.
Always some message was missing. I could see it via web twitch, but didn't get it in chatty.
Of course in chatty my account was verified and i got some messages, but not all of them.
Please test and fix it!
Thanks in advance.

**Comment by tduva** [comment]
It's a known issue with IRC at the moment that some whispers aren't received.

**Comment by Phlynn** [comment]
So the problem on Twitch's side? No info when it will be fixed?
