### ISSUE TITLE
[Feature Request] Ban user on multiple channels

### ISSUE THREAD

**Issue by Konroad** [chatty/chatty#442]
I use Chatty to moderate multiple channels.

The ban/timeout commands only work in the recent opened channel chat window I guess?!

So, is it planed to add an option to ban a user on multiple channels by one click or in a similar way?

I did not found any solution in the chatty guide to do this.
So I guess there is no option like this yet.

My idea would be to add a checkbox in the userinfo box or by holding CTRL when someone should get banned while using the userinfo box. Also a popup that asks for permittion when I want to ban a user.

**Comment by tduva** [comment]
You could create a button with a Custom Command that uses the `/chain` command to run several commands and `/msg` to send a message to a specific channel:

`Ban All=/chain /msg #chan1 .ban $$1 | /msg #chan2 .ban $$1`

This will only show the message being sent in the currently active channel, not in the target channels, although it would show the response.

> 22:02:21 -> #chan1: .ban username
> 22:02:21 -> #chan2: .ban username

See the [this video](https://www.youtube.com/watch?v=-XoVGP61_NY) on how to add buttons to the User Dialog.

**Comment by Konroad** [comment]
Thanks for your fast response. 
The chain command makes absolutly sense for this little problem.
I‘ll gonna use this commands more often. :)
