### ISSUE TITLE
Buggy emote display

### ISSUE THREAD

**Issue by mtrp12** [chatty/chatty#443]
**Describe the bug**
The emote Dingdingdingding is shown along with part of the text

**To Reproduce**
Only tested in twitch.tv/gorgc. Do Dingdingdingding emote.
![image](https://user-images.githubusercontent.com/6695345/140524720-781c649b-90b9-4739-8df2-47cb661cec68.png)

**Screenshots/Videos**
Currently shows this
![image](https://user-images.githubusercontent.com/6695345/140522723-9750028d-3cca-4c8b-b964-23fde6b71de7.png)

Should look like this
![image](https://user-images.githubusercontent.com/6695345/140522867-6d177716-b863-4a40-b8b7-1872cf6fdcb1.png)

**Additional information (please complete the following information):**
- How often does the issue occur (everytime, sometimes): Everytime
- Chatty Version 0.15 Hotkey 
- [Memory] max: 1,052,160 / 14,614,528 free: 773,840 
- [Uptime] 7h 49m 29s 
- [System] Java: 1.8.0_292 (Private Build / /usr/lib/jvm/java-8-openjdk-amd64/jre) 
- OS: Linux (5.4.0-89-generic/amd64) , kubuntu 20.04.3
- Locale: en_US
-  [Connection] Connected to: irc.chat.twitch.tv/34.217.198.238:6697 (1h 42m 31s, 3 channels)

**Comment by tduva** [comment]
I can't reproduce this. Do you have any entries in the Filter setting?

**Comment by mtrp12** [comment]
yes. I am using a filter to reduce spam.
`replacement:none reg:(.{3,})(?=\1)`

Also, an ignore filter.
`reg:([⠄-⣿▀-▟]){6,}?`

Forgot, where i copied them from, but found a reference here [issue#361](https://github.com/chatty/chatty/issues/361)

**Comment by tduva** [comment]
The `replacement:none reg:(.{3,})(?=\1)` entry causes this since it removes part of the emote and then it comes out weird. I'll change it so that it doesn't apply the replacement where it overlaps with other elements like in this case.
