### ISSUE TITLE
Emotes are not scaled in the "Emoticons" dialog

### ISSUE THREAD

**Issue by rybak** [chatty/chatty#454]
Tested in version 0.17.

**Describe the bug**
Emotes are shown at the same size despite captions telling that they are at different scales.

**To Reproduce**

1. Send any emote in chat
2. Click on the emote that you've just sent
3. Observe the opened dialog

**Actual behavior**
Emotes are not scaled. Screenshot:

![image](https://user-images.githubusercontent.com/624072/151830390-b99fa6bc-fed7-48da-97c7-e7de7b41c9a2.png)

**Expected behavior**
Emotes are scaled. Can't show a Chatty screenshot, here's a screenshot of [a page from twitchemotes.com](https://twitchemotes.com/channels/22680841/emotes/emotesv2_33572061fbff4690baecf04f4bd1ca2f):
![image](https://user-images.githubusercontent.com/624072/151829775-089382d9-db4b-46c9-bef5-fae8fe23d1a9.png)

**Additional information (please complete the following information):**
- OS: Linux KDE Neon (basically, Ubuntu)
- Chatty Version: 0.17.
- Java Version (if not using Standalone): OpenJDK 17.0.1
- When has the issue first occurred: not sure, noticed in one of the 0.17 betas by accident.
- How often does the issue occur: every emote that I've tried has this problem.

**Comment by tduva** [comment]
Thanks, the issue will be fixed in the next version.
