### ISSUE TITLE
[emotes] are endangered emotes not part of helix api?

### ISSUE THREAD

**Issue by arrowgent** [chatty/chatty#460]
chatty 0.17

https://github.com/chatty/chatty/blob/6f32ca8b885f9a22bb621e75fbc45652277d84c3/src/chatty/gui/components/EmotesDialog.java#L153

https://github.com/chatty/chatty/blob/6f32ca8b885f9a22bb621e75fbc45652277d84c3/src/chatty/gui/components/EmotesDialog.java#L174

are these only available on GQL api within the browser?
or are these emotes permanently being removed from twitch?

can you point to a twitch dev log link which could help?

thanks

**Comment by Felanbird** [comment]
You are correct these emotes are available via GQL for browser chat. 
https://github.com/twitchdev/issues/issues/445

**Comment by arrowgent** [comment]
awesome thanks for info.  hopefully twitch gets their butts going to merge these onto helix or whatever.

ive setup the local emote thing for those emotes i would like to use, this is a great option

**Comment by tduva** [comment]
The emotes were "endangered" because they are not available in the new API and thus were only available until the old API was turned off. The emotes themselves are still on Twitch, Chatty just has no way of knowing about them (other than manually adding them through the Local Emotes feature).

**Comment by lewisje** [comment]
Is there a guide to adding endangered emotes (that one has access to on Twitch) to Local Emotes?
