### ISSUE TITLE
Troubleshooting runaway CPU usage?

### ISSUE THREAD

**Issue by jspraul** [chatty/chatty#466]
**Describe the bug**
One CPU completely maxed out (constant 50% CPU usage on machine with 2 CPUs reported until chatty was restarted)
![202205031640-chatty-task-manager](https://user-images.githubusercontent.com/115931/166565728-52cae179-b225-4bfd-b0e3-9870f1d7c896.png)

**To Reproduce**
Extensive uptime with several popular channels logging

**Expected behavior**
Hopefully able to only use CPU needed

**Debug Log**
Will update with attachment if it occurs again

**Screenshots/Videos**
The same CPU usage history, after I was able to download a screenshot tool with an editor to highlight the time when chatty was restarted
![202205031643-chatty-task-manager](https://user-images.githubusercontent.com/115931/166566485-2f59eb82-7e75-4246-aa68-174f0e940cb3.png)

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Linux 5.10
- Chatty Version (e.g. v0.9.1 Standalone): v.17 
- Java Version (if not using Standalone): openjdk-18
- When has the issue first occurred (Chatty Version or timeframe): only used v.17 so far; I will update eventually but did not see anything called out as a fix on v.18
- How often does the issue occur (every time, sometimes): eventually (left running for multiple days) 

**Additional context**
I am looking for suggestions how to figure out which thread is maxing out the CPU, maybe [dumping the stack](https://blog.fastthread.io/2020/06/23/flame-graph-from-java-thread-dump/). It seems like whichever is causing the problem is not visible to the task manager / htop because the only ones shown were using 3% CPU intermittently (or less). I will try to capture more details on this aspect of the scenario if it happens again.

**Comment by jspraul** [comment]
This seemed useful: https://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMjIvMDUvNS8tLTIwMjIwNTA0MjIwOC1jaGF0dHkudHh0LS0zLTktNA==&
[ft-report-202205042208-chatty.pdf](https://github.com/chatty/chatty/files/8628514/ft-report-202205042208-chatty.pdf)

Is there an alternative GIF implementation that is able to clean up after itself? Or is this because they are all being held onto rather than GC'd?

229 threads with same stack trace
[...]
STATE : TIMED_WAITING
stackTrace:
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(java.base@18/Native Method)
at sun.awt.image.GifFrame.dispose(java.desktop@18/GifImageDecoder.java:669)
at sun.awt.image.GifImageDecoder.readImage(java.desktop@18/GifImageDecoder.java:458)
at sun.awt.image.GifImageDecoder.produceImage(java.desktop@18/GifImageDecoder.java:212)
at sun.awt.image.InputStreamImageSource.doFetch(java.desktop@18/InputStreamImageSource.java:270)
at sun.awt.image.ImageFetcher.fetchloop(java.desktop@18/ImageFetcher.java:212)
at sun.awt.image.ImageFetcher.run(java.desktop@18/ImageFetcher.java:176)
Locked ownable synchronizers:
- None

**Comment by jspraul** [comment]
I don't know Java, especially not sun.awt.image.Gif*; maybe one of these workarounds would still help? I will also look into GIF on Android (like [Glide](https://github.com/bumptech/glide)), someone's got to have done some work to minimize resource usage...

[JDK-4839709](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4839709) Animated GIF in JEditorPane eats CPU when not displayed still (Duplicate: 2003-03-31)

> [Bug ID: 4302818](https://web.archive.org/web/20110427133533/http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4302818) Animated GIF eats CPU when not visible
> It appears as if the GIF is continually being decoded even though no one is currently asking it to paint.
> [...]
> You can work around this bug by explicitly calling flush on the Image associated with the animated GIF.

[JDK-4821632](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4821632) Displaying Animated Gif in JEditorPane causes nonstop CPU usage (Resolved: 2003-04-25)

> CUSTOMER WORKAROUND: [JDK-4215118](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=%204215118) multi gif icons in swing components cause unnecessary repaints (Resolved: 1999-10-13)
> Override 
> ```
>     public boolean imageUpdate(Image img, int infoflags,
> 			       int x, int y, int w, int h)
> ```
> to return false if the image is no longer associated with the JLabel or AbstractButton.

**Comment by jspraul** [comment]
It looks like `imageUpdate` is implemented ~[here](https://github.com/chatty/chatty/blob/master/src/chatty/gui/components/textpane/ChannelTextPane.java#L359); returning false when no longer needed may not be enough?

**Comment by jspraul** [comment]
GIF performance, debugging https://github.com/chatty/chatty/commit/8289ec6dad6c5c7502ad3822d3dcff53fc33db49 (Sep 27, 2018)

I was thinking maybe this "TODO" could be the issue, images not being cleared if more than two lines were removed at once...
https://github.com/chatty/chatty/blob/c0d8eef92ef97911050a019874117f02e1d88fbf/src/chatty/gui/components/textpane/ChannelTextPane.java#L2090-L2101

... but it looks like it is only ever called with "2" as a parameter (in ChatTextPane):

![202205050114-chatty-removeFirstLines-references](https://user-images.githubusercontent.com/115931/166866782-19d35577-3374-4486-b879-f074f9d8029b.png)

**Comment by jspraul** [comment]
I don't see any call to `imageViews.remove` when all `MyIconView` are removed (line 141). Is the reference to the image left as a key?
https://github.com/chatty/chatty/blob/c0d8eef92ef97911050a019874117f02e1d88fbf/src/chatty/gui/components/textpane/MyEditorKit.java#L121-L146

**Comment by jspraul** [comment]
I turned animated emoticons back on and [a heap dump](https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMi8wNS81Ly0tMjAyMjA1MDUwMjAwLWhlYXAtZHVtcC5iaW4tNi00LTM5Lmpzb24=) right away looks promising... ([PDF Report](https://github.com/chatty/chatty/files/8629028/heapReport-202205050211-chatty.pdf))

![image](https://user-images.githubusercontent.com/115931/166871627-dee1dbce-00ee-412f-9c9d-ea18a74e2c83.png)

Then this is the "Unreachable (garbage) objects":

![image](https://user-images.githubusercontent.com/115931/166872327-507ced4e-5a13-4937-a73f-472764be676b.png)

I will see how this looks after running for a while.

**Comment by jspraul** [comment]
[Thread](https://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMjIvMDUvMTEvLS0yMDIyMDUxMDE2MzAtc3RhY2stZHVtcC5iaW4uZ3otLTEyLTE0LTQ2) and [heap](https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMi8wNS8xMS8tLTIwMjIwNTEwMTYzMC1oZWFwLWR1bXAuYmluLmd6LTEyLTE3LTIxLmpzb24=) dumps. ([pdf1](https://github.com/chatty/chatty/files/8669839/ft-report-202205101630-stack-dump.pdf); [pdf2](https://github.com/chatty/chatty/files/8669842/heapReport-2022-05-11-08-23.pdf))

**Comment by tduva** [comment]
> ![image](https://user-images.githubusercontent.com/115931/166871627-dee1dbce-00ee-412f-9c9d-ea18a74e2c83.png)

I don't really understand this. If they are unreachable objects they should be able to be garbage collected. Of course it might hold of on collecting them for a bit, so it could depend on what kind of garbage collection has been run before the heap dump.

**Comment by tduva** [comment]
> I don't see any call to `imageViews.remove` (and apparently should call `Image.flush` per the other workaround mentioned above) when all `MyIconView` are removed (line 141). Is the reference to the image left as a key?
> 
> https://github.com/chatty/chatty/blob/c0d8eef92ef97911050a019874117f02e1d88fbf/src/chatty/gui/components/textpane/MyEditorKit.java#L121-L146

The call to `imageViews.remove` is one line 141, via removing the element through the iterator. The collection returned by `imageViews.values()` removes it from the map ("The collection supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove..").

**Comment by tduva** [comment]
Each animated image has it's own thread that decodes the frames and sends them to the registered components to repaint with the new pixels. As you noticed my JTextPane modifications are designed to stop the thread for images that have scrolled off-screen. In my tests that's working fine for me. Unused emotes are also removed entirely after a while.

The data you posted is unfortunately lacking some context of what emotes were loaded when or are still being shown. The data from when the program is already unresponsive could be skewed by things not working properly anymore due to possibly out of memory errors (for example one of them shows the debug window causing a lot of memory usage, which could be due to errors being spammed while not being able to clean up properly anymore).

Chatty is also not really designed to run indefinitely. Various data is collected over time that is required for the features to work. Of course this depends on what channels you join, how much chat activity there is and so on. Increasing the max memory can help. Of course if GIF threads are for some reason not cleaned up for you that would not be intended.

The recent betas had some changes how aniamted emotes work in the background, but in practice it behaved pretty much identical in my tests, so I don't know if it would change anything for you.

**Comment by jspraul** [comment]
Just wanted to say thanks for your time. I've shut off animations with the new setting and everything runs fine, and if animations are on but the current joined channel isn't popping off it's also fine.

I would also want to test with a few different JDK's before dropping this in your lap.
