### ISSUE TITLE
Feature Request: First message in this stream

### ISSUE THREAD

**Issue by Emilgardis** [chatty/chatty#469]
**Is your feature request related to a problem? Please describe.**
Twitch has a feature to tell when a new user first types something in the chat (first-time chatter), chatty has this incorporated, but what I'd want is the same feature but for non-first time chatters, i.e people that are typing the first message since stream start + chat was connected.

**Describe the solution you'd like**
A badge similar to the "First message in chat" but instead signifying "First message in this stream". This should probably be configurable per channel.

**Comment by tduva** [comment]
The `config:firstmsg` prefix matches on the first message of a user in the session. https://chatty.github.io/help/help-settings.html#Highlight_Meta_Matching

You can add a Custom Addon Badge and add `$m:config:firstmsg` to it's Restriction field. Or you can e.g. configure a Custom Msg. Color and add `config:firstmsg` as the item.

**Comment by Emilgardis** [comment]
great, did not realise it was a feature already. thank you!

**Comment by Emilgardis** [comment]
followup, is there a way to reset the session data (e.g first seen and whatever firstmg uses) with a command or is restarting the app the only solution?

**Comment by Emilgardis** [comment]
implemented with eac91015bbae34e04854768744ed1917eca524fb
