### ISSUE TITLE
open links without popup confirmation?

### ISSUE THREAD

**Issue by mataski** [chatty/chatty#483]
Really frustrating if you open 10+ links a day.

Thanks for great little app.

**Comment by tduva** [comment]
You can disable the popup for some URL sources under "Main - Settings - Window - "Open URL Prompt". From what place in Chatty are you opening these URLs from?

**Comment by mataski** [comment]
![image](https://user-images.githubusercontent.com/62036912/219339456-b40863d7-4286-46fb-834d-ae772c4d6c85.png)
