### ISSUE TITLE
no sound with Voicemeeter

### ISSUE THREAD

**Issue by mataski** [chatty/chatty#485]
If you remap Chatty through Voicemeeter's virtual cable (to control for streaming, tell OBS which apps can record sound etc.) there is no more sound during highlights, e.g. your name or any custom word you have under Highlight Messages when mentioned there's only visual alert (red box) and no more sound (dink!).

It works if you put Chatty back to default device.

I do not think this is Voicemeeter issue, because all other apps work fine, Chrome, Firefox, OBS, any music/video player MPC/VLC, etc. Only chatty produces no sound.

![image](https://user-images.githubusercontent.com/62036912/221563684-ee7d3912-e330-4f83-92a4-c39eadbdc438.png)

**Comment by tduva** [comment]
Have you tried changing the output device in Chatty instead?

**Comment by mataski** [comment]
Where is the setting exactly?

**Comment by tduva** [comment]
It's under "Main - Settings - Notifications - Sound Notification Settings".

**Comment by mataski** [comment]
solved
