### ISSUE TITLE
[v0.23] FFZ supported badge disappeared

### ISSUE THREAD

**Issue by arrowgent** [chatty/chatty#487]
*First of all please check if there's already a newer version of Chatty (including beta versions) that may fix your issue. You can use <Help - Check for update> in Chatty to find out if there's an update for you or go to the Releases tab in this repository to view all the recent versions.*

**Describe the bug**
[A clear and concise description of what the bug is.]
FFZ supported badge disappeared

**To Reproduce**
[Steps to reproduce the behavior:
1. Go to '...' have FFZ badge
2. Click on '....' compare to FFZ extension in twitch chat (browser)
4. See error] no FFZ badge in chatty

**Expected behavior**
[A clear and concise description of what you expected to happen.]
FFZ supporter badge should be visible

**Debug Log**
[Include a Chatty debug log: https://chatty.github.io/help/help-report_issue.html#log ]

**Screenshots/Videos**
[If applicable, add screenshots or videos to help explain your problem.]

**Additional information (please complete the following information):**
- OS (e.g. Windows 7):  linux x86_64
- Chatty Version (e.g. v0.9.1 Standalone): v0.23
- Java Version (if not using Standalone): 
- When has the issue first occurred (Chatty Version or timeframe):  v0.23 (was working then stopped)
- How often does the issue occur (every time, sometimes): everytime

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)
Chatty Version 0.23 Hotkey [Memory] max: 1,026,048 / 2,048,000 free: 950,900 (3% full) [Uptime] 1h 36m 20s [System] Java: 11.0.18 (Ubuntu / /usr/lib/jvm/java-11-openjdk-amd64) OS: Linux (5.4.0-144-generic/amd64) Locale: en_US

**Additional context**
[Add any other context about the problem here.]

not a big issue,  and it was previously reported and auto corrected itself
https://github.com/chatty/chatty/issues/335

**Comment by ikeman2003** [comment]
I am having the same issue they don't show at all for me though.

**Comment by tduva** [comment]
The badges API didn't return the correct value types, possibly from some recent changes to better support new FFZ badges. This should be fixed now, you can force an update with `/refresh badges`.

**Comment by arrowgent** [comment]
huh... yes the supported badge returned awhile ago

thanks
