### ISSUE TITLE
Further Livestreamer integration

### ISSUE THREAD

**Issue by ivazqueznet** [chatty/chatty#49]
I've been using the existing Livestreamer support in Chatty and it works... well enough, but I'd like to see it go even further. I would like to have it show up as one of the "Twitch Stream" submenu items. Making the option invoke Livestreamer with the "select" quality option would be perfect, but even prefilling the stream name in the Main tab of the existing Livestreamer dialog box would be handy.

**Comment by tduva** [comment]
Have you tried checking "Enable context menu entry" in the Livestreamer dialog?

**Comment by ivazqueznet** [comment]
Of course I hadn't. *facepalm*

Although I'm not sure it's necessary to have that option anymore; it pretty much just works.
