### ISSUE TITLE
Access missing: "Ban users" (see "Main - Account")

### ISSUE THREAD

**Issue by Sparklekitti** [chatty/chatty#495]
My ability to ban bots has stopped working. Is this something I'm doing wrong?

**Comment by tduva** [comment]
Twitch changed their APIs, so you will have to grant additional access scopes for a lot of features that only required a single one before. You need to go the Chatty's main menu "Main - Account" and then remove your account an re-authorize with the required access.

**Comment by Sparklekitti** [comment]
Thank you so much!
