### ISSUE TITLE
Audio notification for a raid

### ISSUE THREAD

**Issue by parmi93** [chatty/chatty#509]
I currently have 3 audio notifications activated "Subscriber Notification", "New Followers" and "Chat Message" which work perfectly, I was wondering how I can activate the audio notification when I receive a raid?

**Comment by tduva** [comment]
A raid should be displayed as a regular info message, so a notification item of the type "Info Message" with the "Match" field set to `start:[Raid]` (text beginning with `[Raid]`) should work.

![grafik](https://github.com/chatty/chatty/assets/5621113/fd84f1fe-53e2-4016-88c0-5930dd6cd7ba)

**Comment by parmi93** [comment]
Thanks it works.
