### ISSUE TITLE
Update User Pronoun Add-On https://pr.alejo.io/

### ISSUE THREAD

**Issue by liquidnya** [chatty/chatty#517]
**Is your feature request related to a problem? Please describe.**
A new version of the Twitch Chat pronouns Extension was released `v0.2.2` (`v0.2.3` for Firefox):

- There is a new API `https://api.pronouns.alejo.io/v1/pronouns` instead of `https://pronouns.alejo.io/api/pronouns` and `https://api.pronouns.alejo.io/v1/users/<login_name>` instead of `https://pronouns.alejo.io/api/users/<login_name>` with different responses
- The front-end URL has changed from `https://pronouns.alejo.io/` to `https://pr.alejo.io/` (Note that the old URL is still working, but the mixed pronouns feature is not present in the old front-end)

**Describe the solution you'd like**
I would like to see support for the new API which adds the support of mixed pronouns. E.g. someone can have `She/Her` and `Fae/Faer` pronouns now and it would be rendered as `She/Fae`.
I would also like to see the new front-end URL in the Other settings page.

**Describe alternatives you've considered**
Not supporting the new API since the old API is still working.

**Additional context**
New version announcement Tweet: https://twitter.com/AlejoP_47/status/1758170386603082037
Repository of the extension: https://github.com/Alejo47/chat_pronouns_browser_extension
The new implementation of using the new API of a plugin for FrankerFaceZ: https://github.com/FrankerFaceZ/Add-Ons/blob/master/src/pronouns/index.jsx

I would be happy to contribute to this project and create a pull request with the changes needed to make this work as I have upgraded my own tools with the new API changes ([pronouns-chat](https://github.com/liquidnya/pronouns-chat/commit/7c6a4ba1abc4dbd99247c70d798536f0e2cb6fa6), and a closed-source tool written in Rust).
Please let me know if I can work on this.

**Comment by tduva** [comment]
Thanks for letting me know. (Updated in b8862176c925815d0d24d51ac48699e59e282cf0)
