### ISSUE TITLE
Copy/Paste doesn't work on OSX

### ISSUE THREAD

**Issue by flamingghost** [chatty/chatty#55]
Title explains it all. Using latest version of OSX El Capitan. cmd + c, cmd + x and cmd + v doesn't work to copy and paste text, either from the chat pane or from the input text box.

**Comment by GhettoGirl** [comment]
To me this sound more like a bug in the ```Java VM``` or ```Cocoa Framework```, rather than Chatty. Does this also happen in other Java apps?

You should also provide this info, so others can help.
  - Java VM version, check with ```java --version``` or ```java -version``` in a terminal
  - Did copy-paste worked before?

Regards

**Comment by flamingghost** [comment]
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

I can't confirm before, new user on the day of posting

**Comment by GhettoGirl** [comment]
I recommend to update to the latest version of Java. 1.6 is quite old and may not be fully compatible with Chatty.

Grep it from the [Oracle](www.oracle.com) website.

Regards

**Comment by flamingghost** [comment]
I had the latest version installed (1.8.0_91) but apparently java changed the installation location a while back and didn't update file paths for any cli, programs were however running with the correct version.
If anyone else has this issue, install the Java Development Kit, not the normal Runtime installation.

Anyway;
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Copy, Cut, Paste still doesn't work.

**Comment by GhettoGirl** [comment]
That's very strange. I still don't have time to test this myself. I suggest for now that you lookup phrases like "mac java copy paste doesn't work" or "mac java copy issues" or "mac java pase issues" or "mac java cannot access clipboard" or anything like this on your favorite search engine.
My guess is that this maybe could be a permission issue and Java cannot read and write the clipboard. What I'm aware of is that El Capitan indroduces more security options, maybe they added a "Clipboard" category or something. Sorry that I cannot help you more with that at the moment. I'm very busy.

Regards

**Comment by GlitchCog** [comment]
I tested it with 1.8.0_25 on OSX El Capitan. Copy and paste shortcuts work, but not with the Command+C/V like typical Mac OS applications. If you specify that Ctrl+C copies in a Java program, and run that Java program on a Mac, it remains **Ctrl**+C. It doesn't automatically translate from Ctrl to Command.

If you wanted to handle this difference, you'd have to check for the operating system to assign which modifier key to use with these shortcuts. Some of this might help:
```
// Get the default modifier mask for stuff like copying and pasting
int modifierMaskForWhateverOsThisIs = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
// Or to generally detect if it's being run on a Mac (I didn't test this out at all, but it works for "win")
boolean isMacOs = (System.getProperty("os.name").toLowerCase().contains("mac"));
```

**Comment by flamingghost** [comment]
Ahhh! Use the actual ctrl key instead of cmd, why didn't I think of that! Thanks!

**Comment by tduva** [comment]
The Look&Feel is adding those shortcuts and should do it correctly automatically, not sure why it doesn't. If the above fixes it, I guess it could be added, I can't test it though.

**Comment by tduva** [comment]
Please try if this works in the new beta: https://github.com/chatty/chatty/releases/tag/v0.8.3b3

**Comment by flamingghost** [comment]
Works great :) pls also add functionality for CMD+A (cntl+A) to select all

**Comment by tduva** [comment]
More shortcuts in the new beta: https://github.com/chatty/chatty/releases/tag/v0.8.3b4

**Comment by tduva** [comment]
I think this should be covered now, otherwise feel free to comment.
