### ISSUE TITLE
[Request] Setting in settings file for auto-hiding userlist on joining channels

### ISSUE THREAD

**Issue by RedSnt** [chatty/chatty#62]
Currently the default when opening channels is showing the userlist, but I don't have much use for it and have to Shift+F10 a lot to hide the userlist every time I join a new channel.  
I'd love it if it was possible to have a setting in the settings file for disabling the showing of the userlist as default when joining channels. 
It doesn't have to be a "per channel" setting. That would probably be too much work.

**Comment by tduva** [comment]
This was added (https://github.com/chatty/chatty/pull/63).
