### ISSUE TITLE
Quit / Exit keyboard shortcut

### ISSUE THREAD

**Issue by i-cant-git** [chatty/chatty#67]
It would be nice to see a keyboard shortcut for quitting Chatty,
Most programs these days use Ctrl+Q (KeePass) or Ctrl+Shift+Q (Chrome).

**Comment by madman2021** [comment]
There you go @i-cant-git hopefully it gets merged :+1:

**Comment by i-cant-git** [comment]
Thanks @madman2021!

**Comment by tduva** [comment]
A way to configure a hotkey to exit Chatty will be in the next version, thanks to @madman2021.
