### ISSUE TITLE
Support for bits and cheering emotes+badges

### ISSUE THREAD

**Issue by GhettoGirl** [chatty/chatty#71]
Twitch introduced a new feature called **Cheering**. And the API for this is already public. Will there be support for this in Chatty anytime soon?
## 
- Description of [Bits and cheering](http://help.twitch.tv/customer/en/portal/articles/2449458)
- [Twitch PubSub API](https://github.com/justintv/Twitch-API/tree/master/PubSub) to implement this in client applications

**Comment by tduva** [comment]
See https://twitter.com/ChattyClient/status/763460202544914434

**Comment by GhettoGirl** [comment]
Nice. Didn't know you already working on it. Wish Twitter would not hide this kind of tweets :disappointed:

**Comment by tduva** [comment]
Well I started on it today. :) How does Twitter hide that? I only just tweeted it moments ago.

**Comment by GhettoGirl** [comment]
@tduva Just checked my timeline in the Android app, Twitter hides it. :confused:

**Comment by tduva** [comment]
Have you disabled "Show me the best Tweets first" in the Twitter settings? Not sure if that helps at all, but it's worth a try if you haven't yet.

**Comment by GhettoGirl** [comment]
Hey I saw you implemented that feature. I'm wondering if sending bits also works or does this need extra work?
I never read the API doc, but it is possible to receive the number of bits you own?

Regards

**Comment by tduva** [comment]
All that stuff is undocumented.

**Comment by GhettoGirl** [comment]
Oh I see, how unfortunate :(
