### ISSUE TITLE
Support for TLS connections

### ISSUE THREAD

**Issue by Robby-** [chatty/chatty#73]
Since Twitch IRC chat supports TLS on ports 443 and 6697 ([source](https://discuss.dev.twitch.tv/t/psa-chat-servers-are-going-to-migrate-to-aws-ec2-servers/4877)), it would be nice if Chatty also gained support for making TLS connections to Twitch IRC chat.

**Comment by Decicus** [comment]
[It already does](https://chatty.github.io/help/help-releases.html#0.8.2)

**Comment by Robby-** [comment]
Oh! Thank you, totally missed that. I did look at the settings in Chatty itself and didn't see anything TLS related, that is why I thought it didn't. I just tried it, and it works great.
