### ISSUE TITLE
Tab completion for localized usernames

### ISSUE THREAD

**Issue by GhettoGirl** [chatty/chatty#76]
Would be nice to have this feature. Its annoying to actually have to copy-paste the username instead of writing just the first one two chars and than press tab, like you can do for every other username.

**Comment by tmccarthy** [comment]
It may be worth having a look at the [IntelliHints component](http://www.jidesoft.com/javadoc/com/jidesoft/hints/IntelliHints.html) provided by JIDEsoft. In the past when I've had to do suggestion or completion components for Swing, it's been the easiest option.

I believe it's available as part of [JIDE's open source library](https://github.com/jidesoft/jide-oss). This can be added as a dependency by adding the following to the `build.gradle` dependencies block:

```
compile 'com.jidesoft:jide-oss:3.6.15'
```

**Comment by GhettoGirl** [comment]
@tmccarthy I don't get your point here. Chatty already has tab completion for usernames, but doesn't list/support localized ones, just the regular ones. I'm saying it would be a good idea to also list the localized names in that already available list to mention users with their localized username easily. At the moment it has to be copy-pasted with is very annoying.

**Comment by tmccarthy** [comment]
Of course. Sorry, I completely misunderstood :).

**Comment by tduva** [comment]
I'm curious, how do you enter Japanese symbols?

**Comment by GhettoGirl** [comment]
@tduva You never heard about IME's (Input Methods) don't you :smile: There are plenty of them. I personally use **fcitx** (IME) + **Anthy** for Japanese.

**Comment by RedSnt** [comment]
I somewhat support this idea. Currently the way to refer to someone using a localized name is to either copy/paste their name or right click their name, press Twitch profile and then see their true twitch name which is much easier to type out. Meaning that it would be really helpful if the "un-localized" name aka twitch profile name to show up in brackets like it does in regular chat for easier reference.

Just my 5 cents.

**Comment by tduva** [comment]
Uh, showing the original name in brackets is already an option in the latest beta.

Tab completion is almost finished as well.

**Comment by RedSnt** [comment]
> Uh, showing the original name in brackets is already an option in the latest beta.

> Tab completion is almost finished as well.

I just installed the new beta, didn't see the option. But that's great! Thanks for pointing it out.

**Comment by tduva** [comment]
TAB Completion has been improved in [v0.8.4b3](https://github.com/chatty/chatty/releases/tag/v0.8.4b3), I'll be curious to hear your feedback.

By default it shows all types of names for a match, for example if in chat you see: `これは名前です (gradea_name): ..`

Then if you complete `これ` it will show the results `これは名前です` and `gradea_name`, when you complete `gra` then it will show the results `gradea_name` and `これは名前です` (mind the order).

When you use it behind a command like `/ban これ` then it will prefer the regular name.

I thought this might be useful to more easily select the name you want to use, although not sure how well it works in practice.

**Comment by GhettoGirl** [comment]
@tduva Thank you for looking into this and making tab completion more convient. I tested everything with my own Twitch account, since I'm using a localized username. Everything is working great so far, except now with this changes I get a `NullPointerException` when tab completing commands (`/`). From the below exception report this looks like an array out-of-bound. I can continue the exectution without problems. All other completions work normally.

```
at chatty.gui.components.AutoCompletion.showCompletionInfo(AutoCompletion.java:412)
at chatty.gui.components.AutoCompletion.doAutoCompletion(AutoCompletion.java:364)
...
Full log at http://hastebin.com/orivuqobuw.avrasm
```

It crashes here: `src/chatty/gui/components/AutoCompletion.java:412`
```java
// Don't show info popup if there is only one entry and no info for it
if (size == 1 && !results.info.containsKey(items.get(0))) {
    return;
}
```

I tried all possible combinations in the new `Names` page of the settings dialog, but it keeps throwing the exception.

**Comment by tduva** [comment]
It tries to access `results.info` which is null when it's not a result with a Localized/Custom name. The info popup is shown after changing the text, so it will do the completion first. I released a new version to fix this, since it affects more than commands.

**Comment by GhettoGirl** [comment]
@tduva Works now, thanks for fixing it. I guess this issue can be closed now.
