### ISSUE TITLE
ignore list for message sounds

### ISSUE THREAD

**Issue by jjYBdx4IL** [chatty/chatty#78]
I'm using chatty primarily to get notified about chat activity using sound playback. I have a bot that spams chat messages at an interval. Obviously, I don't want chatty to play back sounds for that bot's messages, but I also don't want to fully ignore those bot messages.

**Comment by Decicus** [comment]
Are you using the [highlight system](https://chatty.github.io/help/help-settings.html#Highlight)?

If so, you can specify `config:silent` for that highlight entry and it shouldn't trigger the sound.

**Comment by jjYBdx4IL** [comment]
hmmm yeah, I now somehow abuse the highlighting system by highlighting everything except the stuff I don't want sounds for and switching off sounds for that message alert. ty!
