### ISSUE TITLE
Improve Context Menu setting format

### ISSUE THREAD

**Issue by chatty** [chatty/chatty#8]
Since these settings can contain linebreaks for a while already, make them more flexible:
- Allow custom submenu names
- Allow custom names for entries
- Allow entering of command to be executed right there

Similiar to the mIRC format should be reasonable:

```
Command
Command2
Submenu
.Submenu Entry
.Submenu Entry2
```

This would need some sort of automatic transition between the old and new setting format.

**Comment by chatty** [comment]
Also make sure to add a setting for custom entries in the Stream Context Menu (e.g. in Live Streams dialog).

**Comment by ringstabekk** [comment]
Nice that this was added but with the bottom format can you be able to add a serpartor above the submenu, after Close Channel?

@Modes
./Followersoff /Subscribers /Subscribersoff /Emoteonly /Emoteonlyoff /Slow /Slowoff
|/Mods
/Clear

**Comment by tduva** [comment]
Try it like this:

```
-
@modes
./Followersoff /Subscribers /Subscribersoff /Emoteonly /Emoteonlyoff /Slow /Slowoff
-
/Mods
/Clear
```
