### ISSUE TITLE
Request: Date + Time in Chat message timestamps

### ISSUE THREAD

**Issue by CaitSith2** [chatty/chatty#80]
I would love to be able to have both Date & Time in my Chat message timestamps,  as I often do leave a number of chat windows open to various streamers, and if I don't check them for a few days, it becomes impossible at times to see what day those messages were said.   I am kind of annoyed that logging has Date + Time options for its timestamp, but the chat messages section has Time options only.

**Comment by tduva** [comment]
I'm not sure if I want to add that, since there are so many options already. I suggest you set it manually, for example: /set timestamp [yyyy-MM-dd HH:mm:ss]

More information: http://chatty.github.io/help/help-setting_commands.html#time
