### ISSUE TITLE
Pack Chatty with JRE

### ISSUE THREAD

**Issue by ArmorDarks** [chatty/chatty#81]
Thanks for great app!

Is there any chances to see Chatty packed with JRE? Like SmartGit, which also requires JRE, but it's coming with it own JRE environment, so you don't have to install JRE globally on your PC.

It would make it not only much easier for newcomers to install, since there won't be JRE dependency for users anymore, but also will decrease JRE security issues.

**Comment by lewisje** [comment]
I just hope that Chatty still makes the bare .jar file available, for those of us who *do* install the JRE globally and would rather not have multiple copies of it around.

**Comment by tduva** [comment]
If it ever comes to this I would definitely keep the `.jar` versions available. For one there probably won't be a multi-platform solution for this, so it would still be needed on other platforms. And if someone had issues with running the bundled version, the `.jar` would be a fallback to go to.

**Comment by ArmorDarks** [comment]
I'm not Java developer, so can't tell any details about packed JRE, but SmartGit is multiplatform, and essence of JRE is multiplatform too, so I believe it could be packed for any OS.

> And if someone had issues with running the bundled version, the .jar would be a fallback to go to.

There are greater chances that someone will run into troubles running non-bundled version. Bundled version will come with specific, fixed JRE version, on which app have been tested, so it guaranteed to run, while with user installed JREs there are chances to run into rare issues between different versions.

Not to mention that keeping installed global JRE is quite insecure, at least on Windows.

**Comment by tduva** [comment]
Not sure what you mean, I just gave examples. Obviously multi-platform is possible, but for example [Launch4j](http://launch4j.sourceforge.net/) create Windows executables. So unless a custom wrapper is made, it depends on what solutions there are already. And of course while a bundled JRE is probably better, the native executable itself can still have issues.

How is a globally installed JRE insecure?

**Comment by h1z1** [comment]
Bundling a JRE with Chatty would be bad since it frequently needs updating.  It would also add the the install size.

**Comment by ArmorDarks** [comment]
It would be up to people use bundled version or no. Those days a lot of people avoids software which requires installation of JRE because they simply don't get it. Nobody will die from 90mb exe file with todays Internet.

**Comment by GreyAsteroid** [comment]
I don't think I've ever worked on a computer that doesn't have a JRE installed. I don't think there's really a high demand for a bundled version of chatty.

**Comment by ArmorDarks** [comment]
@GreyAsteroid Unfortunately (or fortunately), that's far from truth on PCs. Do not confuse mobile devices stats with PC.

**Comment by lewisje** [comment]
It's rare to find a mobile device that even supports Java SE; still, it is true that increasingly, people don't feel the need to install a global JRE, and because of the stream of stories about vulnerabilities in Java, others are encouraged to at least disable the plugin, and may instead just uninstall Java altogether.

**Comment by tduva** [comment]
@dehesselle has made me aware of the [javapackager](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javapackager.html) that is included in the JDK, which can create a bundle that includes the JRE. I'm inclined to give this a try. He also made a [bundled version for MacOS](https://github.com/dehesselle/chatty) using this method.

**Comment by dehesselle** [comment]
Let me add my 2 cents to the discussion.

- Bundling the JRE is also one step towards making Chatty portable. That might be interesting to some people.
- All solutions I've come across (including `javapackager`) still retain the (unmodified) `.jar`. So even if @tduva decided to go for a bundled-only releases in the future - i.e. dropping the `.jar`-only releases - you'd still be able to get the `.jar` from that and lose the rest.

**Comment by ArmorDarks** [comment]
That's great news! So far I'm using bundled with plain portable JRE Chatty

![explorer_2016-11-06_19-25-50](https://cloud.githubusercontent.com/assets/4460311/20039964/e0b2bc36-a456-11e6-8b37-d6fb0f314db0.png)

It would be incredible great to have properly packed version, since launching it via bat file and observing console running in background isn't nice thing.

**Comment by dehesselle** [comment]
@ArmorDarks to avoid the console for GUI apps, just use `javaw.exe` instead of `java.exe` in your `Chatty.bat`.

**Comment by ArmorDarks** [comment]
@dehesselle Didn't know about `javaw.exe`, thanks!

**Comment by xaoseric** [comment]
Just thought i would update this, I am working on an installer that does this https://github.com/chatty/chatty/issues/114

**Comment by tduva** [comment]
The [0.8.5b1](https://github.com/chatty/chatty/releases) now contains a Windows version bundled using the javapackager, as I mentioned previously.

**Comment by ArmorDarks** [comment]
Works flawlessly. Thanks!
