### ISSUE TITLE
"i" replaced with garbled characters in whisper message notification

### ISSUE THREAD

**Issue by TrainerTimmy1** [chatty/chatty#82]
Title says it all. I've noticed this bug since 0.8.4 beta 1 and is reproducible any time I get a notification from a whisper. Below is what the bug looks like

![image](https://cloud.githubusercontent.com/assets/12021121/18516166/242acc32-7a55-11e6-941c-a47067b3de4d.png)

**Comment by tduva** [comment]
It's actually not an `i`, I mistyped and it's an `í`. That is easily fixed.

As to why it doesn't display a non-ASCII character properly in the first place, that might have to do with switching to Gradle for building the program. It probably assumes the wrong encoding of the source file when compiling.

**Comment by TrainerTimmy1** [comment]
Cool, thanks for the response!

**Comment by tduva** [comment]
This is fixed in the upcoming version.
