### ISSUE TITLE
Support for Streamlink as Livestreamer alternative

### ISSUE THREAD

**Issue by lewisje** [chatty/chatty#84]
Livestreamer has not been updated in a few months, and although workarounds exist to allow people to watch streams with it, even if they have localized display names, the problems caused by recent Twitch changes have inspired a fork with a different name: https://github.com/chrippa/livestreamer/issues/1478#issuecomment-247710308

The fork hasn't yet gotten to the point of proper executable releases, so watch this space: https://github.com/streamlink/streamlink

**Comment by tduva** [comment]
As long as the Commandline interface stays the same there shouldn't be any changes necessary.

**Comment by lewisje** [comment]
Twitch doesn't allow anonymous API requests anymore, and the most obvious way to keep using Livestreamer is with an OAuth token; however, Livestreamer doesn't handle the response properly if you're using a localized display name: https://github.com/chrippa/livestreamer/issues/1486

The last time Livestreamer was updated was months before Twitch stopped allowing anonymous API access *or* started allowing non-ASCII display names.

The most common workaround is to use the `http-header` command to set the `Client-ID` header to Livestreamer's own client ID, something that isn't quite so obvious from its documentation, but I would like to be able to be logged in via Livestreamer, rather than viewing anonymously.

---
The only changes needed to support Streamlink involve recognizing its name and location (e.g., it's no longer called "livestreamer"); I don't see an option to manually set the location of the Livestreamer binary, and probably the easiest change is to allow that to be set (as long as Chatty will allow it to be set to a program called "streamlink.exe" on Windows, for example).

**Comment by GhettoGirl** [comment]
Just use the Chatty OAuth token for livestreamer, there is even an option in the dialog for it - problem solved. I can still watch Twitch streams with livestreamer without problems. A simple OAuth token seems to do the trick.

**Comment by tduva** [comment]
The `Base command` in the Livestreamer Dialog is what is executed, with the other stuff added behind. You can set that to any executable or path you want, as well as add commandline parameters there that should always be used.

**Comment by lewisje** [comment]
> Just use the Chatty OAuth token for livestreamer

Right now, it only works if your display name is all-ASCII

> You can change the command line, you can literally use Streamlink already

How? I only see options to change the command-line parameters, but not to change the path to the livestreamer binary, so that you can, for example, use a binary that is not named "livestreamer".

**Comment by GhettoGirl** [comment]
@lewisje lol, i have no issue with my localized username and oauth token, sure you just missed anything somewhere

**Comment by lewisje** [comment]
I guess I missed how to make Livestreamer not use the "ascii" codec when parsing the response it gets from the Twitch API; my impression, after looking for such a way and not finding one, was that Livestreamer was hard-coded to use ASCII.

**Comment by GhettoGirl** [comment]
I'm not sure what you tried but my system is UTF-8 and the Python interpreter is also using UTF-8, and so does livestreamer. Thats why it is working for me. 
If you are on Windows than I'm not surprised why it uses ASCII.

**Comment by tduva** [comment]
You should probably discuss the encoding issue at https://github.com/chrippa/livestreamer/issues/1486 or https://github.com/streamlink/streamlink/issues/19, so people can actually find it.

**Comment by lewisje** [comment]
@GhettoGirl, it could well be down to the version of Python; I think my default version of Python is 2.7. Also, the default text encoding in Windows is UTF-16, but most command-line programs that work with Unicode at all do work with UTF-8, and this would make no difference if the program is trying to interpret text as ASCII.

@tduva, I put the error message right in the first post of both Issues.
