### ISSUE TITLE
No font size option for Viewer List

### ISSUE THREAD

**Issue by gabrieleliot** [chatty/chatty#85]
There are font size options for Chat Font & Input Font, but none for the viewer list. I'm running my stream computer monitor at an artificial DSR resolution (2880 x 5120 instead of the native  1440 x 2560) so that I can video capture the output of a full resolution IP Cam from a browser as this has very little lag whereas the rtsp stream link has 3 second lag. 

Everything is usable with large enough windows scaling & font sizes of 32+ selected in the Chatty options. However, the viewer list remains impossibly small. Would there be any way of adding a viewer list font size option much like the other font size options that already exist?

Thanks so much for the awesome program! Nothing else I've found displays my viewer list so well or so easily :-)

**Comment by tduva** [comment]
More font options have been added a while ago.
