### ISSUE TITLE
Livestreamer Command with placeholder

### ISSUE THREAD

**Issue by Bootscreen** [chatty/chatty#86]
is it possible to get placeholder for streamer name in the livestreamer command so we can change the vlc player title to the the streamers name?

**Comment by tduva** [comment]
How does setting the title work?

**Comment by GhettoGirl** [comment]
You can not change or alter the VLC window title without modifying its source code which adds such a possibility. And the title is always `VLC media player` when the media comes from a pipe such as stdin, which is livestreamer doing ─ piping the video stream to VLC.

**Comment by Bootscreen** [comment]
you can. with this command as base command in chatty:
livestreamer --http-header Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6 -p "C:\Program Files\VideoLAN\VLC\vlc.exe --file-caching=5000 --meta-title='<new Stream Title>'"

**Comment by GhettoGirl** [comment]
> `--meta-title`

I missed something in the documentation then :(
Its not mentioned in the `man` page at least.

**Comment by tduva** [comment]
I will add replacements that apply to the `Base command` for `$stream`, `$url` and `$quality`.

**Comment by Bootscreen** [comment]
you are my hero :D 

and here is the docu about the command line parameter of vlc: https://wiki.videolan.org/VLC_command-line_help

**Comment by tduva** [comment]
The info for `$stream`, `$url` and `$quality` is already in place, so it's really easy to add, the stream title isn't. I don't want to make it too complicated.

**Comment by tduva** [comment]
The variables `$stream`, `$url` and `$quality` have been added as of 0.8.4b6.

**Comment by lewisje** [comment]
The variables `$streamtitle`, `$streamgame`, and `$streamuptime` have been added in the latest beta, 0.8.5b1.

**Comment by tduva** [comment]
The Livestreamer command isn't part of the Custom Commands system.
