### ISSUE TITLE
Message "[Info] Exited host mode."

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#89]
I don't host any channel. When I start streaming this message appears twice.
0.8.4b6

**Comment by tduva** [comment]
The Hosting messages seem a bit weird lately. Not much I can do about that.

**Comment by ringstabekk** [comment]
This is an issue with Twitch not with client the thankfully. Have seen the message appear in Twitch chat and BTTV.

**Comment by tduva** [comment]
I'm closing this since it's a Twitch issue.
