### ISSUE TITLE
[IDEA] FFZ Donor Badge (and more?) & BetterTTV Emote Approver Badge (and more?)

### ISSUE THREAD

**Issue by magiruuvelvet** [chatty/chatty#9]
FrankerFaceZ has its Donor Badge and BetterTTV has its Emote Approver Badge.
I don't know about the 2 APIs (never used it, only the Twitch API), but there must be a way to receive this information because the browser add-ons can do it.
It would be an idea to implement this feature, so also Chatty users can know who is a FFZ Donor/BetterTTV Emote Approver :)

EDIT: I found this -> https://api.betterttv.net/2/badges
It seems BetterTTV has some more badges: Developer, Support Team, Design Team, Emote Approver
And there is also the complete user list stored. So it basically can be cached in the settings directory.
(just for reference: https://cdn.betterttv.net/betterttv.js)

EDIT2: For FFZ I also found everything relevant :)
http://cdn.frankerfacez.com/script/script.min.js <-- this is the script which the browser add-on injects to the website.
And FFZ also uses more than just donor badges... Developers and such.
This is at least the donor list http://cdn.frankerfacez.com/script/donors.txt

**Comment by night** [comment]
There is not much point for Chatty to support BetterTTV's badges, since they are just for people who assist with the add-on.

**Comment by tduva** [comment]
The FFZ and FFZ:AP badges are available in Chatty by now.
