### ISSUE TITLE
Support for Twitch Prime user icon

### ISSUE THREAD

**Issue by lewisje** [chatty/chatty#91]
[👑 KappaPrime](http://arstechnica.com/gaming/2016/09/amazon-adds-twitch-perks-to-99year-prime-subscription/)

**Comment by broadstone** [comment]
I did some research for the author here:

In the IRC debug log, turbos still exist and are `@badges=turbo/1;`, and the new twitch prime user icon is indicated by `@badges=premium/1;`

So as in commit 9c7c9cf7a2299f7bb74ec521c11e729ffbb6f6df, where `badges.containsKey("turbo")` was checked, you'll have to check for `badges.containsKey("premium")` for this new state.  It is currently distinct from turbo in terms of badge iconing.

The normal API you use, https://api.twitch.tv/kraken/chat/<CHANNEL>/badges doesn't actually contain the "premium" badge item.

There is this undocumented API, though I'm not sure you're allowed to use it: https://badges.twitch.tv/v1/badges/global/display?language=en  It is what the webchat is using.

It was, however, publicly disclosed here: https://discuss.dev.twitch.tv/t/beta-badge-api/6388 So I assume it is permitted.
In fact, that discussion states how you can precisely use the IRC output to look up the right badge.  "turbo/1", as an example, is root -> "badge_sets" -> "turbo" -> "1" > "image_url_1x"

It also contains the links necessary for loading the badges for cheers (which appear to be linked to total cheer bits paid per user per channel, which appears to be broadcast using the pubsub system for total bit count). That may help with badges for issue #71.  In the case of bits, though, I haven't captured a debug instance of them happening, are probably bits/1, bits/100, or bits/1000, as there entries for each.  They'd be root -> badge_sets -> bits -> "1000" -> "image_url_1x" for example for 1000.

**Comment by broadstone** [comment]
I could try writing some code for this, but honestly I haven't touched java in over a decade.

**Comment by tduva** [comment]
Due to Custom Usericons it requires changes in a lot of places, which is almost done.

**Comment by broadstone** [comment]
I fully suspect turbos in the USERSTATE are done, as eventually turbo state will probably be phased out.

**Comment by tduva** [comment]
Some stuff was [accidentally removed](https://discuss.dev.twitch.tv/t/resolved-unannounced-change-to-irc-fucking-things-up/7592) a few days ago and then put back, except for the `turbo` tag in `USERSTATE`. It's still in the message tags though. And Turbo is probably going to stay for a while still, since Twitch Prime is only available in a few countries.

**Comment by broadstone** [comment]
As of d138ab107db93dfcd9da83f6ba48c8bf6af11c53, the usericon works in the chat feed, though they're not marked in the userlist like turbos are.

**Comment by tduva** [comment]
I haven't touched that yet, since with the new system there can be a lot of badges, I don't think it's feasible to display a symbol for all of them (I'm kind of running out of fitting characters). Since Prime is basically the same as Turbo, do you think it would make sense to use the same symbol?

**Comment by tduva** [comment]
I know that, my point is that they grant similiar benefits to the user, just with different badges, so it may make sense to use the same symbol (`+`). Unless you can think of another fitting ASCII character that isn't already used.

**Comment by ringstabekk** [comment]
As a suggestion is $ available? As that might be good choice for Prime.

**Comment by Decicus** [comment]
I think that `+` should work fine for covering both Turbo and Prime specifically in the userlist, because as mentioned earlier, Prime fully replaces Turbo for those countries that have it available to them. And when it comes to Twitch site/chat specifically, it doesn't add a whole lot of extra features anyway (that's related to this).

As an alternative for those that don't like that idea, you could add the ability for advanced users to override default symbols based on the `badges` tags (if possible).  
So that if they want to, they could get a dialog window similarly to the `Custom names` settings and do this:

| Badge | Symbol |
| --------- | ------ |
| `premium/1` | `:` |
| `turbo/1` | `*` |
| `global_mod/1` | `+` |
| `cheer/1000` | `;` |

**Comment by broadstone** [comment]
$ appears to be used for premium in what I think is the fallback case in the chat stream:
https://github.com/chatty/chatty/commit/32daf5cfb50ff52122b7109522f1422f1f3b584e#diff-6f0dae50d8b824c12da17fa5f363af38R59

**Comment by tduva** [comment]
`$` is going to be used for when the User has a Bits Badge.

Customization of user symbols is currently not planned, at least not for the next version.

The symbols defined in the `Usericon.java` class are used in the main chat window and become visible when an icon is copy&pasted. If a usericon is not loaded then it is not displayed at all, if usericons are disabled altogether (or in other places where there are no images like the userlist) then [User.getModeSymbol()](https://github.com/chatty/chatty/blob/6cc6c653cdedd3cc095612ef8db11b46e4a72871/src/chatty/User.java#L714) is used.

**Comment by JeGr** [comment]
@Decicus / @tduva have it absolutely right. For many countries, Prime is to replace Turbo and Turbo isn't available anymore in this countries. So using the same symbol makes sense to me, as any further bonus thingies aren't chat specific in any way. And users that still use turbo in addition to prime can only select to show one or the other. 👍 
Bits donors using $ in the sidebar is also quite fitting. 👍 
Other than that different subscriber badges are incoming, too (sub, 3, 6, 12 and 24month subs). Just wanted to mention that for what it's worth as I don't know how that will be handled internally in chat (other symbols? or only different icons?)

Would also be nice to have the custom user icon in addition to mod/sub/prime|turbo icon (fourth/fifth one) to have a visual indicator of certain users/groups. ;)

**Comment by tduva** [comment]
@JeGr I'm not sure what you mean by the last sentence.

**Comment by lewisje** [comment]
I think it was talking about marking custom user-groups.

**Comment by JeGr** [comment]
@tduva that was just a bit OT remark about the ability to show custom user specific icons (Settings/Usericons). But I think I was wrong there that they replace another icon as I saw the "addon" option. My bad.
