### ISSUE TITLE
/title command for showing the entire stream title 

### ISSUE THREAD

**Issue by lewisje** [chatty/chatty#93]
I realize that you can see the entire title by going to Channel Info in the right-click menu (in the box labelled "Status"), but it would also be nice to be able to have it show within the chatbox by typing a command in chat.

**Comment by tduva** [comment]
I don't think I want to add a dedicated command for this, although I'm adding stream info variables to Custom Commands, so you will be able to add it yourself (for example `/title /echo $streamstatus`).
