### ISSUE TITLE
Ignore Ctrl-codes when auto-opening Chat Rules

### ISSUE THREAD

**Issue by lewisje** [chatty/chatty#94]
I frequently open several chats at a time, and pick one to watch on Livestreamer, and when the other chats go offline, without any chats from me, I go in there and press Ctrl+W to close that chat; if the chat had Chat Rules set, then they pop up right when I press Ctrl+W, which is annoying because I then have to close that window before I can close any other offline chat tabs.

**Comment by tduva** [comment]
Are you using the latest beta (0.8.4b7)? I changed it in that version. If Ctrl still triggers the rules then I'll have to look into it.

**Comment by lewisje** [comment]
I'll test it later today (was on b6, am currently at work), but my suspicion might have been that the W was what triggered it.
