### ISSUE TITLE
Emote Sets for Turbo (793) and Premium/Prime (19194) are the same

### ISSUE THREAD

**Issue by GhettoGirl** [chatty/chatty#96]
In the Chatty emote dialog there are 2 identical emote sets, `793` for Turbo Emoticons and `19194` for Premium/Prime. On an older release the Turbo set showed up as `Turbo Emoticons` and the Prime set as `-`, now both show up as `--hidden--`. Since the both sets are identical it would be worth to hide one set if someone has both, Twitch Turbo and Prime do avoid unnecessary clutter in the emote dialog.

Maybe it would be good to also check if the emote sets are actually identical before hiding one, but I don't think this will change in the future anyway.

And how about a better name than `--hidden--`? (if you hardcoded that name) :smile:  Maybe something like `Turbo/Premium` or `Turbo/Prime` to mention some examples.

**Comment by Decicus** [comment]
The names `--hidden--` is from the [Twitch Emotes API](https://twitchemotes.com/apidocs): https://twitchemotes.com/api_cache/v2/sets.json

**Comment by GhettoGirl** [comment]
closing this since it is implemented now
