### ISSUE TITLE
[Bug] Animated emotes like SourPls don't scale correctly

### ISSUE THREAD

**Issue by RedSnt** [chatty/chatty#97]
So I finally got around to mess about with emote scaling in Settings -> Emoticons -> Scale, which I set to 130%. It works fine except that all animated emoticons (from BTTV obviously) are maximum scale (200% (/2.0)) whenever you go beyond 100% scaling. And when you go below 100% they don't scale below 100% either, so it's stuck at either 100% or 200% scaling for animated emoticons.

Not sure if this is due to limitations regarding the playback of animated emoticons or if due to some kind of error in the code.. Which is why I'm reporting it as a bug.

**Comment by tduva** [comment]
I don't think scaling animated emotes is very easy, so I wouldn't expect it to work. Although maybe it should snap to the two sizes a bit differently.

**Comment by RedSnt** [comment]
And cheer animations have the same problem if that narrows the problem down - if it can be fixed.

**Comment by tduva** [comment]
Animated emotes can not be scaled with the conventional means. It might be possible in the future, since I'm rewriting most GIF emotes anyway, but for now they'll only go to 2x size when the scale is set high enough, so they aren't immediately huge when you just set it to 130%.
