### ISSUE TITLE
Actual Userlist

### ISSUE THREAD

**Issue by KevinGregull** [chatty/chatty#98]
Greetings, Chatty currently does not seem to have an accurate Userlist. It does only deduce the Users by their writings in Chat, but there is actually an API for figuring all Viewers of a current Channel, by doing:

https://tmi.twitch.tv/group/user/CHANELLNAME/chatters

**Comment by GhettoGirl** [comment]
Chatty uses this API already. Note that on the very big channels (like events) this is explicitly disabled.

**Comment by KevinGregull** [comment]
Oh yes your are actually right. It does seem to work for smaller Channels. Posted it because I did not find the URL in the API Sources. But I guess I am just blind :D

**Comment by tduva** [comment]
No, Chatty only relies on what userlist Twitch Chat provides through IRC.
